### ISSUE TITLE
Can't pass credentials from URL

### ISSUE THREAD

**Issue by Informatic** [glowing-bear/glowing-bear#1005]
Seems like code merged in #644 no longer works, as now `window.location.hash` seems to be prepended with `#!/`. This should be really easily fixable by changing `window.location.hash.substring(1)` to `window.location.hash.substring(3)`.

**Comment by lorenzhs** [comment]
Thanks, yeah, I think this happened when we updated angular.

**Comment by Informatic** [comment]
I think it might be a good idea to document it somewhere. Wiki, perhaps?

**Comment by lorenzhs** [comment]
Yeah I think the only "documentation" for it right now is in the issue tracker. We should probably add something to the readme.
