### ISSUE TITLE
hostmasks should not be clickable like email addresses

### ISSUE THREAD

**Issue by rain-1** [glowing-bear/glowing-bear#1011]
In the buffer any time you see a hostmask, e.g.

```
--> foobar (foo@127.0.0.1) has joined #glowing-bear
```

the `foo@127.0.0.1` is a clickable link to `mailto:foo@127.0.0.1`.

These aren't email addresses and clicking on them by accident happens sometimes, which opens up an email client and it's a bit of an annoyance.

It seems to be coming from this, I think
https://github.com/angular/angular.js/blob/master/src/ngSanitize/filter/linky.js#L131

which doesn't provide any option to not insert mailto. So perhaps we could make a copy of that file and modify it.

**Comment by rain-1** [comment]
I removed all mentions of 'linky' from index.html and added

```
    return function(text) {
        if (!text) {
            return text;
        }

        var urlRegex = /((https?:&#x2F;&#x2F;|www\.)[^\s]+)/gmi;
        var substitute = '<a href="$1" target="about:blank">$1</a>'
        text = text.replace(urlRegex, substitute);
```

in weechat.filter('irclinky' js/filters.js

This works but is it ok that the regex needs &#x2F; ?

**Comment by rain-1** [comment]
This solution is not perfect yet, it has issues with links that have an anchor bit at the end.

**Comment by rain-1** [comment]
```
diff --git a/index.html b/index.html
index 896e178..098a74a 100644
--- a/index.html
+++ b/index.html
@@ -267,7 +267,7 @@ npm run build-electron-{windows, darwin, linux}</pre>
         </div>
 
         <div class="title"  ng-click="showModal('topicModal')">
-          <span class="desktop" ng-repeat="part in activeBuffer().title" ng-class="::part.classes" ng-bind-html="::(part.text | linky:'_blank':{rel:'noopener noreferrer'} | DOMfilter:'irclinky')"></span>
+          <span class="desktop" ng-repeat="part in activeBuffer().title" ng-class="::part.classes" ng-bind-html="::(part.text | DOMfilter:'irclinky')"></span>
           <span class="mobile" ng-class="{'active': activeBuffer().active, 'channel': activeBuffer().type === 'channel', 'channel_hash': activeBuffer().prefix === '#', 'channel_plus': activeBuffer().prefix === '+', 'channel_ampersand': activeBuffer().prefix === '&'}">{{ activeBuffer().trimmedName || activeBuffer().fullName }}</span>
         </div>
 
@@ -337,7 +337,7 @@ npm run build-electron-{windows, darwin, linux}</pre>
               <td class="prefix"><span ng-class="::{'repeated-prefix': bufferline.prefixtext==bufferlines[$index-1].prefixtext}"><a ng-click="addMention(bufferline.prefix)"><span class="hidden-bracket">&lt;</span><span ng-repeat="part in ::bufferline.prefix" ng-class="::part.classes" ng-bind="::part.text|prefixlimit:25"></span><span class="hidden-bracket">&gt;</span></a></span></td><!--
            --><td class="message"><!--
              --><div ng-repeat="metadata in ::bufferline.metadata" plugin data="::metadata"></div><!--
-             --><span ng-repeat="part in ::bufferline.content" class="text" ng-class="::part.classes.concat(['line-' + part.$$hashKey.replace(':','_')])" ng-bind-html="::part.text | linky:'_blank':{rel:'noopener noreferrer'} | DOMfilter:'irclinky' | DOMfilter:'emojify':settings.enableJSEmoji | DOMfilter:'inlinecolour' | DOMfilter:'latexmath':('.line-' + part.$$hashKey.replace(':','_')):settings.enableMathjax"></span>
+             --><span ng-repeat="part in ::bufferline.content" class="text" ng-class="::part.classes.concat(['line-' + part.$$hashKey.replace(':','_')])" ng-bind-html="::part.text | DOMfilter:'irclinky' | DOMfilter:'emojify':settings.enableJSEmoji | DOMfilter:'inlinecolour' | DOMfilter:'latexmath':('.line-' + part.$$hashKey.replace(':','_')):settings.enableMathjax"></span>
               </td>
             </tr>
             <tr class="readmarker" ng-if="activeBuffer().lastSeen==$index">
@@ -542,7 +542,7 @@ npm run build-electron-{windows, darwin, linux}</pre>
           <div class="modal-header">
             <button type="button" class="close" ng-click="closeModal($event)" aria-hidden="true">&times;</button>
             <h4 class="modal-title">Channel topic {{ activeBuffer().shortName || activeBuffer().fullName }}</h4>
-            <p ng-repeat="part in activeBuffer().title" ng-class="::part.classes" ng-bind-html="::(part.text | linky:'_blank':{rel:'noopener noreferrer'} | DOMfilter:'irclinky')"></p>
+            <p ng-repeat="part in activeBuffer().title" ng-class="::part.classes" ng-bind-html="::(part.text | DOMfilter:'irclinky')"></p>
           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-primary" ng-click="closeModal($event)">Close</button>
```

```
diff --git a/js/filters.js b/js/filters.js
index 027acbe..7ef414c 100644
--- a/js/filters.js
+++ b/js/filters.js
@@ -30,17 +30,33 @@ weechat.filter('irclinky', function() {
             return text;
         }
 
+       var urlRegex = /((https?:&#x2F;&#x2F;|www\.)[^\s]+)/gmi;
+
         // This regex in no way matches all IRC channel names (they could also begin with &, + or an
         // exclamation mark followed by 5 alphanumeric characters, and are bounded in length by 50).
         // However, it matches all *common* IRC channels while trying to minimise false positives.
         // "#1" is much more likely to be "number 1" than "IRC channel #1".
         // Thus, we only match channels beginning with a # and having at least one letter in them.
         var channelRegex = /(^|[\s,.:;?!"'()+@-\~%])(#+[^\x00\x07\r\n\s,:]*[a-z][^\x00\x07\r\n\s,:]*)/gmi;
+       var channelSubst = '$1<a href="#" onclick="openBuffer(\'$2\');">$2</a>';
         // Call the method we bound to window.openBuffer when we instantiated
         // the Weechat controller.
-        var substitute = '$1<a href="#" onclick="openBuffer(\'$2\');">$2</a>';
-        return text.replace(channelRegex, substitute);
-    };
+
+       var re = new RegExp(urlRegex.source + "|" + channelRegex.source, "gmi");
+       return text.replace(re, function (m) {
+               if(m.match(urlRegex)) {
+                       // if it starts with www. we need to add HTTP
+                       return m.replace(urlRegex, function(m, p1) {
+                               var link = p1.replace(/^www\./, 'https://www.');
+                               return '<a href="'+link+'" target="about:blank">'+p1+'</a>';
+                               });
+               }
+               if(m.match(channelRegex)) {
+                       return m.replace(channelRegex, channelSubst);
+               }
+               return match;
+               });
+       }
 });
 
 weechat.filter('inlinecolour', function() {
```

This version is working great

**Comment by rain-1** [comment]
an improvement to the link regex would be to avoid ) in links (www.google.com) the close bracket ends up in the link

**Comment by oakkitten** [comment]
a regular expression [i'm using](https://github.com/oakkitten/scripts/blob/url_hint/python/url_hint.py#L110-L205). not ideal but finds urls in ()s while not botching up wikipedia links ending with )

**Comment by lorenzhs** [comment]
Angular's linky is rather static and it's been the cause of a few issues and has come up many times over the years. However, the problem isn't quite as trivial as you may think, because doing this improperly opens us up to escaping issues and thus XSS attacks.

The version of angular used in the master branch (https://latest.glowing-bear.org) also handles links in parentheses properly, so at least that bit is easily fixed.

**Comment by rain-1** [comment]
parenthesis dont matter much, that's just a minor important

the really important thing is that foo@bar.com does not get turned into mailto: link

**Comment by lorenzhs** [comment]
Yeah I get it, I'm just saying linkification isn't trivial and giving a reason why it is what it currently is.

For the record, I just don't display the hostmask in weechat. It's absolutely useless 99.9% of the time.

And `mailto:` links can be useful. It feels a bit stupid to remove them just because linkified hostsmasks suck. There should be a better way. But I'm not sure we can tell whether something is a hostmask or not (or does WeeChat specify that?)

**Comment by rain-1** [comment]
http://github.com/rain-1/glowing

**Comment by 0x52a1** [comment]
>But I'm not sure we can tell whether something is a hostmask or not 

Does the `tags_array` hdata key tell you whether a given line is a join/part/quit? If so, it may be worth just disabling `mailto:` linkification in those lines only, since it's very unlikely that an email address will be in a part/quit message. A workaround for that would disabling linkification for the first `mailto:` link if the `irc.look.display_host_join` and related config options were enabled, which would filter out the hostmask link but still allow email addresses in the part/quit message.

**Comment by Techman-** [comment]
>Does the tags_array hdata key tell you whether a given line is a join/part/quit?

Not sure if this is what you're asking for, but IRC messages that are join/parts/quits are tagged as `irc_join`, `irc_part` and `irc_quit` respectively. I got this from the `/debug tags` view.

**Comment by Techman-** [comment]
Also, @rain-1 I think it's fair to keep this issue open unless another one already exists. It may not be desirable for users to hide hostmasks.

In the meantime, this custom CSS does the trick:
`.coa-chat_host {pointer-events: none;}`

**Comment by lorenzhs** [comment]
Yeah it's a valid issue, it's just not trivial to fix.

**Comment by 0x52a1** [comment]
>IRC messages that are join/parts/quits are tagged as `irc_join`, `irc_part` and `irc_quit` respectively

Great. A fix for this, then, would be to change the `irclinky` filter (or add a new filter) in a way that a list of the bufferline's tags get passed to the filter, and then strip the first `mailto:` link if the tags indicate a join/part/quit (and the weechat settings for showing the hostmask in those messages is enabled). I don't know enough about Angular to know whether that's possible or how to implement it, but it's an idea :smile_cat:

**Comment by lorenzhs** [comment]
Fat fingered users rejoice! @rscullin has come to save us and prevent us from accidentally clicking a hostmask again. Closing this :)
