### ISSUE TITLE
style/theme issue: channels with messages 

### ISSUE THREAD

**Issue by rain-1** [glowing-bear/glowing-bear#1012]
In the channel list on the left, when new messages happen in a channel an indicator with the number of messages appears. this indicator makes the box slightly taller than the rest of the entries.

I think they should all be the same height.

**Comment by rain-1** [comment]
I have solved the problem by editing `./css/glowingbear.css` in this way:

```
.nav-pills li {  
    min-height: 30px;
    max-height: 30px;
}
```

**Comment by lorenzhs** [comment]
Needs a filter on `.buffer` otherwise the first buffer is too far up because it matches the search bar, too. I'll make a PR.
