### ISSUE TITLE
also not show *server* buffers if no unread

### ISSUE THREAD

**Issue by quite** [glowing-bear/glowing-bear#1019]
Would be great if setting "only show buffers with unread messages" would also hide server buffers (when no unread in any of server's related buffers, perhaps)

**Comment by lorenzhs** [comment]
Right, it would be better to only show those server buffers which have buffers with activity. This only applies to the hierarchical view btw. The relevant part of the code is https://github.com/glowing-bear/glowing-bear/blob/7471df0f2a24f5804b51a5d4d47c469f42473259/js/glowingbear.js#L713-L729 -- especially the middle bit.

**Comment by lorenzhs** [comment]
The problem is that this has a watcher and finding and checking all buffers would be prohibitively expensive. So instead we should probably have a mechanism that when a message arrives in a buffer, it should set a flag on its server buffer. Currently a buffer doesn't know its server buffer, though, so we'd have to add that, too. If someone wants to work on this, this is probably how it should be done.

**Comment by quite** [comment]
Nice pointers, I may have a look.

**Comment by quite** [comment]
Isn't this the buffer knowing what type it is of? https://github.com/glowing-bear/glowing-bear/blob/7471df0f2a24f5804b51a5d4d47c469f42473259/js/models.js#L93

**Comment by quite** [comment]
But I can't seem to find any link from a non-server buffer to its parent server buffer. Hm...

**Comment by lorenzhs** [comment]
Thinking about this some more, it would probably be better to have a global object of server buffers, mapping server name to buffer ID. When a buffer of type `server` is created, register it in that object. I might have a crack at that.

**Comment by lorenzhs** [comment]
Does https://latest.glowing-bear.org/pull/1020/ work for you?

**Comment by quite** [comment]
WOw, yes!

**Comment by quite** [comment]
Looking forward to a new android build in the store :>

**Comment by lorenzhs** [comment]
The android app is currently rather unmaintained, I'm afraid. The version in the store is terribly old.

**Comment by quite** [comment]
I was under the impression the app was built from this same repo? But perhaps there is a bunch of android specific code in here..
