### ISSUE TITLE
Linkification is too greedy around brackets

### ISSUE THREAD

**Issue by lluchs** [glowing-bear/glowing-bear#1022]
This is kind of the opposite problem than in #961. Examples:

 - Some message (see http://example.com)
 - (Nested https://en.wikipedia.org/wiki/Parenthesis_(disambiguation))
 - Email-style bracketing `<https://example.com>`

Glowing Bear currently always also includes the closing parentheses with the link. Note how github's Markdown gets the balancing right :)

**Comment by lorenzhs** [comment]
Yeah, we're using Angular's `linky` filter for this and it's bad. There are a bunch of issues about this, see also #820 and #954. If you have the time to integrate a better URL matcher, that would certainly be appreciated. Sadly, detecting where a link should end is a pretty non-trivial problem even before you start taking XSS etc into account...

**Comment by lorenzhs** [comment]
#1029 will improve the situation a bit, but the nested example still won't work---but it overcorrects a bit, in that no parentheses are included at the end...

**Comment by lorenzhs** [comment]
So I guess I should reopen #961 and close this issue once #1029 is merged :D
