### ISSUE TITLE
Electron build failing on linux

### ISSUE THREAD

**Issue by sianhulo** [glowing-bear/glowing-bear#1028]
I get the following:
 ```
make -f electron.makefile build-electron-linux

find bower_components \( -name "*min.js" -o -name "*min.css" \) -exec cp {} 3rdparty \;
cp -r bower_components/bootstrap/fonts .
cp: cannot stat 'bower_components/bootstrap/fonts': No such file or directory
make: *** [electron.makefile:11: copylocal] Error 1
```

I already have bower installed, I don't know if I'm supposed to have another packages as well but the build fails because it seems it can't find files it considers it needs.

**Comment by lorenzhs** [comment]
Did you do `npm install` beforehand? The recommended way to build the electron thingy is
```sh
npm install && npm install electron-packager && npm run build-electron-linux
```

**Comment by sianhulo** [comment]
I don't think I had. But I'm getting the same error running your command. I'm definitely not an expert on anything npm related, but I checked bower.json and bootstrap isn't listed as a component, but as a dev component, which is likely why it wasn't downloaded (all normal dependencies are in bower_components folder but none of the dev dependencies). I decided to comment out said lines but it still failed, this time with: 
```
sed -i.bak 's,https://cdnjs.cloudflare.com/ajax/libs/[^\"]*/,3rdparty/,g' index.html
sed -i.bak 's, integrity=\".*\" crossorigin=\"anonymous\",,' index.html
electron-packager . "Glowing Bear" --overwrite --version-string.FileDescription="Glowing Bear" --ignore=node_modules --ignore=test --ignore=bower_components --platform=linux --arch=x64 --electron-version=1.8.4 --icon=assets/img/favicon.ico
CANNOT RUN WITH NODE 10.12.0
Electron Packager requires Node 4.0 or above.
make: *** [electron.makefile:27: build-electron-linux] Error 1
```
so it is complaining with my node version for some reason, and, even though not mentioned, the icon it tries to set doesn't exist, as can be seen here https://github.com/glowing-bear/glowing-bear/tree/master/assets/img there's no `favicon.ico`

**Comment by sianhulo** [comment]
and, just in case, I updated to node 11 but keep getting `CANNOT RUN` error

**Comment by sianhulo** [comment]
I can't run that command directly, electron-packager is npm installed and I don't know how to run it, attempting to run it directly just gives me command not found (which makes sense given that it wasn't installed with a package manager but with npm).

**Comment by sianhulo** [comment]
ran the commands again today, dunno if it was a change on master or some of the dependencies or both, but I went from having a few vulnerabilities according to npm to having none, and this time `npm run build-electron-linux` ran properly.

**Comment by lorenzhs** [comment]
I updated a bunch of things, yeah. Glad that it works now! :)

**Comment by EbonJaeger** [comment]
This may have broken again. Attempting to run `npm install && npm install electron-packager && npm run build-electron-linux` on a fresh git clone fails with this:

```nodejs
> make -f electron.makefile build-electron-linux

find bower_components \( -name "*min.js" -o -name "*min.css" \) -exec cp {} 3rdparty \;
cp -r bower_components/bootstrap/fonts .
cp: cannot stat 'bower_components/bootstrap/fonts': No such file or directory
make: *** [electron.makefile:11: copylocal] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! glowing-bear@0.8.0 build-electron-linux: `make -f electron.makefile build-electron-linux`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the glowing-bear@0.8.0 build-electron-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Attached is the npm debug log.
[glowing-bear-npm-failure.log](https://github.com/glowing-bear/glowing-bear/files/2559706/glowing-bear-npm-failure.log)

**Comment by lorenzhs** [comment]
Ah! The problem is that `npm install` runs `bower install -p`, but bootstrap is marked as `devDependency` in bower.json and thus not installed automatically. Right now you can run `bower install` manually to fix this. The commit that broke this is d168d432615e0c84393c82280fb72b6d2e5a455d from #987. I'll see what we can do about it without having to revert that (it speeds up the tests *a lot*).

**Comment by lorenzhs** [comment]
Hopefully fixed it for good now by adding the `bower` make target to the command line run by `npm run build-electron-linux` (and windows/darwin)

**Comment by EbonJaeger** [comment]
That does indeed seem to have fixed it. Builds fine now.
