### ISSUE TITLE
The setting “Mark messages as read in WeeChat” doesn't work

### ISSUE THREAD

**Issue by oakkitten** [glowing-bear/glowing-bear#1035]
With the setting on, buffers are marked as read upon focusing/unfocusing them in g-b. With the setting off, only on unfocusing.

**Comment by lorenzhs** [comment]
What's your weechat version? That's behaviour that depends quite heavily on the version of weechat.

**Comment by oakkitten** [comment]
WeeChat 2.2 on Raspbian GNU/Linux 8 (jessie) 4.9.77-v7+

**Comment by lorenzhs** [comment]
Ah! It would seem that we need a condition on `settings.hostlistsync` here: https://github.com/glowing-bear/glowing-bear/blob/6bf2ea6b02732ee7d3684d6b2ae656c25736966a/js/inputbar.js#L202-L205

**Comment by lorenzhs** [comment]
Context: this is the code that's executed when you send a message. It marks the buffer as read, which makes sense if you want your state synced with weechat. But if you don't want *any* sync, then it probably shouldn't do that.

**Comment by oakkitten** [comment]
it happens when i simply click around. but yeah, when i send a message, buffer is marked as read as well.

**Comment by lorenzhs** [comment]
Oh shit yeah, this needs a condition as well: https://github.com/glowing-bear/glowing-bear/blob/41bea6ec7e6ec82506208a6d748610a8b3d2bd18/js/glowingbear.js#L519-L525

**Comment by lorenzhs** [comment]
Can you give https://latest.glowing-bear.org/pull/1036/ a shot in 15 minutes or so? (gotta wait for the cronjob to run)
