### ISSUE TITLE
Some unicode characters displayed as pngs

### ISSUE THREAD

**Issue by JulienPalard** [glowing-bear/glowing-bear#1042]
Some unicode characters, like 👌 (U+1F44C) is displayed as an image from https://cdn.jsdelivr.net/emojione/assets/png/1f642.png?v=2.2.7

Sadly (or not) I'm blocking it with CSPs, so I can't see those characters. But also my browser display them properly when simply displayed as characters so I don't understand why they are replaced by pngs.

I tried grepping jsdelivr in glowing-bear but my front-end-fu is not at this level and git grep found nothing.

**Comment by lorenzhs** [comment]
Have you tried turning off "Enable non-native Emoji support" in the settings?

**Comment by JulienPalard** [comment]
Woah, it works, I like when the fix is easy (also feel dumb not reading the settings before posting). Thanks!

**Comment by lorenzhs** [comment]
:)

We should maybe check how widespread native emoji support has become among desktop browsers, at some point it will make sense to disable the option by default.
