### ISSUE TITLE
Hidden Slack channels have strange name prefixes (square F02)

### ISSUE THREAD

**Issue by jan-vandenberg** [glowing-bear/glowing-bear#1043]
I just upgraded the wee_slack.py plugin, and in WeeChat everything looks fine. 

But in Glowing Bear the muted channels have a strange prefix (see screenshot).

I understand this might be more of a wee_slack.py problem but since this wasn't the case before I was wondering if this is some sort of style parsing issue in GB?

![Screenshot 2019-04-11 at 18 56 31](https://user-images.githubusercontent.com/13764557/55976236-fc9f0400-5c8b-11e9-836d-f920adc00f4e.png)

**Comment by AStove** [comment]
What is it supposed to look like in weechat?

**Comment by jan-vandenberg** [comment]
In WeeChat they are greyed out

![image](https://user-images.githubusercontent.com/13764557/87761369-a2d3a500-c811-11ea-805b-81443bbf72ad.png)

**Comment by AStove** [comment]
Ah ok so it's probably a color control character. I'll look into it.
