### ISSUE TITLE
How do I run glowing bear on a machine with no internet connection? 

### ISSUE THREAD

**Issue by dmahony** [glowing-bear/glowing-bear#1047]
I need to use glowing bear for an offline communication project and it wont work without fetching some javascript sources from the internet, I tried to host the files locally but could never get it to work. Any ideas?

**Comment by lorenzhs** [comment]
Have you red the section "*Can I make it so that there are no requests to third party servers at all?*" in the FAQ in the readme? It explains exactly that. If it doesn't work, say what you did, and what did and didn't work.

**Comment by lorenzhs** [comment]
Using the Electron app is probably the nicest way of doing this. Run `npm install; npm install electron-packager; npm run build-electron-{windows, darwin, linux}` (choose your platform from the list, e.g. build-electron-darwin for macOS)

**Comment by dmahony** [comment]
Thanks for your help, my bad for not seeing the FAQ. I had another attempt and everything is working offline.

**Comment by lorenzhs** [comment]
Excellent, great to hear! :)
