### ISSUE TITLE
`electron-start.hml` not working with current electron version

### ISSUE THREAD

**Issue by rio-** [glowing-bear/glowing-bear#1048]
I used to run Glowing Bear using

    electron "https://latest.glowing-bear.org/electron-start.html"

However, with the current version of electron (1.4.1) this is no longer working and all I get is a white window.

**Comment by lorenzhs** [comment]
I'm no expert on electron but I don't think that's how it works? You need to run `npm run build-electron-windows` (or `-linux` or `-darwin`) to build it. Then you can execute `./Glowing-Bear-*/Glowing\ Bear` to run it.
