### ISSUE TITLE
highlight when nick is mentioned

### ISSUE THREAD

**Issue by zaro0508** [glowing-bear/glowing-bear#1049]
I'm using weechat (ver 1.9.1) with glowing bear (ver 0.7.1) on safari (ver 12.1) and when my nick is mentioned the behavior is different in weechat than in glowing bear.  In glowing bear the text of the nick that mentioned me is in bold yellow[1] while in weechat the entire nick text and background is highlighted[2]

Its difficult to tell in glowing bear if you already have colorized names.  Is it possible to make glowing bear highlight the same as weechat?

[1] https://pasteboard.co/Ih7h5NU.png
[2] https://pasteboard.co/Ih7hiEX.png

**Comment by lorenzhs** [comment]
You can use the custom CSS box in the settings to style the `highlight` class, see https://github.com/glowing-bear/glowing-bear/blob/a5ad0ca1d88373525daa6d3c34da49ff807edcc7/css/themes/dark.css#L2111-L2115 for how it's handled by the dark theme. The maybe nicer long-term solution would be to read WeeChat's settings, but I don't think that's going to happen anytime soon.
