### ISSUE TITLE
Uploading Images should ask consent

### ISSUE THREAD

**Issue by brauner** [glowing-bear/glowing-bear#1050]
When sharing images with people glowing bear should really ask whether it is ok to upload those images to imgur by default. I was pretty surprised when it didn't ask me whether it's ok to upload the image but suddenly just showed me an imgur url. Especially from a GDPR perspective this seems kind of dangerous.
Could there be some way to ask for consent before? :)

**Comment by lorenzhs** [comment]
Sure, we could add a notice the first time that button is clicked. Would you like to do this?

But I'm not quite sure what you expected to happen. Glowing Bear runs entirely in your browser, there is no server component, so uploading to a public image board is kinda the only way to include image sharing. But I agree that it might not be immediately clear to users.

**Comment by brauner** [comment]
> Sure, we could add a notice the first time that button is clicked. Would you like to do this?

I would but I'm a kernel guy and Javascript is really not my cup of tea or expertise. :)

> 
> But I'm not quite sure what you expected to happen. Glowing Bear runs entirely in your browser, there is no server component, so uploading to a public image board is kinda the only way to include image sharing. But I agree that it might not be immediately clear to users.

Just a warning and selection the first time would be nice, i.e. warn that this would upload and ask whether to proceed and maybe the option to remember the selection.

**Comment by lorenzhs** [comment]
I'm a C++ algorithms guy and can only write javascript while holding my nose (but it is possible) ;) But this shouldn't be too hard to add, hopefully I'll get around to it soon-ish.

**Comment by lorenzhs** [comment]
A shit, yeah, the paste thing is bad. Your idea sounds like a good mitigation. "Use _this link_ if you want to delete this image (copy it now, it won't be shown again), or log into your imgur account in Settings" or something like that.
