### ISSUE TITLE
Integrate with dpaste.de

### ISSUE THREAD

**Issue by spapas** [glowing-bear/glowing-bear#1051]
It would be nice if there was dpaste.de integration (similar to the already existign pastebin integration). There doesn't seem to be a full API for retrieving snippets but just appending `/raw` to the url will get you the raw code, for example: https://dpaste.de/udYr/raw

Thus it should be simple to implement something similar to the already existing pastebin plugin.

**Comment by lorenzhs** [comment]
Sure, send a pull request if you want to add it. There are too many pastebin sites out there for us to implement support for all of them, but nobody is going to stand in your way if you want to add support for it to Glowing Bear :)
