### ISSUE TITLE
Backticks in URLs causes problems with codify filter

### ISSUE THREAD

**Issue by mcpower** [glowing-bear/glowing-bear#1058]
[The `text.replace` in the `codify` filter](https://github.com/glowing-bear/glowing-bear/blob/6ab4ef7d88668bfb7a985fef48b3923787f4d95b/js/filters.js#L243-L246) replaces backticks everywhere in the text, including in HTML tags - most notably `<a>`s generated by the `linkify` filter.

For example, the message

    http://google.com/`weird` one http://google.com/`weird` two http://google.com/`weird` three

is rendered like

![screenshot](https://user-images.githubusercontent.com/6015058/63224464-0c18f580-c208-11e9-8a22-6ba8d37fcebf.png)

due to there being two backticks in the `href` attribute of the anchors, and the message

    `http://google.com/` one `http://google.com/` two `http://google.com/` three

is rendered like

![screenshot](https://user-images.githubusercontent.com/6015058/63224481-4aaeb000-c208-11e9-8d69-34ed92f37ae8.png)

due to there being one backtick in the `href` attribute of the anchors.

One way to fix this is to walk the DOM in the `codify` filter and only apply the backtick replacement on top-level text nodes... That seems a bit complicated for a simple formatting filter - is there a simpler way?

**Comment by lorenzhs** [comment]
Maybe we should just move the backtick filter further down in the filter hierarchy, or require that there be a space before the initial backtick. Github for example handles it correctly: http://google.com/`weird`
