### ISSUE TITLE
Weechat 2.6 - No visible text

### ISSUE THREAD

**Issue by Tony763** [glowing-bear/glowing-bear#1061]
Hi,
 after my Ubuntu updated Weechat to version 2.6 - I can't see a text in Glowing Bear.

Weechat 2.6 is running in TMUX as Service
Glowing Bear - latest from git is running locally

![image](https://user-images.githubusercontent.com/5598750/64728231-da2f4200-d4da-11e9-90f0-cd5fe542f46c.png)

**Comment by lorenzhs** [comment]
Uff, I don't have a WeeChat 2.6 around, but are you sure it's related to the upgrade? What happens if you force reload weechat? Because this looks quite a bit like what happens when there's a caching issue.

**Comment by Tony763** [comment]
Tried, killing weechat and start it again not helped. I can see a times of incoming messages from servers logging in, but still no text.

**Comment by lorenzhs** [comment]
Sorry, don't know what I was thinking when typing that, I meant force-reloading Glowing Bear, not WeeChat :see_no_evil:

**Comment by Tony763** [comment]
No problem, When I force reload Glowing Bear, it jump to login page and back to buffers (autologin enabled). with same behavior.

**Comment by lorenzhs** [comment]
Hm, thanks for trying it out, I'll try to debug this later.

**Comment by lorenzhs** [comment]
Well I can't reproduce this, just built WeeChat 2.6 from source. Can you try using Glowing Bear in an incognito window to rule out any caching issues?

![Screenshot from 2019-09-14 21-44-36](https://user-images.githubusercontent.com/142205/64913039-e7e20300-d738-11e9-8c14-a0ac757fd358.png)

**Comment by Tony763** [comment]
HA - incognito works.

**Comment by lorenzhs** [comment]
Yeah it’s a cache issue then. Reload Glowing Bear until it works, the specific keyboarding for a force reload depends on your browser.
