### ISSUE TITLE
Two whitespace characters are appended after nickname completion

### ISSUE THREAD

**Issue by KeepBotting** [glowing-bear/glowing-bear#1065]
Steps to reproduce:

1. Connect Glowing Bear to a relay
2. Enter a channel and attempt to tab-complete a nickname
3. Notice the resulting string `nickname:  ` contains two whitespace characters after the separator

Changing the separator as described in [release notes](https://weechat.org/files/releasenotes/ReleaseNotes-2.4.html) also has no effect on Glowing Bear

**Comment by lorenzhs** [comment]
https://github.com/glowing-bear/glowing-bear/blob/162a23304bc22030c89b3b78ebac861429c50cf0/js/irc-utils.js#L147 *ahem*

**Comment by Techman** [comment]
Looks like the WeeChat relay protocol has a [way to check the version of WeeChat.](https://weechat.org/files/doc/devel/weechat_relay_protocol.en.html#command_info)

**Comment by lorenzhs** [comment]
I know, we use it in several places already, but this isn’t version-dependent behaviour, it’s a changed default and you can produce either behaviour with either version. It’s much more robust to check the actual values used.
