### ISSUE TITLE
Feature Request: Dim non-typed messages

### ISSUE THREAD

**Issue by Fmstrat** [glowing-bear/glowing-bear#1067]
In Weechat Android, there is a nice feature to dim out (decolorize and make a dim gray) any messages that are not typed (join/quit/etc). When you get into a channel that has a lot of these, it can get pretty unruly:

![gb](https://user-images.githubusercontent.com/971474/68947494-95968000-0783-11ea-931d-4f86633cd074.png)

Any chance we could implement this feature?

**Comment by lorenzhs** [comment]
Formatting is controlled by your weechat settings, if you dim then in WeeChat, they'll be dimmed in GB. Or you could use smart filter to hide them. This is what it looks like for me:
![Screenshot from 2019-11-15 15-26-45](https://user-images.githubusercontent.com/142205/68950390-5a647300-07bc-11ea-8574-7d55642a2049.png)

**Comment by Fmstrat** [comment]
@lorenzhs How did you pull that off? I used these set commands, and everything is dark gray in the console weechat client, but not in Glowing Bear.

```
/set irc.look.color_nicks_in_server_messages off
/set colorize_nicks.look.ignore_tags irc_join,irc_part,irc_quit
/set irc.color.message_join darkgray
/set irc.color.message_quit darkgray
/set irc.color.reason_quit darkgray
/set weechat.color.chat_tags darkgray
/set weechat.color.chat_nick darkgray
/set weechat.color.chat_host darkgray
/set weechat.color.chat_delimiters darkgray
/set weechat.color.chat_channel darkgray
```

**Comment by oakkitten** [comment]
you can use [triggers](https://github.com/weechat/weechat/wiki/Triggers#colors-for-joinpartquitnickmodedisconnect)

**Comment by lorenzhs** [comment]
Aaaah that's where I did that:
```
 09:57 		  nocolor: modifier(weechat_print)
09:57 		           =? "${tg_tags} =~ ,irc_(nick(_back)?|join|part|quit|mode|topic|kick|3[236][0-9]),"
09:57 		           ~1 ".*" --> "${color:darkgray}${tg_prefix_nocolor}\t${color:darkgray}${tg_message_nocolor}"
```
Thanks @oakkitten

**Comment by Fmstrat** [comment]
I will update this as it becomes final, but this gives dark gray with blue links for channel and id. The goal will be to make it all dark gray just like in the Weechat terminal client.

```
/trigger add nocolor modifier 2000|weechat_print "${tg_tags} =~ ,irc_(nick(_back)?|join|part|quit|mode|topic|kick|3[236][0-9])," "/.*/${tg_prefix}\t${color:darkgray}${tg_message_nocolor}"
```
