### ISSUE TITLE
Background colors are incorrectly parsed on recent WeeChat versions

### ISSUE THREAD

**Issue by oakkitten** [glowing-bear/glowing-bear#1071]
Since June, WeeChat uses `~` instead of `,` to separate foreground and background colors. Glowing-Bear doesn't parse it and displays e.g. `~09a~06s~14d` instead of `asd`

https://github.com/weechat/weechat/issues/1264
https://github.com/weechat/weechat/commit/7aa82db47106206b8e1bc0c56d34530ec25d23e6
https://weechat.org/files/doc/stable/weechat_dev.en.html#color_codes_in_strings

**Comment by lorenzhs** [comment]
Might be https://github.com/glowing-bear/glowing-bear/blob/564764c7f0e336a85db04d09ed446e7a540f9e96/js/weechat.js#L366 and should probably be an easy fix. Can you try replacing the `,` in that regex with `[,~]`?

**Comment by oakkitten** [comment]
Yep this seems to work
