### ISSUE TITLE
Some types of embedded media open in browser instead of Web (Epiphany) app window

### ISSUE THREAD

**Issue by rodneyrod** [glowing-bear/glowing-bear#1079]
On Manjaro Gnome x86_64

Steps to reproduce:
1. Create a web app in Gnome Web (Epiphany)
2. Open, sign in
3. Expand any Youtube or Google Maps embedded media.

The media will open up in the default web browser instead of being loaded embedded in the Glowing Bear web app.

**Comment by lorenzhs** [comment]
That’s probably not our bug, the plugin code just adds an iFrame with the embed code. If the system intercepts that, there’s nothing we can do about it. I think your setup is too uncommon for anyone else to debug it, though if you can figure out how to fix it, I’d gladly merge a pull request.

**Comment by rodneyrod** [comment]
That's fair, I'll go open up a bug over with them and see, I'll close this for now.
