### ISSUE TITLE
Highlight sound plays upon opening the tab

### ISSUE THREAD

**Issue by AStove** [glowing-bear/glowing-bear#1093]
Often if there's a highlight while browsing in another tab the sound doesn't play. The favicon does change. The sound is then played upon opening the tab. Often but not always.

**Comment by lorenzhs** [comment]
Sounds like your browser is blocking background sounds, not much we can do about it. Which browser are you using?

**Comment by AStove** [comment]
Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by AStove** [comment]
I was running it in http mode back then. I also noticed the site did not have notification permission.

**Comment by AStove** [comment]
Very related: https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome

**Comment by AStove** [comment]
Reproduce:

- Open new tab to glowing bear
- Connect, do anything, just don't get highlighted
- Open another tab so glowing bear is in the background
- Get highlighted
- Open tab, sound plays upon opening
