### ISSUE TITLE
Sidebar overlaps the bufferlines after dragging tab

### ISSUE THREAD

**Issue by AStove** [glowing-bear/glowing-bear#1094]
When draging the tab in chrome and detaching the tab from the current window, and sticking it to a new window there is a chance that the sidebar will overlap the bufferlines.

The sidebar is always displayed correctly however sometimes the bufferlines don't get the `sidebar-state=visible`. This prevents the margin-left from being applies so it's under the sidebar. The sidebar also has a different width when this happens because the `#sidebar[data-state=visible]` is not applied. See screenshots for what I mean.

The reason I think this happens is it resizes the window to below the mobile size limit. If you then add it to a full size window again it resizes again. It doesn't always seem to reproduce. If you have no success in reproducing try having a different buffer open 

Bug presents itself:
![2019-12-16_19-57-19](https://user-images.githubusercontent.com/23409814/70936892-a1f05000-2043-11ea-965a-ba49da8c5896.png)

Correct for comparison:
![2019-12-16_19-57-37](https://user-images.githubusercontent.com/23409814/70936893-a288e680-2043-11ea-8e6b-4f44743c8ed0.png)

**Comment by AStove** [comment]
The side bar is set to hidden, it's just that the current CSS has a rule that only actually hides it when de window width is lower than 968px.
So somehow a resize event is missed that shows the sidebar.

**Comment by lorenzhs** [comment]
Huh, yeah, I can reproduce this in Chrome but not in Firefox. Weird. Maybe it's a Chrome bug?

**Comment by AStove** [comment]
I think in firefox it doesn't actually create or resize the tab while drag dropping, only shows a ghost image. In chrome it creates a new window while dragging the tab and then destroys this window again when releasing. For me at least, in windows.
