### ISSUE TITLE
Performance of switching buffers

### ISSUE THREAD

**Issue by AStove** [glowing-bear/glowing-bear#1100]
I've notice that switching buffers takes a while (>1.5s). I investigated with the performance tab in chrome dev tools. I've found that [this line](https://github.com/AStove/glowing-bear/blob/f3e97e3ec21218a37cf0d0893bfc5793f44d81ba/js/filters.js#L101) took a lot of time. I've tried to imporove upon it and found a way that is much faster. However it uses jQuery. Is there another way to do soemthing similar without jQuery?

Original time of the click event of switching a buffer:
```
var el = document.createElement('div');
el.innerHTML = text;
1.57s
1.75s
1.40s
1.51s
```

New time of the click event of switching a buffer:
```
var el = $("<div>").append($sce.getTrustedHtml(text)).get()[0];
0.96s
0.73s
0.67s
0.77s
```

**Comment by AStove** [comment]
Got it down to:
0.29s
0.35s
0.29s
0.29s

However I discovered this only occured when the develloper console is open.. Believe it or not, I worked on a fix for this and only figured this out afterwards.

https://github.com/AStove/glowing-bear/commit/92239feb47d1225c91ee15a5f5e2efff1857dad6

What I do there, when switching buffers, hide the bufferlines instead of removing them from the DOM. This shows the bufferlines of the new buffer faster. Then a second later they get deleted from the DOM anyway. Because removing things from DOM is expensive apparently, but one of the dev console is open...

Since this is not an actual issue, will close.

**Comment by lorenzhs** [comment]
Huh, what a brilliant idea! Very cool

**Comment by lorenzhs** [comment]
Do you think it would be possible to hide the bufferlines another way than with a watcher on `hidden`? I'm a bit wary of adding more watchers because it makes the interface really sluggish when a lot of lines are loaded

**Comment by AStove** [comment]
First I tried with two `tbody` tags, one for each array of bufferlines. With some work I could make that work. Then it'd just be one or two watchers.
