### ISSUE TITLE
Toast of "NICK has left the room" appears when clicking on nick in PM buffer

### ISSUE THREAD

**Issue by mcpower** [glowing-bear/glowing-bear#1108]
Commit afcc264f99ef285747d527e2004a852ea6624554 introduced a feature which displays "NICK has left the room" when clicking on a nick not on the nicklist. However. PM buffers do not have a nicklist. so the message appears every time when clicking on a nick in a PM buffer.

Perhaps `queryNicklist` could check for whether there is no nicklist?

**Comment by lorenzhs** [comment]
Oh no, I completely forgot to test that in a PM buffer. Thanks for the report!

**Comment by lorenzhs** [comment]
Should be fixed in https://latest.glowing-bear.org/ (in 20 minutes or so), can you confirm?

**Comment by mcpower** [comment]
I can confirm that the issue has been fixed - thanks for the speedy bug fix! 😄
