### ISSUE TITLE
No way to set timezone for timestamp

### ISSUE THREAD

**Issue by guoqiao** [glowing-bear/glowing-bear#1111]
I work for a global company, we use UTC for work, my weechat server is also in UTC.
However, in glowing-bear, it's always showing time in local/browser timezone.
We need a setting to specify timezone, at least allow me to switch between local time and UTC.

**Comment by AStove** [comment]
If your OS (windows?) is set to UTC it will show UTC. Isn't that how is should work? Is there any other application where divert from OS settings only for that application?

**Comment by guoqiao** [comment]
hi AStove,  I use both macOS and Ubuntu, but I only want irc/weechat to show UTC time.

**Comment by AStove** [comment]
Would it be a good idea to link the weechat setting to glowing bear so this woudn't have to be done twice?

**Comment by guoqiao** [comment]
@AStove  as I known, weechat only has settings `buffer_time_format`, but no such settings for `buffer_time_zone`.
I run both weechat and glowing-bear on a VPS which has UTC time. When I ssh to that VPS and use weechat directly, I get UTC time, which is expected. However, when I  open glowing-bear in browser, it uses timezone in my browser, which is different from weechat and is not what I want.

**Comment by AStove** [comment]
Apparently the normal way to set the timezone in weechat is [with an environment variable](https://weechat.org/files/doc/devel/weechat_faq.en.html#timezone).

Wouldn't be able to read this with the relay so disregard my comment.

**Comment by guoqiao** [comment]
The other way to work around is: 
glowing-bear get time from weechat as pure string(if we can), do not parse it to Date. 
So we always get same timestamp display, and we can get ride of the complex time format string conversion in https://github.com/glowing-bear/glowing-bear/blob/c7a5a65ed74f4a084666e0d32b8aac0fe4002fd6/js/connection.js#L85

This piece of code also introduced another "bug": it always uses '/' to join time parts, regardless what ever you use in weechat.conf, which confused me for a while when I was changing time format.

**Comment by guoqiao** [comment]
> Apparently the normal way to set the timezone in weechat is [with an environment variable](https://weechat.org/files/doc/devel/weechat_faq.en.html#timezone).
> 
> Wouldn't be able to read this with the relay so disregard my comment.

Ah, thanks for that, I did come access that section before, but since I am using UTC on server, so have no tz issue with weechat itself.

**Comment by AStove** [comment]
As mentioned in https://github.com/glowing-bear/glowing-bear/pull/1112#issuecomment-613507353_

You could use an extension for this. Would this solve your issue?
