### ISSUE TITLE
Nick completion only works for the first nickname

### ISSUE THREAD

**Issue by AStove** [glowing-bear/glowing-bear#1121]
As of version 2.4 of weechat the default value of `weechat.completion.nick_completer` is ": ". Nick completion works for the first nickname, but does not cycle tot he second nickname.

This works correctly with `weechat.completion.nick_completer` set to ":" which used to be the default value before 2.4. I've never noticed the nickcycling being broken because I inherited the old default values.

**Comment by lorenzhs** [comment]
Is this the same as #1062 or yet another issue?

**Comment by AStove** [comment]
You are correct, this is a duplicate. But now we know the reason. I'll add the new info to the old issue.
