### ISSUE TITLE
Input history broken if nothing in input

### ISSUE THREAD

**Issue by AStove** [glowing-bear/glowing-bear#1130]
It seems like the input history (arrow up) does't seem to work unless there's at least 1 character already in the input.

**Comment by lorenzhs** [comment]
Thanks, looks like that's a regression, I'm pretty sure it used to work

**Comment by AStove** [comment]
Yeah it's because of this https://github.com/AStove/glowing-bear/commit/a318c447ffd4e158b3f53f66f7f2713c46e8a0b0
My bad.
