### ISSUE TITLE
Feature request: Warning certificate expiration

### ISSUE THREAD

**Issue by AStove** [glowing-bear/glowing-bear#1131]
I'd like to see a warning before the websocket's certificate is about to expire. Detailed reasoning why: [issue](https://github.com/weechat/weechat/issues/1508)

In that issue I have requested an additional info to get the expiration of the ssl certificate for the websocket. Javascript cannot get the certificate info or I would have suggested doing it like that.

How should we show the warning? How often and where? I'd suggest a dismissable, but infinite duration snackbar thing at the bottom of the bufferlist. Where other warnings already appear. Appears once every day. And starts to appear 14 days before expiration of certificate. Most certificates get renewed a month in advance at least, if that's not happening, something is wrong.

What can happen is that the certificate is renewed, but weechat has not loaded it yet. In that case the certificate warning would come. But maybe we can put a button to automatically reload the certificate or something.

**Comment by lorenzhs** [comment]
See https://github.com/weechat/weechat/issues/1508#issuecomment-629082947, I don't think this is something we want in the relay protocol
