### ISSUE TITLE
Need help on Nginx proxy configuration....

### ISSUE THREAD

**Issue by axzxc1236** [glowing-bear/glowing-bear#1135]
So I have done these things:  
1. Get a DDNS domain name, point that to my IP address  
2. Get let's encrypt certification
3. Setup ssl.irc relay to open to Internet

Things are well so far, but I want to setup Nginx proxy instead of using built in https server of Weechat, and I want to automate certificate renewal with Nginx only (do it in one place).  
I've followed [the wiki guide](https://github.com/glowing-bear/glowing-bear/wiki/Proxying-WeeChat-relay-with-a-web-server#nginx), came up with this configuration

```
#Weechat relay configuration
limit_req_zone $binary_remote_addr zone=weechat:10m rate=5r/m;

# server configuration
server {	
	# SSL configuration
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	
	ssl_certificate       /home/user/nginx-cert/fullchain;
	ssl_certificate_key   /home/user/nginx-cert/key;
	server_name (my domain name);	

	location /weechat {
        	proxy_pass http://localhost:35999/weechat; # Change the port to your relay's
        	proxy_http_version 1.1;
        	proxy_set_header Upgrade $http_upgrade;   # These two lines ensure that the
        	proxy_set_header Connection "Upgrade";    # a WebSocket is used
        	proxy_read_timeout 604800;                # Prevent idle disconnects
        	proxy_set_header X-Real-IP $remote_addr;  # Let WeeChat see the client's IP
        	limit_req zone=weechat burst=1 nodelay;   # Brute force prevention
	}
	
	location / {
		#test
		return 500;
	}
}
```

I found out I can't connect to my ssl.irc relay, and if I browse https://(my domain name)/weechat it shows "502 Bad Gateway".

I thought I need to point the proxy to a "irc" (with no ssl) relay, so I did, now connects are stuck at "connecting" state (no disconnection, just stuck connecting).

The last thing I did is point back to ssl.irc relay and change proxy_pass to "https://localhost....." and it worked, but that doesn't match what the manual says, is this the correct way to do it?

**Comment by AStove** [comment]
Do I understand  you correctly in that you want to offload the ssl in the following manner?:
User ==https==> Nginx ==http==>

If so, you need to configure weechat to not use SSL, this is not like  you described.

**Comment by axzxc1236** [comment]
```
Listening on:
  port 35999, relay: ssl.weechat, IPv4+6, started on: 日, 24  5月 2020 21:06:53
  port 9856, relay: irc, IPv4+6, started on: 日, 24  5月 2020 21:06:53
```

I tried pointing Nginx to http://localhost:9856/weechat, result in connections being stuck at "connecting" state.

**Comment by AStove** [comment]
What does the core buffer of weechat say?

**Comment by axzxc1236** [comment]
```
relay: new client on port 9856: 2/irc/127.0.0.1
relay: websocket client 2/irc/127.0.0.1(My home ip address) has real IP address "My home ip address"
(The line below shows immediately when I close the tab that's stuck at connecting)
relay: disconnected from client 2/irc/127.0.0.1(My home IP address)
```

Here is the setting value

`relay.network.websocket_allowed_origins  string  ""`

Am I supposed to change it to something?

**Comment by AStove** [comment]
That allow origins setting is good.

It looks like you are opening a http connection and then do nothing. Either because the client gets no response or because the client does nothing. Do you self host or do you use glowing-bear.org? Can you go to the network tab of the development console of your browser and see what messages are sent over the websocket?

**Comment by axzxc1236** [comment]
I disabled 2FA, doesn't change anything.

I opened network tab in both Firefox and Chrome, there are precisely only two messages

```
(1) init compression=zlib,password=(My Weechat password)
(2) info version
```

No 3rd message

Headers
![chrome_2020-05-24_23-17-51](https://user-images.githubusercontent.com/3145859/82757856-9b95a980-9e15-11ea-8991-9f8623fa7430.png) 
Messages (The exact same messages shows in Chrome)
![firefox_2020-05-24_23-19-50](https://user-images.githubusercontent.com/3145859/82757883-c97aee00-9e15-11ea-91ab-c883aaf75177.png)

**Comment by AStove** [comment]
I don't know. Everything looks fine from the client side. But weechat must not be getting that init message, it would either say conneccted or authentication failed.

**Comment by oakkitten** [comment]
>     Listening on:
>       port 35999, relay: ssl.weechat,

does this still say `ssl.weechat`? it should be simply `weechat`

**Comment by AStove** [comment]
Right, you made an irc relay not a weechat relay.
Do
`
/relay del irc
/relay add weechat 9856
`

**Comment by axzxc1236** [comment]
That is it...... I set the wrong type of relay

Thank you!

**Comment by lorenzhs** [comment]
For posterity: if you need help with configuration, ask in #glowing-bear on freenode instead of opening an issue. Issues are for bugs, feature requests, and other things that have to do with the software. If you need help with the software, join our IRC channel. Issues are not the right medium to provide tech support.
