### ISSUE TITLE
Issue with SSL

### ISSUE THREAD

**Issue by tobifanibi** [glowing-bear/glowing-bear#1139]
I was having issue with ssl, turns out it was because I was using a bare ip address
Having the android app really helped because it will say "this certificate is only valid for this ip or domain." 

So from their you can see that glowing-bear should connect to the domain and not the ip address that domain points to.Theirs no way to use a self signed certificate it seems.  As glowing-bear requires that the certificate be valid

**Comment by AStove** [comment]
You can navigate to https://yourdomain.org:12345, accept the security warning. The page won't load because weechat doesn't present a page. But then the websocket will actually connect and glowing bear will work for a while. (A week.) Similar if you navigate to the bare ip address and accept the certificate, it will work for a while 

The current Glowing Bear does not give the error you say. It should say "A secure connection with the WeeChat relay could not be initiated. This is most likely because your browser does not trust your relay's certificate. Please read the encryption instructions below!"

There is no current android app, just the web app.

Now that you figured it out, what is your issue?

**Comment by tobifanibi** [comment]
direct ip=ip of server i.e https://1.1.1.1 
domain=https://something.mydomain.com 
glowing bear address: how glowing bear is accessed
relay address: the ip or domain used to connect to the relay


I tried a lot of things before getting something that works. I am also behind a vpn

**Scenario 1**
glowing bear address:direct ip of server with weechat installed, along with glowing bear
relay address:direct ip of server
certificate:certbot certonly --standalone -d something.mydomain.com 

Other commands:
/set relay.network.password y0ur_StRonG-pa$sw0rd:of*choice
/relay sslcertkey
/relay add ssl.weechat 9001


**result:**
![Annotation 2020-06-11 134802](https://user-images.githubusercontent.com/58971180/84427307-567dbf80-abea-11ea-9b94-b5ac6022b2f9.png)

![image](https://user-images.githubusercontent.com/58971180/84427671-e3287d80-abea-11ea-890d-c4b6d715e300.png)


**Scenario 2**
glowing bear address:direct ip of server with weechat installed
relay address:direct ip of server
certificate: self signed set to ip address:https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-WeeChat

Other commands:
certbot delete:At first the android app says the certificate is still tied to the domain. So I deleted the certbot certificate.
/relay sslcertkey


**result:**
![Screenshot_20200611-140848](https://user-images.githubusercontent.com/58971180/84429410-b5910380-abed-11ea-975a-ccd2950dd971.jpg)
So now the android app works

However glowing-bear doesn't display an option like that. 
So the error message for glowing bear is the same as in scenario 1.

Scenario 3
glowing bear address::direct ip of server with weechat installed
relay:domain address
certificate:certbot certonly --standalone -d something.mydomain.com 

Other commands:
/relay sslcertkey


conclusion:
the relay address must be set to the domain name, and not a direct ip address.
glowing-bear address can be anything

**Comment by AStove** [comment]
There is no issue here. That is how certificates work. If you wanted to make a self signed certificate for a bare ip address that is possible but you didn't. (And it would be very rare to do that, and impossible for letsencrypt).

If you make a certificate for a domain. You cannot then visit the bare ip and expect the certificate to be trusted.

As Glowing Bear is a web app, it must use the browser's capabilities, and no browser has the capability of asking you to trust an untrusted certificate for a websocket.

As I said a workaround would be to visit `https://<direct ip of server with weechat installed>:9001`, accept the untrusted certificate and then go back to glowing bear and connect. But you'd have to repeat this after a week or so, or upon restart and this is unsecure behaviour.

**Comment by tobifanibi** [comment]
I was just a little confused about what the issue was as went through the instructions multiple times
I thought maybe I had made the certificate wrong
