### ISSUE TITLE
Add day separators

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#114]
It would be nice to have some kind of a date display when days change

**Comment by theo01** [comment]
Any updates on this? I would love to have this day separator.

**Comment by lorenzhs** [comment]
Nope, no updates. Feel free to work on it, or use @torhve's `/trigger` approach.

**Comment by pmelanson** [comment]
Working on this issue. So far, `/trigger addreplace gb-print-day-change signal day_changed "" "" "/allchan /eval /print Day changed to ${date:%a, %d %b %Y}` prints any day change in all channels, eg `Day changed to Sun, 15 Nov 2015`.

Now if I `/quiet` send this command every time glowing-bear connects to a relay, it should work. Only caveat is that on stable debian atm (jessie) the functionality for `eval`ing dates hasn't been added so the string will just be `Day changed to ` and nothing else. However, for Ubuntu and Debian stretch this functionality has been added.

So yeah. Solution is to send this one-liner command to weechat on connecting. Any objections? There might be an objection to sending a command to the weechat relay, but it shouldn't conflict with any triggers the user has.

**Comment by lorenzhs** [comment]
Prototype implementation of adding the date change messages dynamically in glowing bear: https://github.com/glowing-bear/glowing-bear/compare/date-change

**Comment by lorenzhs** [comment]
Closed in #678 and related
