### ISSUE TITLE
Stop playing embedded media when the embed is minimized

### ISSUE THREAD

**Issue by dowodenum** [glowing-bear/glowing-bear#1153]
Hi, thought this would be a nice suggestion. Sometimes I'm in a chat with a lot of linked youtube music and I lose track of which track is playing, by closing the embed without first stopping the video. It's easy enough to just refresh and reload, but I figured I'd put this out there as a potential feature. Maybe there could be an option to disable it in the settings, but on by default makes sense to me.

Thank you for your development efforts, I love what you've put together!

**Comment by AStove** [comment]
duplicate of #975
fix suggested in #1151

**Comment by dowodenum** [comment]
My bad, didn't search hard enough.
