### ISSUE TITLE
Proxy embedded previews 

### ISSUE THREAD

**Issue by bendem** [glowing-bear/glowing-bear#1156]
It would be nice to be able to proxy embedded previewable content. That would hide the client IP as well as allow seeing that content from restricted networks.

**Comment by lorenzhs** [comment]
It's a good idea but unfortunately not possible: we don't run a server that could do the proxying. All of Glowing Bear is executed in your browser, and the whole thing is hosted by GitHub pages (or any web server that serves static files if you host yourself). It's fundamentally incompatible with the architecture, sorry. (Also, proxying video content would be quite expensive and a questionable use of bandwidth)

**Comment by bendem** [comment]
Makes sense, thanks for the answer.
