### ISSUE TITLE
Critical bug: authentication method for weechat 2.9 does not work in http context

### ISSUE THREAD

**Issue by JeremyMahieu** [glowing-bear/glowing-bear#1157]
`crypto.subtle` or `window.crypto.subtle` is undefined in non secure contexts.

This is used for calculating the hash to log in to the new version of weechat with encrypted authentication.

Suggest either rolling back or disabling http. Don't really see a way around except with using an extra crypto library.

![image](https://user-images.githubusercontent.com/23409814/89577303-c9916400-d830-11ea-8cfa-6f1449d4a041.png)

**Comment by AStove** [comment]
Maybe have an alert that shows when trying to connect to >=2.9 and crypto.subtle is undefined?

**Comment by lorenzhs** [comment]
Well that's annoying. I don't know whether we should just say "GB doesn't work when served over http any more". There aren't a lot of valid use cases that require the http version (except for connecting to a different host on the same local network which can't use TLS). But maybe it would be better to fall back to the old insecure authentication when the site is used over http? But then again, showing big nasty warnings doesn't actually help (https://twitter.com/PowerDNS_Bert/status/1171352665164529665). Maybe disabling it is actually the way to go.

**Comment by AStove** [comment]
The problem I have with falling back is, pre weechat 2.9 we don't even check if weechat accepts plaintext, because it always did. The result is regardless of weechat version: "Oh I see I'm in http, let's send the password in plaintext." So because you're in an insecure context, you end up being double insecure.

What would be reasonable imo is to fall back only when the compatibilty checkbox is on.

**Comment by lorenzhs** [comment]
Yes, it's clearly a bad situation. The question is whether we want to support the very limited use case for that (-> add fallback, but without a compatibility checkbox because it's pointless) or not (-> kill http). I don't see the point of an in-between solution.

**Comment by JeremyMahieu** [comment]
Visit glowing bear on http, and uncheck encryption.

**Comment by Tony763** [comment]
Tried:
![image](https://user-images.githubusercontent.com/5598750/117936430-214f8500-b305-11eb-9573-118cbc65dd1c.png)
and
![image](https://user-images.githubusercontent.com/5598750/117936542-4512cb00-b305-11eb-8309-1d41f4c20c30.png)

Both result in:
![image](https://user-images.githubusercontent.com/5598750/117936470-2ca2b080-b305-11eb-89fd-fe58b057d67c.png)

**Comment by lorenzhs** [comment]
> Visit glowing bear on http, and uncheck encryption.

The whole point of this issue is that this doesn't work any more? The new authentication flow doesn't work on non-secure origins. We've hit the 0.01% of legitimate use cases of this on non-secure origins.

**Comment by Tony763** [comment]
Yes, I am pointing glowing bear only to http. Unchecked encryption does not help. I also tried it without password and empty password enabled but without success.

**Comment by JeremyMahieu** [comment]
Yes I'm sorry, it doesn't work. I deed that is the whole point of this
issue.

**Comment by lorenzhs** [comment]
A workaround is to serve Glowing Bear locally - the crypto API is enabled if you serve from `localhost`. Cloning the repo and running `npm start` should do the trick. You can then access GB at http://localhost:8080/.

**Comment by Tony763** [comment]
Yes, this works. Not so convenient, but better than nothing. Thank you
