### ISSUE TITLE
Feature: use twemoji for emoji display

### ISSUE THREAD

**Issue by Aerdan** [glowing-bear/glowing-bear#1163]
On some platforms, the OS-provided emoji are entirely illegible for certain glyphs. It would be appreciated if Glowing Bear could use twemoji instead of deferring to the OS mechanism.

**Comment by Techman** [comment]
Why not just change your operating system's emoji font?

**Comment by JeremyMahieu** [comment]
A similar thing was removed in 724b2c6e939aca6b48f40f4d82d82e9ef682d2ee

**Comment by lorenzhs** [comment]
Yup, we removed support for non-native emoji rendering in #1127. Since any modern platform that I am aware of provides support for emoji fonts nowadays, we saw no further need for it. In most cases, bad platform emoji rendering is a configuration issue.

**Comment by Aerdan** [comment]
> Why not just change your operating system's emoji font?

I use Glowing Bear on four separate devices, three fairly regularly, across three operating systems, so this is really not a viable solution.

**Comment by lorenzhs** [comment]
But iOS has excellent emoji support? I really don't understand your issue

**Comment by Aerdan** [comment]
I thought I stated my issue quite clearly in my original feature request: certain emoji are illegible in the OS-provided emoji font. If it helps, I am legally blind and twemoji is more accessible than Apple's colour emoji font.

Though I learned this after I'd filed the issue, macOS may support other emoji fonts, but it currently is not possible to use colour emoji via the SVG-in-OTF emoji font outside of Firefox; this is not an *obstacle* for me, but it may be for other users.

**Comment by lorenzhs** [comment]
Right. We can't use a font that only works as intended in Firefox because lots of people use other browsers. But you should be able to use the twemoji font by adding some custom CSS in the settings (there's a field to enter custom style definitions). Define a new `@font-face` and set the favourite font setting to that new font, like here: https://stackoverflow.com/questions/39875299/how-to-use-an-emoji-font-on-a-website

**Comment by Aerdan** [comment]
That would be a clever solution, if not for the fact that there is no browser on iOS which supports SVG in OTF (as Firefox on iOS is, like every other browser on the platform, constrained to be a Safari wrapper).

**Comment by lorenzhs** [comment]
Ah, I thought you proposed to use the twemoji font in Glowing Bear. But your actual request is for an emoji to SVG translation inside Glowing Bear? If so, have you tried whether the non-native emoji rendering that we used to have works for you? A version that still has it is, for example, available at https://pull.glowing-bear.org/1126/

**Comment by Aerdan** [comment]
Yes, that works, but only if I don't, say, install an emoji font to replace Apple's.
