### ISSUE TITLE
latest.glowing-bear.org gives an HTTP 404

### ISSUE THREAD

**Issue by Minnozz** [glowing-bear/glowing-bear#1167]
Probably related to merging #1166?

**Comment by cormier** [comment]
You are right, this is surely related to merging #1166. We will fix this as soon as possible. Thanks !

**Comment by lorenzhs** [comment]
Thanks, I fixed the deploy script. However, new pull requests (that branch from a point after the merge of #1166) won't work until a better deploy script is running.
