### ISSUE TITLE
TOTP not working in post 0.9.0

### ISSUE THREAD

**Issue by norbusan** [glowing-bear/glowing-bear#1175]
Hi all,

thanks for glowing bear, it is very much appreciated.

I am trying to get TOTP working with current version in master, but selecting the checkbox for TOTP does not activate the TOTP input field. With 0.9.0 this did work, though.

Thanks

Norbert

**Comment by norbusan** [comment]
Bisection gave 
b0675b1ad395023eeba9135d0c1d85102157c90e convert app to be built using webpack 
as the broken commit.

**Comment by JeremyMahieu** [comment]
TOTP is no longer an input field. It's a prompt that triggers when weechat asks for it. Introduced in #1119

**Comment by norbusan** [comment]
Thanks for your answer, indeed. But still, it does not work.

I have a weechat 3.0 running with encrypted relay, and I used https://www.glowing-bear.org/ with TOTP selected, and can easily connect to my server.

OTOH, when I use https://latest.glowing-bear.org/ I never get it to work. I usually get the error:

> Weechat version error Weechat connected but did not respond to a handshake. This could mean weechat < version 2.9. Verify > your weechat is 2.8 or older and check "Compatibility with Weechat 2.8 and older" or consider updating weechat.

and when I select the 2.8 compatibility with TOTP it give an error that password/token is invalid.

This is with Debian/stable, weechat installed from weekchat packages, version 3.0.

Thanks for any suggestions

Norbert

**Comment by JeremyMahieu** [comment]
What kind of network delay is there? Glowing bear determines it's an old
version if handshake message doesn't come within a certain time. Are you
using TLS or not?

**Comment by norbusan** [comment]
Hi Jeremy,
that is a rental server of Hetzner in Finland, bare metal. So the connection speed shouldn't be a problem. Yes, TLS is activated and the only way to access the relay server. I have root access to the server, so if you need some debug logs from weechat or anything else, please let me know.

**Comment by JeremyMahieu** [comment]
Can you manage to connect with V0.9?

You may want to increase `var WAIT_TIME_OLD_WEECHAT = 200; //ms` https://github.com/glowing-bear/glowing-bear/blob/88a95c0f76377e60d5686e33929cf9058dad0efb/src/js/connection.js#L54

If the response takes longer than 200ms GB assumes weechat is too old to send the handshake.

**Comment by norbusan** [comment]
Hi Jeremy,

yes as I wrote, with https://www.glowing-bear.org/ which is 0.9 there is no problem at all.

With that in mind, would it help you to thest the increase of the handshake timeout?

**Comment by JeremyMahieu** [comment]
I think that would solve it. Several roundtrip at high latency can easily exceed 200ms. You can remove this whole block of code and always assume weechat is >2.9. 

Now that newer versions of weechat are available, the checkbox should change so it assumes a newer version by default, regardless of delay.

**Comment by norbusan** [comment]
Ok, thanks, will try that out. I will put it onto my local machine to simulate remote access (putting glowing-bear onto the weechat running server is on my list).

BTW, is it possible to force a certain server, say *only* localhost is allowed? This would be useful when putting glowing bear onto the same server where weechat is running, so only for my own use, but don't allow other people to use it.

**Comment by JeremyMahieu** [comment]
By not allowing it through the firewall.

**Comment by norbusan** [comment]
Hi Jeremy,
ok, I have changed the `WAIT_TIME_OLD_WEECHAT` to `500`, installed the `npm run build` created files onto my server, and now it works.

Thanks for the hint!

**Comment by JeremyMahieu** [comment]
Glad it works. I probably misunderstood your question about localhost. It's not possible but perhaps you should make a new issue for that one.

**Comment by norbusan** [comment]
Forget my question about localhost, it was anyway stupid ;-) And if I want to do it, I can force the server entry field to a fixed value myself in the javascript code, since I am deploying the stuff by myself (and need to change the timeout anyway).

Thanks, I am closing this issue.

**Comment by lorenzhs** [comment]
You can restrict who can connect to your weechat instance with `relay.network.allowed_ips` and `relay.network.websocket_allowed_origins`
