### ISSUE TITLE
Can't connect to relay on LAN with Chrome & Firefox - Safari works fine

### ISSUE THREAD

**Issue by hrvstr** [glowing-bear/glowing-bear#1176]
Hi, I am having trouble connecting to my relay on a local network after upgrading WeeChat to version 3.0. I can login with my password using Safari but all other browsers fail to login with the error ` Error: wrong password or token ` although the password is correct.

Any ideas?

- weechat 3.0
- http://latest.glowing-bear.org

---

### Chrome (87.0.4280.141)
WebUI: 
```
Error: wrong password or token
```

Console: 
```
Connecting to URL:  ws://dietpi:9001/weechat
angular.js:15697 Aborting connection (lock in use)
angular.js:15697 Notification permission status:  denied
```

WeeChat:
```
relay: new client on port 9001: 3/weechat/192.168.178.31 (waiting auth)
relay: authentication failed with client 1/weechat/192.168.178.31
```

---

### Safari (14.0.1)

Console:
```
[Debug] Connecting to URL:  – "ws://dietpi:9001/weechat" (main.js, line 2)
[Info] Notification permission status:  – "denied" (main.js, line 2)
[Log] Succesfully connected (main.js, line 2)
[Info] Connected to relay (main.js, line 2)
```

WeeChat:
```
relay: new client on port 9001: 1/weechat/192.168.178.31 (waiting auth)
relay: client 1/weechat/192.168.178.31 connected/authenticated
```

**Comment by lorenzhs** [comment]
That `Aborting connection (lock in use)` message says that a connection is already pending/opened, are you sure that's what happens the first time you connect in a new tab? Because to me it looks like a follow-up failure and the actual problem occurs before it

**Comment by hrvstr** [comment]
Hm, not sure if it was a fresh tab when I created the last log (might have tried multiple browsers at once). I just tried again with new Chrome tab:

```
Connecting to URL:  ws://dietpi:9001/weechat
angular.js:15697 Notification permission status:  denied
Disconnected from relay
```

**Comment by lorenzhs** [comment]
That's odd, maybe chrome doesn't allow the unsecured websocket? Does it work if you run weechat on the same host as your browser?

**Comment by hrvstr** [comment]
Yes, according to [this thread](https://stackoverflow.com/questions/50704614/websocket-connection-fails-on-chrome-without-ssl) that might be the case (I'm no expert though). What's weird is that I used an electron app (latest glowing bear in a wrapper) created with [nativefier](https://github.com/jiahaog/nativefier) with no problems until the upgrade to WeeChat 3.0.

At least it's still working in Safari.

I just installed WeeChat on my desktop and added a weechat relay. I can't connect from the same machine but connecting from my iPhone via latest.glowing-bear is working fine. Really weird...

**Comment by lorenzhs** [comment]
Oh right, it's the crypto API we use for the handshake mechanism. That isn't available in non-ssl contexts. I guess this makes it the same issue as #1157.

**Comment by hrvstr** [comment]
Okay, I took it as a final nudge to finally set up dyndns and get a cert from lets encrypt. It was easier than I thought - not sure if I feel more secure with open ports to my raspberry pi though. 😀

**Comment by lorenzhs** [comment]
(Also, we have electron support in the main repo, the build instructions are in the readme, you don't need to use nativefier)

**Comment by hrvstr** [comment]
Yes, I know but this never really worked for me. Either the build fails or I could not connect. Might try it again now that I have a cert.

**Comment by k3tan172** [comment]
I'm getting the same error as well. On Chrome `Error: wrong password or token`, on Safari it works fine. Electron app for Linux works fine. Could we please consider having this reverted back to work if possible? I use an all in one messaging browser called Ferdi and it utilises a chrome based browser. I can't connect to weechat using my glowing-bear instance using ferdi.

**Comment by lorenzhs** [comment]
We should just ship a replacement implementation of the crypto interface for these scenarios, but without loading it if it isn't required. I just don't have the time to do it, so someone else will have to to get this fixed.

Shouldn't just using the last release (`gh-pages` branch) instead of `master` work in the meantime?
