### ISSUE TITLE
Custom Emoticons

### ISSUE THREAD

**Issue by Shinmera** [glowing-bear/glowing-bear#1179]
Hi, I'm the maintainer of a relatively new chat protocol called [Lichat](https://shirakumo.github.io/lichat). We've been working on a [weechat script](https://github.com/shirakumo/weelichat) for that, and are almost done with it.

Now, one extension to the protocol allows the server to serve a set of emoticons -- small images associated with a name. Users that have a client that supports the extension can then include these emoticons in their messages with a simple `:emoticon:` syntax. Of course, since weechat is usually used through a terminal, there's no way for us to really support that feature in the weechat script, aside from just saving the images somewhere on disk, and giving auto-completion.

Since glowing bear would have the ability to render such emoticons however, we were wondering if there was an opportunity for collaboration here. Meaning some protocol that both glowing bear and our weechat script could use to allow the rendering of these emoticons in supported buffers. Hopefully the protocol would be general enough to allow other scripts to offer similar functionality through glowing bear.

Is there any interest in such a thing, and if so, do you already have some ideas on how to go about it?

**Comment by lorenzhs** [comment]
Hi @Shinmera,

that sounds like a nice project, but a bit out of scope for us. I think it would be best if you developed such functionality in a fork. To me, including it in GB seems like an undue maintenance burden, given that it's a bit too specialised to be easily testable. I hope you understand!

Something you might find useful: you can read WeeChat configuration from Glowing Bear with `fetchConfValue`, including (iirc) buffer settings, which might help with communicating the relevant data without reinventing the wheel.
