### ISSUE TITLE
JavaScript not enabled when started from a container image

### ISSUE THREAD

**Issue by carbolymer** [glowing-bear/glowing-bear#1180]
1. Use following `Dockerfile`:
```
FROM nginx:mainline-alpine

RUN apk add --no-cache --update git && rm -rf /var/cache/apk/*;
RUN rm -rf /usr/share/nginx/html/ && \
    mkdir -p /usr/share/webapps && \
    git clone https://github.com/glowing-bear/glowing-bear.git /usr/share/webapps/glowing-bear && \
    ln -s /usr/share/webapps/glowing-bear/src /usr/share/nginx/html;
CMD git -C /usr/share/webapps/glowing-bear pull && nginx -g "daemon off;"
```
2. Build the image: `podman build -t glowing-bear .`
3. Run the image `podman run --name glowing-bear -d -p 9898:80 glowing-bear`
4. Open in a browser (tested on FF 84 and fresh chromium 88) and go to 'http://localhost:9898/`

### Expected result
Javascript works

### Current result:
No console errors. Visible error:
"GlowingBear requires JavaScript support to function. Additionally, you must allow JS from cdnjs.cloudflare.com. Please check your script blocker or browser settings."
![Screenshot_2021-02-02_07-55-06](https://user-images.githubusercontent.com/228866/106563383-fac2c680-652b-11eb-88e1-d59c8019aa21.png)

**Comment by lorenzhs** [comment]
Javascript works, but your dockerfile is incorrect. You either need to allow network access to `cdnjs.cloudflare.com` as the error message states, or include those files in the image and change the path in index.html. This isn't a glowing bear issue, it's a configuration issue on your side.

**Comment by essembeh** [comment]
Hi @carbolymer 

I also struggled to run this project using docker. The documentation is not very detailed about this.
Also @lorenzhs I couldn't find the  extra steps you point in your message:
> You're also not running GB's recently added build step, so I suspect that this doesn't work at all right now.

Anyway, I ended up building my docker container directly based on the `gh-pages` branch, as all the packaging and extra steps have been done by the CI;)

```sh
$ git clone https://github.com/glowing-bear/glowing-bear --branch gh-pages
$ docker run -d --name glowing-bear -p 80:80 -v ./glowing-bear:/usr/share/nginx/html:ro nginx:latest
```
I didn't use the `docker` command but in a `docker-compose.yml`
```yaml
version: '3.3'
services:
  glowing-bear:
    image: nginx
    container_name: glowing-bear
    restart: unless-stopped
    volumes:
      - ./glowing-bear:/usr/share/nginx/html:ro
    ports:
      - "80:80"
```

I hope someone find this useful.

**Comment by lorenzhs** [comment]
`gh-pages` is an older state that doesn't have the build step yet. The build step is just `npm run build` which simply runs `webpack`. If you run that, the `master` branch should also work.
