### ISSUE TITLE
Enhancement: File Sharing via servers other than Imgur

### ISSUE THREAD

**Issue by Chisight** [glowing-bear/glowing-bear#1181]
Enhancement request: Please add the ability to paste or drag images (and other files) to servers other than Imgur.

@Quite recently commented on closed issue #925 that they would like to have the ability to use other back ends for file and image hosting like [Weechat-Android File-Sharing](https://github.com/ubergeek42/weechat-android/wiki/File-sharing) now supports and I concur.  Imgur support is great to have but it would be nice to have other options, including private ones that we host ourselves.

There are many ways to upload files, but being compatible to Weechat-Android's methods would mean that users only have to pick (or install) one back end service and can use it with both front ends.

atg on IRC suggested that I include a mock up of a possible UI, so here it is.  I welcome other design choices for the UI.

![Glowing-Bear-File-Mockup](https://user-images.githubusercontent.com/11790570/107845747-96adc700-6da3-11eb-817f-dea73e3713c4.png)

**Comment by lorenzhs** [comment]
Duplicate of #925, see also #1050. It has also been brought up occasionally on IRC (#glowing-bear) but nobody's volunteered to implement it.

**Comment by Chisight** [comment]
Yes, that was me on IRC asking if writing this up was a welcome request or not.  Good to know you read it there and chose not to respond.

**Comment by lorenzhs** [comment]
Haha lol this has been brought up like 5 times in the past, I’m not always fully up to date on what happens on our channel and people often leave before anyone gets the chance to reply so maybe be a bit less bitter about it?
