### ISSUE TITLE
Electron App on Mac: EROFS: read-only file system, open 'init.json'

### ISSUE THREAD

**Issue by bjoernhaeuser** [glowing-bear/glowing-bear#1183]
Hey there and thanks for all the work you have put into glowing bear!

I was able to built the electron app for mac, but whenever I am closing the app (or shutdown the computer), the following error message pops up:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: EROFS: read-only file system, open 'init.json'
at Object.openSync (fs.js:440:3)
at Object.func [as openSync] (electron/js2c/asar.js:140:31)
at Object.writeFileSync (fs.js:1265:35)
at BrowserWindow.<anonymous> (/Users/bjoernhaeuser/Applications/Glowing Bear.app/Contents/Resources/app/electron-main.js:1:919)
at BrowserWindow.emit (events.js:223:5)
```

I tried moving the `.app` to my users folder (you can see that in the error message), but the error stayed the same. I am not sure if I am doing something wrong or how that error message could/can be avoided.

Thank you for your help.

**Comment by lorenzhs** [comment]
I think you can just ignore the error for now (but we should fix it nonetheless). It's related to storing the window size so it opens at the same size next time. See also the comments in #1106.
