### ISSUE TITLE
Apache 2 and 0.9.0

### ISSUE THREAD

**Issue by Tony763** [glowing-bear/glowing-bear#1187]
Hello, I run glowing bear instance locally on my apache2 server with:
```
Alias "/irc" "/var/www/irc"
<Directory "/var/www/irc">
    Order allow,deny
    Allow from all
    # New directive needed in Apache 2.4.3: 
    Require all granted
</Directory>
```
With version 0.8.0 it works flawlessly.
I just tried version 0.9.0, but it not works for me. First change I found that `index` and other files were moved to `src` folder so I changed my directive to it. Now site runs, but I get error with `GlowingBear requires JavaScript support to function. Additionally, you must allow JS from cdnjs.cloudflare.com. Please check your script blocker or browser settings.`  JS is enabled and site is available. I have also tried PR #1186 but it have a same error and even break layout of page.

**Comment by lorenzhs** [comment]
This has nothing to do with Apache and everything with our documentation :) For 0.9.0, you need to run `npm install && npm run build` and then serve the `build/` folder with Apache.
