### ISSUE TITLE
Cloudflare origin certificate error on https://www.glowing-bear.org/

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [glowing-bear/glowing-bear#1188]
The origin web server does not have a valid SSL certificate.

**Comment by snookie** [comment]
Yep, same here:

The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. 

![YYxiyxKWtV](https://user-images.githubusercontent.com/373735/118595320-2603b580-b7ab-11eb-9816-3b7458b7696f.png)

**Comment by nextl00p** [comment]
Meanwhile there is: https://latest.glowing-bear.org/

**Comment by BKPepe** [comment]
@lorenzhs Can you take a look?

**Comment by lorenzhs** [comment]
Ugh looks like GitHub pages' certificate broke. I "fixed" it by not requiring a valid origin certificate any more.

**Comment by lorenzhs** [comment]
Yes looks like the origin certificate expired two days ago. What the hell?

**Comment by lorenzhs** [comment]
According to the repo settings, a new certificate is being provisioned. Looks like renewal doesn't work when strict verification is enabled? But I guess we could just remove cloudflare now that github pages natively supports encryption.

**Comment by lorenzhs** [comment]
19 hours later and the process that's supposed to take up to 15 minutes still isn't done :thinking: I've disabled proxying in Cloudflare to see if that will help.

**Comment by lorenzhs** [comment]
Yup that did the trick, a new certificate has been issued. It may take up to an hour for all CDN nodes to start serving it though, so you might get the expired certificate in the meantime
