### ISSUE TITLE
Cannot connect to relay after upgrading Letsencrypt to ECDSA

### ISSUE THREAD

**Issue by jmui** [glowing-bear/glowing-bear#1252]
When renewing my Letsencrypt certificate, I chose to upgrade it to ECDSA from RSA. Now I am getting the following error in Glowing Bear when trying to connect to my relay.
"Secure connection error A secure connection with the WeeChat relay could not be initiated. This is most likely because your browser does not trust your relay's certificate. Please read the encryption instructions below!"

Do I need to change the certificate back to RSA or is there a way to make the new certificate work? 

In WeeChat itself, I get this error when I try and fail to connect:

"relay: TLS handshake failed for client 1/ssl.weechat/IPaddress: error -87 No supported cipher suites have been found."

**Comment by flashcode** [comment]
This was an issue with the option `relay.network.ssl_priorities` in WeeChat, see: https://github.com/weechat/weechat/issues/1919#issuecomment-1524866434

Using the default value of option works fine and is recomended.
