### ISSUE TITLE
Desyncronized nicklist

### ISSUE THREAD

**Issue by JulienPalard** [glowing-bear/glowing-bear#1263]
I've not diagnosed the root cause (sooooory) but since a few time I notice some nicklist discrepency:

- Either it gets empty
- Either it gets way smaller than it should (in terms of number of participants)
- Either it's good (but I don't know, maybe it gets out of sync... ?)

Example:

![Capture d’écran du 2023-07-04 21-59-52](https://github.com/glowing-bear/glowing-bear/assets/239510/8179df81-0d69-4478-926b-eae971884ebd)

notice there's many people in the room but only the op displayed. I bet it is displayed because he's the last one changing or connecting.

Using Firefox 114, weechat-headless 3.8-1.

**Comment by lorenzhs** [comment]
Autoclose was a bit aggressive there :upside_down_face:

**Comment by jhoneycutt** [comment]
I can reproduce this by joining my bot to a channel I am in, kicking it, then rejoining it.

**Comment by jhoneycutt** [comment]
Created PR #1274 to fix this.

**Comment by lorenzhs** [comment]
Thank you so much! I think this will make quite a few people happy :) Merged!
