### ISSUE TITLE
anything with <>, <nicks> is getting parsed as html and doesnt show up

### ISSUE THREAD

**Issue by technonerd33** [glowing-bear/glowing-bear#1281]
% git log -n1
commit f39fe804b10b407f00467c8455772e9ce4ba95cf (HEAD -> master, origin/master, origin/HEAD)

weechat from console

```
19:28:08 +sd <nick1> hi
19:30:37 +sd <nick2> hello
19:35:27 technonerd <test>

```
glowing
```
19:28:08 	+sd   hi
19:30:37 	+sd   hello
19:35:27 	technonerd	
```

`
19:51:35 technonerd <marquee>run forest run</marquee>`

[Screencast_20240604_185251.webm](https://github.com/glowing-bear/glowing-bear/assets/14337797/22b8ea59-6741-4b0c-8472-be33d75e5435)

**Comment by meldra** [comment]
Can confirm

**Comment by iakat** [comment]
indeed, this is an XSS

**Comment by iakat** [comment]
latest.glowing-bear.org does not seem affected, but f39fe80 in an incognito firefox windows is.
