### ISSUE TITLE
Unable to Connect Glowing Bear to WeeChat via Localhost without Opening a Port

### ISSUE THREAD

**Issue by miztizm** [glowing-bear/glowing-bear#1283]
I am trying to connect Glowing Bear to WeeChat running in a Docker container using localhost without exposing the port. The connection works fine when using the server's IP address or domain, **but not when using localhost.** Below are the configurations and steps I have taken. I laso tried a 127.0.0.1 and a docker internal ip address, no luck 

```
OS: Debian
Docker Version: Docker version 20.10.7
WeeChat Docker Image: j33r/weechat:latest
Glowing Bear Docker Image: j33r/glowing-bear:latest
Nginx Version: 1.18.0
Firewall: UFW
```

**Nginx Configuration**

```
# Configuration for external domain
server {
    listen      ip:443 ssl;
    server_name subdomain.domain.com;
    error_log   /var/log/apache2/domains/subdomain.domain.com.error.log error;

    ssl_certificate     /home/user/conf/web/subdomain.domain.com/ssl/subdomain.domain.com.pem;
    ssl_certificate_key /home/user/conf/web/subdomain.domain.com/ssl/subdomain.domain.com.key;
    ssl_stapling        on;
    ssl_stapling_verify on;

    include /home/user/conf/web/subdomain.domain.com/nginx.hsts.conf*;

    location /glowing-bear {
        proxy_pass http://localhost:9003; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /\.(?!well-known\/|file) {
        deny all;
        return 404;
    }

    location / {
        proxy_pass https://ip:8443;

        location ~* ^.+\.(css|htm|html|js|json|xml|apng|avif|bmp|cur|gif|ico|jfif|jpg|jpeg|pjp|pjpeg|png|svg|tif|tiff|webp|aac|caf|flac|m4a|midi|mp3|ogg|opus|wav|3gp|av1|avi|m4v|mkv|mov|mpg|mpeg|mp4|mp4v|webm|otf|ttf|woff|woff2|doc|docx|odf|odp|ods|odt|pdf|ppt|pptx|rtf|txt|xls|xlsx|7z|bz2|gz|rar|tar|tgz|zip|apk|appx|bin|dmg|exe|img|iso|jar|msi)$ {
            try_files $uri @fallback;

            root /home/user/web/subdomain.domain.com/public_html;
            access_log /var/log/apache2/domains/subdomain.domain.com.log combined;
            access_log /var/log/apache2/domains/subdomain.domain.com.bytes bytes;

            expires max;
        }
    }

    location @fallback {
        proxy_pass https://ip:8443;
    }

    location /error/ {
        alias /home/user/web/subdomain.domain.com/document_errors/;
    }

    include /home/user/conf/web/subdomain.domain.com/nginx.ssl.conf_*;
}

# Configuration for localhost
server {
    listen      127.0.0.1:443 ssl;
    server_name localhost;

    ssl_certificate     /home/user/conf/web/subdomain.domain.com/ssl/subdomain.domain.com.pem;
    ssl_certificate_key /home/user/conf/web/subdomain.domain.com/ssl/subdomain.domain.com.key;
    ssl_stapling        on;
    ssl_stapling_verify on;

    location /weechat {
        proxy_pass http://localhost:9001;  # WeeChat relay port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /\.(?!well-known\/|file) {
        deny all;
        return 404;
    }
}

```

**Firewall Configuration:**
```
sudo ufw allow 9001/tcp
sudo ufw reload
```

![image](https://github.com/glowing-bear/glowing-bear/assets/617020/ba9b0ef3-1354-4694-b191-9117b86dcdaa)

**Testing Connection:**
```
Works: curl -v -k https://subdomain.domain.com/weechat
Does not work: curl -v -k https://localhost/weechat
```

**Expected Behavior:**
I expect to be able to connect to WeeChat using localhost and port 9001 from Glowing Bear without opening the port to the outside world.

**Actual Behavior:**
The connection only works when using the server's IP address or domain name, not when using localhost.

**Reproduction Steps:**

1. Run WeeChat in Docker
2. Configure Nginx to proxy requests to localhost.
3. Attempt to connect to WeeChat from Glowing Bear using localhost.

```
netstat -tuln | grep 9001 shows WeeChat listening on the correct port.
Firewall rules allow traffic on port 9001.
```

Please help me with guidance or a solution to connect Glowing Bear to WeeChat using localhost without exposing the port.

**Comment by miztizm** [comment]
Thank you for you answer! Given that WebSockets require a direct connection from the client (my browser) to the WeeChat server, and localhost on my browser resolves to the client machine itself, not the Docker container, how can I configure my setup so that Glowing Bear can connect to WeeChat inside the Docker container without having to expose the port on the host machine? Is there a way to make the browser recognize the Docker container as localhost or is there a specific Docker network configuration that could facilitate this direct connection? This function dosent exists in GlowingBear? 

thanks!

**Comment by miztizm** [comment]
As you can see my configuration Weechat and GlowingBear running on the same localhost. I tried with docker and without a docker. You mean , even if the GlowingBear is hosted on my server with weechat together, it sill connects to the localhost of my client machine? This is confusing, why GlowingBear can connect to my localhost (or a alias, 127.0.0.1 etc) on my server side.

**Comment by Kagee** [comment]
Why GlowingBear might be *hosted/stored* on the same machine as your weechat, when you *open/render* GB it is happening in your client/browser, and "localhost" is relative to the machine the browser is running on, not where the GB files are stored. No part of GB is executed on your server, only in your browser.

**Comment by miztizm** [comment]
@Kagee, thank you for the explanation. So the definitive answer is that "No, I can't use GlowingBear and Weechat on my server (with localhost) without opening a port."

**Comment by Kagee** [comment]
You will have to open *a* port. How you open/protect it is up to you. Be aware - if you use Docker to expose a port directly to the IP of a interface, Docker will probably bypass any firewall rules you apply - so i.e. limiting what browser clients that can connect to it using i.e. a allow list in a firewall may not work as expected.

Personally i use i.e. nginx with some form of auth to both serve the GB files *and* forward the Weechat websocket (both behind the same auth).

**Comment by lorenzhs** [comment]
your question is literally the first item in the FAQ https://github.com/glowing-bear/glowing-bear?tab=readme-ov-file#faq

**Comment by miztizm** [comment]
Okay, thank you. I thought maybe it had changed over time.
