### ISSUE TITLE
Swiping is unreliable on mobile devices

### ISSUE THREAD

**Issue by cormier** [glowing-bear/glowing-bear#184]
* The swiping zone is not large enough
* Sometimes the bufferlist or nicklist will not open / close and require two swipes.

**Comment by stenehall** [comment]
The swiping seems very stable on ios safari (home screen).

**Comment by lorenzhs** [comment]
True, it's gotten a lot better in general. @torhve's #560 made things a lot smoother, which was a huge improvement, and angular updates seem to have helped as well. I'm closing this.
