### ISSUE TITLE
WebSocket takes a long time to disconnect

### ISSUE THREAD

**Issue by tribut** [glowing-bear/glowing-bear#242]
When I'm connected over 3G, I often won't be disconnected using the 'X' button. Using the Chrome Debugger I have confirmed that the WebSocket is indeed in `readyState: 2` ([CLOSING](http://dev.w3.org/html5/websockets/#websocket)) and seems to remain like that for 10+ minutes.
Unfortunately, I don't have a solution. `ws.close()` does nothing as per the spec and there doesn't seem to be a way to force-close the connection. Closing the tab is of course possible but only if not running in app mode. With @lorenzhs's cordova branch this could have even greater impact on usability,  though I have not tried it myself.

**Comment by lorenzhs** [comment]
This seems to be a server-side issue, I didn't have this for a long time now and since I switched to proxying with nginx, I occasionally experience this issue again. Meh.

**Comment by torhve** [comment]
This is fixed.
