### ISSUE TITLE
Buffer list isn't compact enough (design wise)

### ISSUE THREAD

**Issue by AlexisEvo** [glowing-bear/glowing-bear#306]
Weechat in my terminal can fit about 55 buffers in a single list before running out of room. In the browser, it's limited to 17. This is a huge usability downside. I can't glance at my most commonly used channels in one go and see if someone has said anything. I have to scroll through the list.

Tangentially related: the core buffer with all networks aren't merged into a single buffer. So the first 14 buffers in Glowing Bear are all the networks I'm connected to. That's almost the *entire* buffer list as is. WeeChat merges these all into a single window, I don't see any reason why GB shouldn't as well.

**Comment by lorenzhs** [comment]
This issue is a part of in #592
