### ISSUE TITLE
Automatically focus new buffers requested by the user

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#318]
When we know that the user initiated opening of a new buffer (i.e. clicked a nick in the nicklist or a #channel link), or when they've typed "/query foo" or "/join #bar", we should automatically focus the new buffer.

The issue here is that we have to link the buffer-open event to the preceding event causing the buffer to open, and that means remembering some kind of state.

**Comment by vivien** [comment]
Is that deployed on latest.glowing-bear.org? It doesn't work for me yet, even after full page reload.

**Comment by lorenzhs** [comment]
Yes it is there. You can always check at https://latest.glowing-bear.org/version.txt - it will show the commit ID and message of the latest commit. Makes it easy to detect if my server is broken again (in this case, it is not)
