### ISSUE TITLE
Add support for themes

### ISSUE THREAD

**Issue by eepp** [glowing-bear/glowing-bear#32]
This is a **suggestion** to add support for various themes.

A theme would be a single CSS file (which may be the result of several LESS/SASS files, see #20) that controls pretty much all the look of this application:
- background color
- fonts
- connection page look
- preferences page look (if it exists)
- list of buffers look and position (left/right/top should all be easily possible)
- nick list look and position
- input bar style (and possibility of hiding the Send button)
- main buffer view look

I guess the CSS file location could be modified in the preferences to apply a theme instantly without downloading anything manually (saved in local storage).

@vivien won't like me for this, but having color schemes could be an option too, for instance if someone wants more pastelish colors instead of the default, oversaturated ones of terminals which are hurting my fragile eyes. In my defense, you can do exactly this with popular terminal emulators like GNOME terminal, urxvt, Terminator or PuTTY. Here's a screenshot:

![](http://1.bp.blogspot.com/-HGKZHXxqRp0/Uh0uGTStpWI/AAAAAAAAc84/rzG1OdGoZjc/s1600/settings.png)

See? Yes, if you set the red as green here, `grep` will output matches in green. People like me usually prefer schemes like [Solarized](http://ethanschoonover.com/solarized) because we're not using VT-100s like @vivien.

So to make this really easy for theme designers, very simple classes should be attached to strategic elements. The designer should also be aware of the "default state" of the application look, i.e. the reset values when no theme is applied. This is important because, for example if the core's CSS forces an element's `line-height` to `150%`, whereas the browser default is usually `normal`, the designer will need to manually force it back to `normal` to retrieve the default value (or use a reset sheet).

We don't want this to become like old MySpace CSS "skins".

The core CSS should only be used for things that a theme should never change, like rules to force the input bar at the bottom and have a buffer view that takes all the viewport's height.

**Comment by omeid** [comment]
@eepp Well, if Weechat sends blue, you can change the blue upstream, in weechat, just like you would do with curses. too easy.
