### ISSUE TITLE
Hotlist syncing not working?

### ISSUE THREAD

**Issue by Vincent-C** [glowing-bear/glowing-bear#337]
When "Sync hotlist with WeeChat" is enabled in the settings panel, if I clear my hotlist from my weechat session (/input hotlist_clear, or alt+h), that doesn't seem to sync over to glowing bear. "/input hotlist_clear" itself seems to have no effect directly in glowing bear as well. Is there any other way of marking all buffers as read (instead of clicking through each channel that has unread messages)?

**Comment by lorenzhs** [comment]
@Vincent-C in case you're still reading, we managed to implement this after all in #796. It's not in a release yet, but https://latest.glowing-bear.org has it.

**Comment by Vincent-C** [comment]
@lorenzhs Awesome, thanks! :)
