### ISSUE TITLE
Missing tab completion for commands

### ISSUE THREAD

**Issue by tfheen** [glowing-bear/glowing-bear#372]
Weechat should inform glowing-bear about what commands are available and those should then work, so you can do /que<tab> and it completes to /query.

**Comment by lorenzhs** [comment]
We've discussed this in the channel a while ago and it isn't technically feasible -- the WeeChat completion system is highly complex (e.g. `/set`) and we can't replicate it in Glowing Bear. We could do completion for a small subset of frequent commands (`/join /query /msg /close`) though

**Comment by cormier** [comment]
Yes, we could add support for a subset of commands, but I'm not really comfortable in duplicating WeeChat's features. How complicated would it be to implement some sort of "completition forwarding" in the WeeChat relay?

**Comment by lorenzhs** [comment]
Mentioning @torhve because he might know. As far as I'm aware, there is no such thing at the moment.

**Comment by cormier** [comment]
From what I know, there is no such thing. However, I would rather look into implementing some "completion forwarding" support in WeeChat than re-implementing command support in GB.

**Comment by AStove** [comment]
This is certainly possible. I tried with a simple test program:

- (1) init compression=off,password=hunter2\n
- (2) input 0x160b1a0 /con\n
- (3) hdata buffer:0x160b1a0/completion\n

It returns a bunch of stuff but "connect" is one of those. 
I mean it's made for this purpose, it even says if it's a base command or nick, etc.

Remove label of weechat limitation?

**Comment by lorenzhs** [comment]
Are you sure this existed in 2014? ;) What's the minimum version of WeeChat that supports this? Having full tab completion would certainly be nice

**Comment by AStove** [comment]
Looking up hdata has always been possible in the relay plugin. Since when this [completion hdata](https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#hdata_completion) object existed, I'm not sure, probably longer. So yes I think it existed in 2014. Either way I think we can lift the weechat limitation label and work towards a new way of tab completion without looking at the nicklist.

**Comment by io12** [comment]
This feature would be awesome. Glowing bear is the best experience I've had with an IRC client but lack of TAB completion can get annoying.

**Comment by AStove** [comment]
Turns out I was wong and it isn't possible afterall. And @flashcode suggested making a command for it.
