### ISSUE TITLE
Feature Request: Light mode

### ISSUE THREAD

**Issue by davewaxman** [glowing-bear/glowing-bear#423]
I would like to request a feature / function be adding to Glowing-Bear that allows the user to choose a "Light" theme. Probably just changing the BG to white and the text color to black would be enough; but I am surely not a UI expert.

**Comment by Noitidart** [comment]
The colors in the light theme of the names are so unreadable, they are so bright you cant see the names :( Anyway to change the colors of hte names? :(

**Comment by lorenzhs** [comment]
I'm not sure how it's implemented but I think we're using the colour codes that weechat sends us, so it's quite unflexible. @cormier, @torhve do you know more?

**Comment by torhve** [comment]
Colors are defined here: https://github.com/glowing-bear/glowing-bear/blob/master/css/themes/light.css
Just like in any normal terminal you can override what the colors are suppose to render as "locally"

**Comment by Noitidart** [comment]
Thank you all so much will try it out! :)
