### ISSUE TITLE
Crashes both Chrome and Safari on iOS on reconnnect

### ISSUE THREAD

**Issue by auduny** [glowing-bear/glowing-bear#452]
Starting glowing-bear works perfectly, but once you change active app for more than say 60 seconds and go back it goes back to the screen where it allows you to connect again. (probably because the websocket has timed out) 

When you then click connect, both chrome and iOS crashes

Seems like a runaway process or memory.

**Comment by lorenzhs** [comment]
I'm just going to close this because we don't have any influence over this and iOS 8 is now the norm

**Comment by t3chguy** [comment]
I had this happen on my iPad Air iOS8 today, doesn't crash chrome but freezes it entirely and the only way to do anything is to kill it from the Multitasking Menu, and then restore the chrome session when it gets reopened

**Comment by lorenzhs** [comment]
That seems to be a different issue though - I think I've had that one once too,not totally sure though. There's also the crash on connect bug in chrome.
