### ISSUE TITLE
Glowing bear home screen icon does not work on iOS8

### ISSUE THREAD

**Issue by TheFiZi** [glowing-bear/glowing-bear#467]
Safari on iOS 8.0.2. Using Glowing-bear with encryption enabled, password saved and auto-connect checked.

If I connect to my Glowing Bear install via Safari, enter in my Weechat relay information and connect everything works fine. At this time I enable remembering of password, automatically connecting and encryption.

While I have a working Glowing Bear connected in Safari I then add the page as a favorite. I can then close the tab, close Safari, reload Safari and click the Favorite for Glowing Bear and everything works as you'd expect. Glowing-bear loads, remembers all settings and automatically connects.

If I then 'Add to Homescreen' I then get a cool Glowing Bear icon on my home screen. If I click the Glowing Bear icon the server name has been forgotten, the port and password boxes are highlighted in yellow and appear to have had their settings remembered correctly. If I then enter the server hostname and click 'Connect' nothing happens. Weechat itself reports a new client connect but the UI never loads on iOS.

Re-entering all of the connection information after loading Glowing Bear from the home screen icon does not solve the problem.

When closing Glowing Bear from the Home Screen icon the following error is generated in Weechat:

      error -9 A TLS packet with unexpected length was received.

This TLS error may be a red herring because when you close Safari while Glowing Bear is loaded the following errors are generated in Weechat:

      relay: reading data on socket for client 1/ssl.weechat/::ffff:192.168.0.xxx: error -9 A TLS packet with unexpected length was received.
      relay: sending data to client 1/ssl.weechat/::ffff:192.168.0.xxx: error -10 The specified session has been invalidated for some reason.

**Comment by fuzzy76** [comment]
+1 here, fwiw. iOS 8.1.2 on an iPad Air.

**Comment by stenehall** [comment]
I've been debugging this a little and created a small test-case.

https://gist.github.com/stenehall/c4a1127ef11c1713f9b1#file-test-html

if you run this on Safari IOS 8.2 it will init and you can see the messages in weechat if you type /relay raw in weechat. If you instead add the page to your home screen and rerun the test it will not show any messages in weechat and it won't work. Removing line 5 (https://gist.github.com/stenehall/c4a1127ef11c1713f9b1#file-test-html-L5) will make it work.

In both cases https://gist.github.com/stenehall/c4a1127ef11c1713f9b1#file-test-html-L17 does work, it's just when you try to connect to weechat that it doesn't work. I'm not sure if this is a bug in Safari or Weechat but right now it seems more likely there's a problem on weechats side than Safaris given that the echo test works.

**Comment by zofrex** [comment]
I've also been debugging this a little.

I've found that relaying through nginx (i.e. I have a reverse proxy set up in nginx pointed at weechat, and connect through that instead of directly to weechat) resolves the issue.

**Comment by stenehall** [comment]
Here's an example nginx config that do work. https://gist.github.com/torhve/6470ec988bbfa4616f36

**Comment by rscullin** [comment]
iOS 8.3 seems to have fixed this issue -- I can now connect with GB launched from a web clip (home screen) using SSL.

**Comment by fuzzy76** [comment]
Not for me. :(

**Comment by lorenzhs** [comment]
It doesn't seem to be fully resolved to me either (iPad, iOS 8.3) -- sometimes it works, sometimes it breaks in mysterious ways. Maybe it got better (I never used iOS < 8.3), I don't know, but I can definitely say that the current state falls short of what it should be. I'll have to see how well I can debug things without a Mac.

**Comment by fuzzy76** [comment]
FWIW, I'm also seeing a similar issue trying to run Glowing Bear from http://fluidapp.com

**Comment by lorenzhs** [comment]
@fuzzy76 what javascript engine does Fluid use? Does it support websockets? I can't find any technical details on its web page

**Comment by fuzzy76** [comment]
Fluid is an embedded OS X webview, so it uses webkit internally. The author could not see any reason it shouldn't work. http://websocketstest.com/ returns green checkmarks on all tests when run inside Fluid.

**Comment by TheFiZi** [comment]
This issue also appears to have been resolved for me to with iOS 8.3. I'm also using SSL.

**Comment by lorenzhs** [comment]
Nice to hear that it works at least for some :) I just switched to using it in Safari, the homescreen icon version kept doing weird stuff for me... Still not sure what causes this or why it happens.

**Comment by breunigs** [comment]
the homescreen icon works for me on iOS 9+, when I could not get it to work on iOS 8 (any version).

**Comment by lorenzhs** [comment]
thanks for the report, I'll try again with iOS 9 and if more people report success I think we can close this

**Comment by lorenzhs** [comment]
Still crashing when trying to connect on iPad Air, iOS 9.0.2. Not every time but every other time.

**Comment by lorenzhs** [comment]
iOS 9.3 Public Beta 1 fixes this issue for me, while it was still broken on 9.2. Does anyone else still experience this or was I the last one left?

**Comment by lorenzhs** [comment]
I'm closing this since it seems to be fixed for everyone. Thanks all!
