### ISSUE TITLE
YouTube regex is too naïve

### ISSUE THREAD

**Issue by codl** [glowing-bear/glowing-bear#519]
Not all YouTube URLs are videos, but the YouTube plugin tries to display an embed for every link to YouTube.

Here's a small sample of URLs that should not be caught but are:
- https://www.youtube.com/youtube
- https://www.youtube.com/user/youtube
- https://www.youtube.com/channel/UCBR8-60-B28hp2BmDPdntcQ
- https://www.youtube.com/yt/about
- https://www.youtube.com/account
- https://www.youtube.com/feed/subscriptions

On legitimate `/watch` video links, if `v` is not the first parameter in the URL then the embed is not displayed correctly. Here's an example URL: https://www.youtube.com/watch?t=32m22s&v=lKkkXInTjNo

**Comment by MoonZ** [comment]
The domain name dots should be escaped:

`/(?:youtube.com|youtu.be)\/(?:v\/|embed\/|watch(?:\?v=|\/))?([a-zA-Z0-9_-]+)/i`
to
`/(?:youtube\.com|youtu\.be)\/(?:v\/|embed\/|watch(?:\?v=|\/))?([a-zA-Z0-9_-]+)/i`

[Link](https://github.com/glowing-bear/glowing-bear/blob/master/js/plugins.js#L209)

**Comment by lorenzhs** [comment]
That's indeed true... probably doesn't matter much in practice because otherwise it wouldn't match the URL filter but we should still fix it. Would you like to send a pull request?
