### ISSUE TITLE
in android chrome, there are no keyboard correction suggestions when entering a message

### ISSUE THREAD

**Issue by oakkitten** [glowing-bear/glowing-bear#520]
using latest chrome & google keyboard

**Comment by lorenzhs** [comment]
Can reproduce, doesn't work in Chrome but works in the app. Swiftkey works in both. I'll investigate

**Comment by lorenzhs** [comment]
This was introduced in a29905e02c19168cf0f0efdd26404fe2157f2def, I am waiting for a reply from @vivien before reverting it

**Comment by vivien** [comment]
Hi @lorenzhs! Do you think there will be any side effect by reverting it? Otherwise I don't mind

**Comment by lorenzhs** [comment]
To be honest I didn't know `autocomplete=off` was set because SwiftKey ignores it. It works great with autocompletion!
