### ISSUE TITLE
Problem with tweet embedding

### ISSUE THREAD

**Issue by TimelessBeing** [glowing-bear/glowing-bear#540]
Tweets are not properly embedded, and the hiding button looks weird (see screenshot below)

![capture d ecran 2015-01-22 a 15 36 51](https://cloud.githubusercontent.com/assets/2805912/5857903/7135ac98-a24f-11e4-92af-09c893cea84a.png)

Additional information:
- I'm using firefox; I tried with Chrome but the problem stays so it does not seem browser specific
- I'm using a mac right now, I haven't tried to reproduce it on another OS yet
- Chosing "Hide embedded content by default" in the parameters seems to solve the problem (but that's not a real solution)

**Comment by cormier** [comment]
Thanks @TimelessBeing. I've been able to reproduce this issue. I will try to fix this as soon as possible.

**Comment by lorenzhs** [comment]
I believe we need to call `plugin.showContent` to execute the tweet fetching mechanism

**Comment by lorenzhs** [comment]
Found the issue, #548 fixes this. @cormier, could you review please?
