### ISSUE TITLE
How to unisntall glowing bear firefox app?

### ISSUE THREAD

**Issue by introom** [glowing-bear/glowing-bear#552]
I am running ff 35.0.1, on OSX 10.10.2

After clicking installing the app, nothing happens though. But a second click will do alert that it has already been installed.

But I found it no where on my computer.

Does glowing bear really support FF 35.0.1 on OSX?
If not, how can I uninstall it?

TIA.

**Comment by introom** [comment]
OK. First time install FF app. Turns out a FF app is kinda a native osx app, and resides in /Applications.

**Comment by lorenzhs** [comment]
Sorry about that, we need to do a better job of documenting Firefox apps. See also #544
