### ISSUE TITLE
MathJax integration for LaTeX math rendering

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#556]
It would probably be a good idea to make this a setting (like twemoji), but imagine the possibilities! Awesome math rendering in your IRC client! I intend to implement this as a filter.

It's totally obvious that I work in academia, isn't it? ;)

EDIT: dropping http://docs.mathjax.org/en/latest/typeset.html#typeset-math as a starting point so I don't forget

**Comment by cormier** [comment]
It does seem like a use case that originated in academia, but I think it would be awesome!

**Comment by cormier** [comment]
Not knowing MathJax myself, i'm trying to figure out the context:
So, this is the project Github page:
* https://github.com/mathjax/MathJax

According to the docs [1]:
We first need to import the library:

```javascript
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

And then we can include inline mathematics like this:
```javascript
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
</script>
```

For this, I suppose that we would need a filter that look for `$$...$$` or `\\..\\` ?

References:
MathJax doc: http://docs.mathjax.org/en/latest/start.html

**Comment by lorenzhs** [comment]
Yup @cormier, I started implementing this in #557. Not using `$...$` as delimiter because of too many false positives, instead `$$...$$` and `\(...\)` as inline math delimiters and `\[...\]` for display math
