### ISSUE TITLE
latest.g-b does not align bar properly in lower resolutions

### ISSUE THREAD

**Issue by Evropi** [glowing-bear/glowing-bear#567]
Screenshot at 1280*800 px, taken from Firefox 37.0 beta:
![](https://imgrush.com/0mo_IpGBgLfB.png)

**Comment by lorenzhs** [comment]
thanks, fixed. The problem was that the `use-minification` branch did not merge cleanly.

**Comment by Evropi** [comment]
Turns out the git repo was unclean on the http://latest.glowing-bear.org website.
