### ISSUE TITLE
Lost notifications when using new hotlist clearing

### ISSUE THREAD

**Issue by torhve** [glowing-bear/glowing-bear#577]
Scenario:

1) /query lorenzh in gb
2) WeeChat switches automatically to the newly created buffer
3) GB doesn't switch buffer anymore for the user, so weechat will now have this buffer open
4) GB doesn't get notifications for the buffer because it's open in weechat

Proposed solutions:

Maybe force a /buffer core after we send a query? 
Or find an option in weechat that prevents auto-opening from occuring.
Or use /msg instead, but not sure about that.

**Comment by torhve** [comment]
It's relatively easy to add a /buffer core command in the event handler for handlebufferopened
But that would be kinda intrusive if you are trying to use the ncurses client at the same time as gb, because then user would lose messages in cli.

A new thought, how about changing
/set weechat.look.hotlist_add_conditions "${away} || ${buffer.num_displayed} == 0"
into
/set weechat.look.hotlist_add_conditions "${away}" which will cause WeeChat to add mesages n the current buffer to be added to hotlist and thus gb.

The problem with that solution is that it requires user to make changes to their conf, which we've sort of avoided so far.

**Comment by lorenzhs** [comment]
Have you talked to FlashCode if it would be possible to not switch to a buffer created from relay? Not sure if the WeeChat architecture permits this.

**Comment by torhve** [comment]
/query creates buffers, no options for it, I checked the C code.
But we could use /msg instead, maybe. Looks like that doesn't switch to the new buffer when the other part replies and a buffer gets created.

**Comment by lorenzhs** [comment]
:+1: sounds good

**Comment by torhve** [comment]
/Query -noswitch was recently introduced in weechat, we can use that.
https://github.com/weechat/weechat/commit/dea8b0bb09b5d301d9d61a6653d0f1683c8422c2

**Comment by lorenzhs** [comment]
:+1: very nice

**Comment by lorenzhs** [comment]
Closing this because we're using the `-noswitch` option on recent weechat versions
