### ISSUE TITLE
Crashes iOS Chrome on login

### ISSUE THREAD

**Issue by charlienewey** [glowing-bear/glowing-bear#597]
Replicated on both iPhone and iPad, using Chrome both times. Crash occurs when submitting details (i.e. when hitting submit after entering server, port, and password).

Both devices are running iOS 8.2

**Comment by rscullin** [comment]
Are you using encryption, and do you trust the cert if it's self-signed? I can only repro this when connecting to a secure host that Chrome doesn't trust (and that's a Chrome bug more so than a GB bug).

**Comment by charlienewey** [comment]
Bug is reproducible with and without encryption, same result on both devices. SSL certificate is trusted and in browser's default certificate store - encryption is not the issue.

Come to think of it, this may be a Chrome/WebKit issue rather than something wrong with Glowing-Bear. Will investigate further this weekend.

**Comment by rscullin** [comment]
Can you still reproduce this with iOS 8.3? It's fixed some other GB issues, and I'm curious if it fixed this issue.

**Comment by lorenzhs** [comment]
I can reproduce this issue with iOS 8.3. It doesn't happen 100% of the time, but it definitely happened to me a couple of times.

**Comment by lorenzhs** [comment]
Does anyone have any idea on what causes this, how to fix it, or a bug report in the Chrome bugtracker?

**Comment by lorenzhs** [comment]
Can’t reproduce on iOS 11.1 so I’ll close this
