### ISSUE TITLE
Changing Buffer on G-B changes the Buffer on WeeChat too

### ISSUE THREAD

**Issue by t3chguy** [glowing-bear/glowing-bear#602]
WeeChat v1.1.1
Running SSL Relay with Valid Cert
When changing relays on the hosted version of Glowing-Bear, with the WeeChat instance open in SSH, you can see the buffer being changed to the one that Glowing-Bear needs.
I asked @FlashCode about this and he said it shouldn't happen and its a bug within the client.

```
13:20 <t3chguy> Any way to stop a Relay Client changing the active buffer on WeeChat or is that a necessity?
13:37 <@FlashCode> t3chguy: I would say if a client does that, it's a bug in client
13:37 <t3chguy> its Glowing Bear, latest :/
13:37 <@FlashCode> and there's no way to prevent that, execpt by fixing the client
13:37 <t3chguy> it makes my WeeChat instance switch buffers
13:38 <t3chguy> that's a pain
13:38 <t3chguy> I'll report it
13:38 <@FlashCode> you should report them the problem
```

**Comment by torhve** [comment]
Latest version of gb doesn't do that if you have WeeChat newer than 1.0.
And also you can turn this behaviour off in old versions with turning off the "Mark messages as read option in gb".

**Comment by t3chguy** [comment]
What version is running at https://glowing-bear.github.io/glowing-bear/ then?

**Comment by lorenzhs** [comment]
the `gh-pages` branch that is tested and found stable. That said, https://latest.glowing-bear.org, which runs the `master` branch, is usually pretty stable (but might break without warning)
