### ISSUE TITLE
Firefox App Installation on Ubuntu Broken 

### ISSUE THREAD

**Issue by levlaz** [glowing-bear/glowing-bear#606]
I installed glowing bear as a Firefox App in Ubuntu. When I tried to launch the application I got a 404 error message saying that the location did not exist. 

Upon further investigation it appears that the `launch_path` argument in `webapp.json` is pointing to `/glowingbear/index.html` which does not really make sense to me. I changed the launch_path variable to be `http://glowing-bear.org` and I am now able to launch the app and use it normally. 

I have only used this on Ubuntu so I am not sure if this is the intended behavior on other systems, but if so then there should be a separate configuration file for Ubuntu (and I asssume other Linux systems). 

My working webapp.json file now looks like this: 

```json 
{"registryDir":"/home/levlaz/.mozilla/firefox/wf1fnvtn.default","app":{"manifest":{"name":"Glowing Bear","description":"WeeChat Web frontend","launch_path":"http://glowing-bear.org","icons":{"32":"/glowing-bear/assets/img/favicon.png","60":"/glowing-bear/assets/img/glowing_bear_60x60.png","90":"/glowing-bear/assets/img/glowing_bear_90x90.png","128":"/glowing-bear/assets/img/glowing_bear_128x128.png"},"installs_allowed_from":["*"],"developer":{"name":"The Glowing Bear Authors","url":"https://github.com/glowing-bear"},"permissions":{"audio-channel-normal":{"description":"Needed to play this app's audio content on the normal channel"},"audio-channel-content":{"description":"Needed to play this app's audio content on the content channel"},"desktop-notification":{}},"default_locale":"en","version":"0.4.8"},"origin":"http://www.glowing-bear.org","manifestURL":"http://www.glowing-bear.org/manifest.webapp","installOrigin":"http://www.glowing-bear.org","categories":[],"receipts":[],"installTime":1430427497401}}
```

Thanks so much for an awesome app! :)

**Comment by 20after4** [comment]
I don't even see a webapp.json. I'm also on ubuntu. Where do you see that file?

I'm having a different problem installing the app on ubuntu - it keeps telling me that reinstall is forbidden.

**Comment by levlaz** [comment]
Hey @20after4 All of the firefox apps are installed in your home directory. The reason why you cannot "reinstall" the app is because the file already exists. 

I am not sure if the name of the file is the same but on my machine it is located in ~/..glowingbear-2f382f7d2fd995866615df7aa3ea739b/webapp.json 

In order to launch the app you can run `~/.glowingbear-2f382f7d2fd995866615df7aa3ea739b/webapprt-stub`

The entire process seems a bit broken, it may have to do with how Firefox views these "apps".

**Comment by 20after4** [comment]
@levlaz: so my webapp.json works and it's got the default launch_path relative to my install_origin. What version of firefox are you using? I'm on the beta channel (v 38) and it seems to be working, although the firefox webapp stub is missing some features like ctrl+f find in page and the application menus are both translucent and non-functioning.

The chrome app works much better though it's got one annoyance: it insists on opening links from irc in chrome rather than my default browser (firefox) ...

**Comment by levlaz** [comment]
I noticed the same exact issue on OS X with the latest firefox. Please see the screenshot below. 
![screenshot 2015-05-13 10 25 23](https://cloud.githubusercontent.com/assets/7981032/7612726/93dbf498-f95a-11e4-83eb-86f57869671b.png)

Updating the webapp.json file seems to fix the issue just like it did in Ubuntu.

**Comment by pelmers** [comment]
I see the same issue as @levlaz. Where can I find the webapp.json file on disk?

**Comment by levlaz** [comment]
What OS are you running?

**Comment by pelmers** [comment]
OS X Yosemite

**Comment by levlaz** [comment]
@pelmers I cannot for the life of me find this file in OS X. :/ I submitted a patch which should resolve this issue going forward.

**Comment by etamme** [comment]
I am using ubuntu 14.04 and I installed the app from firefox 38 and have no issue launching it.

**Comment by lorenzhs** [comment]
This has nothing to do with your OS, folks. The problem is that firefox doesn't support relative paths and the URL is set to '/glowing-bear/index.html', which works for https://glowing-bear.github.io/glowing-bear but not for https://www.glowing-bear.org -- there's no way to fix one without breaking the other.

**Comment by lorenzhs** [comment]
wait actually this should work, the gh-pages branch has a symlink. Which instance of glowing bear are you guys using?

**Comment by lorenzhs** [comment]
Sorry guys, that symlink only existed locally. I pushed it, it should work now.

**Comment by lorenzhs** [comment]
GitHub pages handles symlinks strangely, I can't seem to get it to work. See https://github.com/Sidnicious/gh-pages-symlink-test/issues/7

**Comment by lorenzhs** [comment]
I contacted GitHub support about this, let's see what they say.

**Comment by lorenzhs** [comment]
The issue was that jekyll does not support recursive symlinks...
