### ISSUE TITLE
Feature Request: sticky buffers

### ISSUE THREAD

**Issue by vivien** [glowing-bear/glowing-bear#608]
Hi,

I idle on many chans, but I frequently talk only in a few of them. The "Only show buffers with unread messages" is nice to have a clean buffer list, but this is not quite handy to switch beetween frequently used buffers.

It'd be great to have a little pin icon on hover on a buffer name, in order to keep them in the list even if there's no unread message inside.

What do you guys think?

**Comment by lorenzhs** [comment]
I think it's a great idea. It sorta goes hand in hand with #604 - both require some changes to the information stored on the client and to the handling of the buffer list.

**Comment by lorenzhs** [comment]
This is actually a duplicate of #440 -- closing this one.

**Comment by blaskovic** [comment]
Is there any ETA for this? Or plans if it will be implemented or not?

**Comment by lorenzhs** [comment]
See #800
