### ISSUE TITLE
Reconnect sometimes results in duplicated line data

### ISSUE THREAD

**Issue by disassembler** [glowing-bear/glowing-bear#610]
On occassion, glowing bear shows duplicate data. Android weechat app and tmux session of weechat don't show this. Screenshot attached. This is for comments, status messages, join/parts, etc...
![screen shot 2015-05-13 at 11 29 17 am](https://cloud.githubusercontent.com/assets/651205/7617974/b27ebc4c-f963-11e4-8e9a-0b82ef62c086.png)

**Comment by t3chguy** [comment]
I've had this for regular messages too - logging out and back in solved it - but yeah +1

**Comment by lorenzhs** [comment]
Yes, this sometimes happens after a reconnect. It seems like Glowing Bear reconnects twice, but we haven't figured out yet how that is even possible...

**Comment by lorenzhs** [comment]
`daurnminator` suggested on IRC that this might be caused by registering the events on the same connection multiple times. We should look into that.

**Comment by lorenzhs** [comment]
'dancek' posted this on irc: http://i.imgur.com/rB1xlUj.png

**Comment by phime42** [comment]
Having this issue on a regular basis on iOS when leaving the GlowingBear Task open. Sometimes, messages are repeated 4 times.

**Comment by lorenzhs** [comment]
Yeah, this happens with bad connections. I'll try to find some time to fix it soon, the problem is that we need a lock on the connection object. Shouldn't be too hard actually, but I've got plenty on my plate at the moment unfortunately. I promise to fix it for the next release though :)
