### ISSUE TITLE
Minimal HTTP login?

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [glowing-bear/glowing-bear#611]
Would it be possible to have a version of Glowing Bear which used HTTP login (probably via some PHP code)? When the credentials were entered, it would add those as perhaps JavaScript variables for some autologin code on the browser.

For example: Entering Username/Password `localhost:1337`/`sup3rs3cr3t` in the HTTP login would cause glowing-bear to connect immediately to hostname "localhost", port 1337, with password "sup3rs3cr3t" immediate upon the page finishing loading.

This would make storing credentials in the browser more functional, especially for multiple Weechat servers.

**Comment by cormier** [comment]
I don't think I understand exactly the feature that you would wish to have.

I understand that you are currently have multiple WeeChat instances running, each with a different relay configuration, and that you would like to have an easy way, for example by using a syntax like `host:port/secret` to specify where Glowing Bear should connect. 

However, I don't see how it would make switching between different configurations easier. How would it make storing credentials more functional? What would this PHP code do?

**Comment by lorenzhs** [comment]
I think what @JamesTheAwesomeDude wants is login via HTTP POST so the browser remembers the credentials in its password store. But I think we can achieve this without a server side component, single page apps should be able to do that. We would probably need to encode host/port/encryption in a hidden field, although I'm not sure whether that would work with credential storage.

**Comment by torhve** [comment]
I saw this in a fork:
https://github.com/WeeNC/glowing-bear/commit/7cc574d43f324cea4ead19bb6ea9fa4ccaf75f90

**Comment by AppleDash** [comment]
If anyone is interested, I have added some documentation at the top of the README of my fork, which has been linked in the comment above mine.

**Comment by JamesTheAwesomeDude** [comment]
@lorenzhs HTTP POST is not quite what I am thinking. I am thinking of a plain [HTTP Login](http://en.wikipedia.org/wiki/Basic_access_authentication), the simplest way to send authentication.

@cormier My idea is to have the host/port separated by a `:` in the HTTP username field, and the password in the HTTP password field. **This way, the browser would recognize the host/port and password, and could save them appropriately.**

**Comment by t3chguy** [comment]
http://www.w3.org/TR/XMLHttpRequest/#author-request-headers
Authorization headers can be accessed via Javascript in most browsers - this is extremely easy to implement.

**Comment by JamesTheAwesomeDude** [comment]
Ooh, I really like @t3chguy's point!

Perhaps have some JavaScript which would check for HTTP login details, and if they existed, then use them to autoconnect.

**Comment by lorenzhs** [comment]
Well, basic auth is just about the most user-unfriendly method to authenticate users (at most one sentence of explanation possible). It also goes against each of our design principles (no server-side components, easy to use). You are, of course, welcome to implement this, but I doubt that we would merge it.

If you can find some kind of trick to make the browser consider the hostname and port input and the TLS toggle as username and password as password *without requiring the user to do this manually*, that would be quite nifty and I'll gladly consider such a PR.

**Comment by JamesTheAwesomeDude** [comment]
I do notice that some browsers do detect the port as username and the password as password, so perhaps simply merging the host and port fields would be enough to have browser credential storage working well. (As it currently stands, the browser tries to store `port`/`password`; merging the fields would cause it to store `host:port`/`password`, which is a slightly more sane system)

**Comment by lorenzhs** [comment]
yes, but it reduces usability. We can't expect users to know that ports are commonly separated from the hostname with a colon. Moreover, we support entering IPv6 addresses without enclosing `[` and `]` -- the syntax for connecting is `[12:34:56::1]:8000`, but if you enter `12:34:56::1` and `8000`, it will work.

**Comment by AppleDash** [comment]
@torhve If I submitted a PR, would there be a chance of getting it merged?

**Comment by lorenzhs** [comment]
Well providing information in the hash part of the URL sounds like a nice addition to me, as long as it doesn't break anyone's workflow (like a HTTP login dialog would). That would have a good change of getting merged.

**Comment by lorenzhs** [comment]
@JamesTheAwesomeDude you could use that to make multiple bookmarks, combined with autoconnect this might be a nice solution for your use case

**Comment by torhve** [comment]
Agree with @lorenzhs , I am in favor of storing this in a hash so you could craft links and send to users and bookmark for super convenience. Nice on phones too where input always is cumbersome.

If you want to extend it further @AppleDash, we could store every setting in the hash, for a full setup experience.

**Comment by lorenzhs** [comment]
Continuing the idea of setting settings via hash in #619  and closing this one
