### ISSUE TITLE
What exactly are these numbers next to the buffers?

### ISSUE THREAD

**Issue by AppleDash** [glowing-bear/glowing-bear#614]
![buffers](https://cloud.githubusercontent.com/assets/1939757/7787464/9981cda8-01db-11e5-8674-12b679e68438.jpeg)

See the numbers to the left of the buffers? What are these? These can't be the buffer number because not every buffer has them and there is a #0, which does not exist in WeeChat.

**Comment by lorenzhs** [comment]
They're the quick keys. You can jump to the buffer with number X next to it with Alt+X. Personally, I'm not too much of a fan of those. As you noticed, they're not very intuitive, which is something I always try to avoid. Do you have any suggestions how to improve that?

**Comment by AppleDash** [comment]
@lorenzhs Alright, that makes sense now. As for suggestions... Why not just display the buffer number and use those for the quick key numbers?

**Comment by lorenzhs** [comment]
because of merged buffers, we don't really handle those (see #488)

**Comment by AppleDash** [comment]
@lorenzhs I like the idea of just pressing the jump key combo for that number multiple times to switch between merged buffers.

**Comment by lorenzhs** [comment]
Yeah, I think I would prefer that as well. I'm closing this issue for now.
