### ISSUE TITLE
Broken characters with nick name colours 

### ISSUE THREAD

**Issue by bascht** [glowing-bear/glowing-bear#615]
Just noticed this issue when I started to use [wee-slack](https://github.com/rawdigits/wee-slack). Coloured nick names seem to work fine in Weechat itself:
![screenshot from 2015-05-26 15 50 24](https://cloud.githubusercontent.com/assets/51264/7813985/6924ca8a-03bf-11e5-9128-ec0feecb7bff.png)
but lead to broken Unicode in Glowing Bear:

![screenshot from 2015-05-26 15 50 51](https://cloud.githubusercontent.com/assets/51264/7813991/6c821de0-03bf-11e5-98c6-5ca7fc363bc4.png)
![screenshot from 2015-05-26 15 50 46](https://cloud.githubusercontent.com/assets/51264/7813997/727e9bec-03bf-11e5-86eb-41a388de5640.png)

Browser: Firefox, using Glowing Bear @ glowing-bear.org.

**Comment by lorenzhs** [comment]
looks like we need to pipe the nick through the colour parsing function as well? If anyone with more knowledge of weechat could comment?

**Comment by hormigas** [comment]
This is a wee-slack bug. They are appending the color to short_name

It can be seen here https://github.com/rawdigits/wee-slack/blob/master/wee_slack.py#L549

The colors show up as desired in the chat (such as in the image above), but the problem occurs in the server list. Short of adding in a special check just for dealing with their bug, this should probably be marked as closed.

**Comment by lorenzhs** [comment]
Thanks, @hormigas - I never used wee-slack, so I had no idea what they were doing. Closing this now.

**Comment by lorenzhs** [comment]
(I mean, it would probably not be hard to fix - if it's not invasive, I think we would consider a pull request to fix this. I just don't have a way to test)

**Comment by torhve** [comment]
I think the wee-slack guys were going to remove the "feature" as FlashCode told them it's disallowed to do it like that. Atleast that was my understanding/recollection.

**Comment by lorenzhs** [comment]
Ah, okay, that solves this as well.
