### ISSUE TITLE
Don't put invisible <> for copy&paste around non-chat prefixes such as join/quit messages

### ISSUE THREAD

**Issue by t3chguy** [glowing-bear/glowing-bear#616]
![image](https://cloud.githubusercontent.com/assets/2403652/7844760/a4dd2af4-04aa-11e5-9e81-4a2ffaf56f40.jpg)

As is obvious, the WeeChat join/part characters are customisable, in this case Glowing-Bear seems to treat them as nicks. Same goes for plugins which just /print to a buffer, with a blank nick.
The former should have no prefix+suffix;
The latter should have no nick whatsoever (so no prefix+suffix);

**Comment by lorenzhs** [comment]
@torhve looks like your fix didn't fix it...

**Comment by lorenzhs** [comment]
Wait I think I might have misunderstood. Is your issue that <> appears around the nicks? Because I can't reproduce that (they are there, but only for copy pasting, and hidden 1000px left off the screen for display). I'm using current chrome for iPad. Also works correctly in safari. You should try reloading, it might be using an old cached CSS file.

**Comment by t3chguy** [comment]
I didn't realise they're not meant to appear
But if they're only for copying, then they should NOT be around the Join/Quit markers (--> | >>>, <<< | <---)
and they should not be around nicks of 0 length
(caused by /print)

**Comment by lorenzhs** [comment]
well, true, but arguably having them around join/quit markers is preferable to not having anything which is why they were added in the first place ;) I don't actually know a lot about weechat but I think we should have enough information to distinguish the two cases. A fix would be most welcome!

**Comment by t3chguy** [comment]
@lorenzhs since its meant to be about Nick Prefix Suffix, then surely it shouldn't be around the Join/Quit markers, maybe instead around the nick that those markers are regarding, but definitely not around the markers as this makes them look like a nick on first sight

**Comment by lorenzhs** [comment]
@torhve how easy is it to recognize non-chat messages? is there an attribute we can use? (i.e., should I label this "easy" or "weechat limitation"? :D)

**Comment by Techman-** [comment]
I'd like to bump this issue, because it annoys me a little when copying and pasting logs.

For example, this was just in #glowing-bear:
```
12:00:00 AM	<─>	Tuesday (December 12)
12:48:43 AM	<lorelai>	[glowing-bear/glowing-bear]: Issue #940 <T​echman-> You could make it a setting. I'm not sure exactly what wording it should be, though. CC: @lorenzhs @torhve  https://github.com/glowing-bear/glowing-bear/issues/940
```
I don't believe there should be angle brackets around anything that isn't an IRC message. When someone joins the channel, the indication is clearly messed up:
```
11:23:37 PM	<-->>	because [alyptik] (wark.) (ayy@cpe-76-173-133-37.hawaii.res.rr.com) has joined #glowing-bear
```

**Comment by lorenzhs** [comment]
#990 should finally fix this
