### ISSUE TITLE
Pass settings via URL hash

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#619]
It would be nice to be able to pass settings via the url hash (e.g. `glowing-bear/#server=foo.bar!port=1337!ssl=true!font=sans!fontsize=42pt!noembed=true!mathjax=true`).

See also the discussion in #611

**Comment by AppleDash** [comment]
My fork currently does this, minimally. It base64-encodes the settings so that they cannot be immediately read via an observer looking over the user's shoulder or something like that.

**Comment by lorenzhs** [comment]
we should probably erase the hash after processing it

**Comment by evaryont** [comment]
@AppleDash do you think you could rebase off the latest master and open a PR? I'd like to see this included, as well.

**Comment by lorenzhs** [comment]
I cherry-picked https://github.com/WeeNC/glowing-bear/commit/7cc574d43f324cea4ead19bb6ea9fa4ccaf75f90 as #644
