### ISSUE TITLE
HTML parsed in chat

### ISSUE THREAD

**Issue by nathan0** [glowing-bear/glowing-bear#622]
Typing any HTML code plus an emoji will result in the HTML getting parsed.

![screenshot 2015-06-08 at 16 21 15](https://cloud.githubusercontent.com/assets/3042219/8038264/6ce109b4-0dfa-11e5-9e80-2835963afa08.png)

**Comment by lorenzhs** [comment]
Ouch! I've managed to reproduce this. I'm looking into it.

**Comment by lorenzhs** [comment]
Thanks @nathan0, I've tracked down the issue. It was a problem in our DOM filter, which didn't properly escape *input* into the filter. When the result of the filter was set as an element's `innerHTML`, the surrounding HTML was parsed as well. I fixed this by escaping the filter's input.
