### ISSUE TITLE
Favicon unread count stops working

### ISSUE THREAD

**Issue by johnkernke** [glowing-bear/glowing-bear#626]
After an unknown about of time, the favicon unread count stops showing when I get new messages. It is solved if I do a refresh, but that can get annoying to have to do every 30 minutes or so.

Using Chrome Version 43.0.2357.81 on Mac OS X 10.10 (I think it also happens on Windows 7 as well)

**Comment by lorenzhs** [comment]
This is a known issue. I have observed it quite a few times and never found a fix. I narrowed it down to the favico.js library that we use, as I can't manually change the favicon either once it stopped working. Maybe it's actually applying the badges to the apple-touch-icon thing? https://github.com/ejci/favico.js/issues/14

**Comment by Kubuxu** [comment]
I have the same issue on Firefox 44.0b2 (and previous versions), Windows 8.1.

So it is not the linked issue.

**Comment by MoonZ** [comment]
I didn't have the problem until I switched from http://www.glowing-bear.org/ to http://latest.glowing-bear.org

However, in contrary to the first post, it just doesn't display unread notifications at all.
I do have the "Display unread count in favicon" activated.

Chrome 54.0.2840.71 m

**Comment by lorenzhs** [comment]
The only favico-related change is that we updated it from version 0.3.5 to 0.3.10, so if that broke it for you, it's probably a favico (https://github.com/ejci/favico.js/) bug.

**Comment by lorenzhs** [comment]
Looks like it may be related to https://github.com/ejci/favico.js/pull/106. Can you try https://latest.glowing-bear.org/favico-update/ and report if that works?

**Comment by MoonZ** [comment]
I can confirm that with http://latest.glowing-bear.org/favico-update/ (not https), it does work.

**Comment by lorenzhs** [comment]
Awesome, thanks!
