### ISSUE TITLE
Search box stuck in place

### ISSUE THREAD

**Issue by madyoda** [glowing-bear/glowing-bear#630]
Is it possible to have the search box always visible? With 200+ buffers, it gets annoying scrolling up all the way to the top to use the search box.

**Comment by lorenzhs** [comment]
Hi @madyoda , you're absolutely right about that. However, there's already an issue about this: #393. I'm closing this on as a duplicate, please subscribe to the other one. We would also appreciate it if you were to implement this and send a pull request ;)

**Comment by madyoda** [comment]
@lorenzhs I'm not very good with JavaScript/HTML, but I'll have a go.

I apologise, didn't see the other issue!
