### ISSUE TITLE
Remove menu bar in Firefox desktop app

### ISSUE THREAD

**Issue by SimonSapin** [glowing-bear/glowing-bear#631]
When using the "Install Firefox App" button I get a window without most of the browser’s chrome, which is nice, but that still has a menu bar:

![screenshot from 2015-06-29 08-50-40](https://cloud.githubusercontent.com/assets/291359/8402480/1a48a39a-1e3c-11e5-9b28-b304e22995bb.png)

Can this bar be removed?

The closest I could find is https://developer.mozilla.org/en-US/Apps/Build/Manifest#chrome , but that’s not it.

**Comment by torhve** [comment]
We would like to see this aswell, but I don't know how to remove it. If you can figure it out that would be awesome! Maybe try asking in some Mozilla IRC-channels?

**Comment by SimonSapin** [comment]
I’m told this is something to change in Gecko, not in apps: https://bugzilla.mozilla.org/show_bug.cgi?id=769170

**Comment by lorenzhs** [comment]
Thanks for looking into this, @SimonSapin - let's hope that there will be a way to configure this.

**Comment by SimonSapin** [comment]
I’ve found a work-around:

```sh
cd ~/.glowingbear-*/*.default
mkdir chrome
echo '#main-menubar { display: none !important; }' > chrome/userChrome.css
