### ISSUE TITLE
Tab completion on mobile

### ISSUE THREAD

**Issue by SimonSapin** [glowing-bear/glowing-bear#632]
On a computer, I can hit the Tab key to have someone’s nickname completed automatically. It’s nice. But on Android, my virtual keyboard does not have a Tab key. Is there another way to do this?

**Comment by torhve** [comment]
You click the nick in the chat

**Comment by SimonSapin** [comment]
What if that person hasn’t spoken (or triggered another event) recently?

**Comment by torhve** [comment]
We don't have a button for that

**Comment by SimonSapin** [comment]
Would you consider a PR adding that button, next to the Option menu and Disconnect ones? Ideally it’d only be visible when no physical keyboard is available, but I don’t know a way to detect that. The `width` media query could be a heuristic for "mobile", but it’s not a great one.

**Comment by torhve** [comment]
My personal opinion is that such a button does not have enough merit to justify it being visible all the time, albeit only when physical keyboard is not present.

I think the more modern UI way to solve it would be displaying different suggested "tags" after user types start of a nick and then pauses for a short while, which then the user can click to get it filled out.

This is a much more complicated solution than a simple button, but a much nicer user experience that doesn't impede on the looks of the interface when it's not being actively used.

**Comment by abjugard** [comment]
I would like this as well.

**Comment by Berzerker** [comment]
Hijacking this a bit. A button isn't necessary, per se. However, the keyboard collapsing when clicking the username does make it very counter-intuitive to use. Having the keyboard not collapse would nearly remove my need for a "tab complete" button on the Android client.

**Comment by rkitover** [comment]
The way quasseldroid does this, is you can double-tap on the input field to nick complete, would you accept a PR adding such a feature?

**Comment by lorenzhs** [comment]
Well we have a button for that now (a few years, actually). Double-tapping the input field is completely undiscoverable, easy to trigger accidentally with no clear indication what happened, and generally sounds like a UX nightmare to me tbh
