### ISSUE TITLE
12-hour format

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [glowing-bear/glowing-bear#633]
There needs to be a way to display timestamps in a 12-hour format.

**Comment by lorenzhs** [comment]
It would be nice if we could mirror WeeChat's behaviour there. However, I don't have time to look into this in the foreseeable future unfortunately, so if you want to take this on yourself, that would be most welcome.

**Comment by lorenzhs** [comment]
Closing since nobody wanted to take it
