### ISSUE TITLE
Settings window not affected by fontsize setting

### ISSUE THREAD

**Issue by Phyks** [glowing-bear/glowing-bear#641]
Hi,

The setting window is not affected by the fontsize setting in preferences. Then, it overflows on small screen without any way to see the bottom of the window, other than dezooming in the browser.

Thanks

**Comment by lorenzhs** [comment]
On second thought, I'm not sure that it should be. In my mind the settings should only affect user content. If a Glowing Bear component doesn't fit onto the screen that's probably a bug. Am I right in assuming that you've zoomed in the window using the browser's zoom function? In that case it could also be a bug in your browser's zoom handling. @Phyks do you still experience this issue? If so, can you provide some more detail please?

**Comment by Phyks** [comment]
Yes, I was experiencing this issue. I think the content actually fits in the window, but the scrolling is terrible due to the presence of many input fields in the window.

**Comment by lorenzhs** [comment]
Right, but without more info on what you're actually doing (did you zoom the window as I was assuming?) I can't really help you. What platform are you on? (OS, Browser, Browser version)

**Comment by Phyks** [comment]
Sorry, my phone is dead in the meantime and I cannot take a screenshot for you.

It was a Fairphone running Android 4.2 and Firefox for Android up to date. No zooming done in the browser.

**Comment by lorenzhs** [comment]
I can scroll the settings dialog just fine on Firefox for Android (OnePlus One, which has a huge screen though, running Android 5.1.1). I'm still not quite sure what your issue is/was.

**Comment by lorenzhs** [comment]
Is the scrolling still giving you issues? If yes, can you please provide more detail?

**Comment by Phyks** [comment]
Sorry, no longer an issue, I forgot to close it.
