### ISSUE TITLE
Alt-A is a character in my language

### ISSUE THREAD

**Issue by Kubuxu** [glowing-bear/glowing-bear#642]
Alt-A combination creates `ą` character in my language's keyboard. Unfortunately glowing-bear overrides it with its own key bind which is not best of the options.

Solution would be to allow rebinding shortcuts to different keys.

**Comment by torhve** [comment]
Alt-a or AltGr-a ?
Because we fixed an issue with this in the development version already, not separating properly between those two.

**Comment by Kubuxu** [comment]
AltGr-a so making it only Alt-a would also solve the issue.

**Comment by torhve** [comment]
Then it's already solved in development version.

**Comment by Kubuxu** [comment]
Thanks for your help and awesome work.
