### ISSUE TITLE
Buffers list items are too high

### ISSUE THREAD

**Issue by Kubuxu** [glowing-bear/glowing-bear#646]
With recent push to stable the buffers names take much more space, which is just wasted and forces much more scrolling.

It can be changed by changing padding from `10px 15px` to `5px 15px` in `.nav-pills li a`.
Also font and padding is not affected by settings' font size.

![5px](https://cloud.githubusercontent.com/assets/2259282/10042541/0e82c0ce-61ec-11e5-94d2-098bfc510b4d.PNG)![10px](https://cloud.githubusercontent.com/assets/2259282/10042542/0fe444f6-61ec-11e5-89ad-9c2b5f3d6444.PNG)

**Comment by lorenzhs** [comment]
We've had this discussion numerous times, and I'm pretty sure this issue has been filed before as well. It boils down to a usability thing, and larger navigation items on large screens are better in the majority of cases for the majority of users. On smaller screens, the items are smaller. Maybe we are only checking width but not height? 

In any case, this is something for our planned "Custom CSS" feature.

**Comment by Kubuxu** [comment]
Padding is same for both width settings and yes css checks only widths:
https://github.com/glowing-bear/glowing-bear/blob/master/css/glowingbear.css#L721

**Comment by lorenzhs** [comment]
Not true. It's 5px 10px for narrow non mobile and 10px 15px otherwise. On mobile, smaller items are too small to be tappable (see also Google and apple design guidelines)

**Comment by gdude2002** [comment]
Why not make it configurable, then? If it's such an issue for some people, surely that wouldn't be out of the question for those of us that don't like the wasted space?

**Comment by lorenzhs** [comment]
Adding more and more options is not something we want to do lightly. There are also various preferences as to *how much* smaller the items should be, and it's impossible to please everyone. Thus I think that custom CSS (with documented examples in the wiki) is the best way to go. It really shouldn't be hard to implement, but I just don't have the time at the moment.

**Comment by gdude2002** [comment]
Custom CSS is good, but if having lots of options is an issue then maybe having settings categories would be good as well? My only worry with custom CSS is, well, not everyone using GB is going to know CSS.

**Comment by lorenzhs** [comment]
How do categories reduce the number of settings? They just mean more places to look for settings, and they're exactly what we're trying to avoid.

A "looking for inspiration? See some popular customizations in our wiki!" link below the text box would take care of the CSS knowledge issue for the most part.

**Comment by gdude2002** [comment]
What's wrong with avoiding settings, just out of interest?

**Comment by lorenzhs** [comment]
It adds a lot of complexity for testing, and as much-hated as that argument is, settings create confusion. It just sucks when you have to look for two minutes to find the setting to change something.

**Comment by gdude2002** [comment]
Search box?

I definitely understand the whole testing aspect as a dev myself, though.

**Comment by lorenzhs** [comment]
A search box makes things even worse, because now you need to consider synonyms

**Comment by lorenzhs** [comment]
Closing since this is purely a matter of personal preference and easily fixed once #647 is fixed
