### ISSUE TITLE
slide trigger on desktop

### ISSUE THREAD

**Issue by arnottcr** [glowing-bear/glowing-bear#658]
When I use glowing-bear on my desktop and I highlight text, it triggers the swipe right trigger and opens the channel menu. I can get you a better trace of the issue, but this is the high level description. My intuition would be that you need to activate such triggers on touch events only, but I have not dealt with that type of JS before.

**Comment by lorenzhs** [comment]
It seems that you are using the mobile layout on the Desktop, is that correct? In that case, this is probably a bug with `ngTouch`, angular's touch module. We use the attributes `ng-swipe-left` and `ng-swipe-right` to bind the events, and `ngTouch` manages when they are triggered.

**Comment by lorenzhs** [comment]
I guess we should only bind to `touch`: https://code.angularjs.org/1.5.7/docs/api/ngTouch/service/$swipe
