### ISSUE TITLE
Change buffer keyboard shortcut conflicts with some keymaps

### ISSUE THREAD

**Issue by eepp** [glowing-bear/glowing-bear#67]
Alt+[0-9] might not be the best keyboard shortcut to switch between buffers. With my usual keymap (Canadian French), the `@` character is entered with right Alt+2, so I cannot input a `@` now.

Unless there's a way to differentiate between left and right Alt, we should change this ASAP because it's very annoying.

**Comment by KervyN** [comment]
For Mac the shortcut alt+7 for | is not working.
Maybe there should also be an option to disable certain keybinds.
