### ISSUE TITLE
Human friendly date change markers

### ISSUE THREAD

**Issue by pmelanson** [glowing-bear/glowing-bear#679]
We almost have date change markers, in the form of roughly "date changed to tues mar 08 2015" or whatever. People on IRC are discussing fancier ones, such as "Yesterday" "Last Month" "Last Week".

What do we want for human friendly date change markers?

**Comment by pmelanson** [comment]
Suggestion from @lorenzhs:
"Yesterday"
"n Days Ago" n<7
The full date after that.

What do we want for a full date? "Tues March 7"? Year or no year? Weekday, month, shortened? I think we'd probably all agree that the day of the month shouldn't be zero padded.

**Comment by pmelanson** [comment]
Suggestions from @torhve 

"Last week, Monday" or "Monday of last week"

**Comment by lorenzhs** [comment]
I like @torhve's suggestions as well, but I wouldn't go back further than one week with them. Maybe add the full day just in case? "Yesterday (25 November)", "Monday (23 November)", "Tuesday of last week (17 November)". Preferably using the user's locale if that's at all possible. 

I'd leave out the year if the line is <1y ago, but then again it's highly unlikely that anyone has IRC channels that range that far back with a reasonable amount of lines.

**Comment by lorenzhs** [comment]
#678 and related (#677, #682, #685) added this
