### ISSUE TITLE
URLs with a hash should not generate an IRC channel link

### ISSUE THREAD

**Issue by dancek** [glowing-bear/glowing-bear#680]
If there's an URL like `http://localhost/#foo`, the following markup is generated:

```
<a target="_blank" href="http://localhost/#foo"><span>http://localhost/</span></a><a href="#" onclick="openBuffer('#foo');">#foo</a>
```

Obviously the user won't want to join the `#foo` IRC channel, so this is a bug.

**Comment by lorenzhs** [comment]
this is due to the way filters work, and I don't see how we could fix that easily without rewriting linkification. If you want to work on this yourself, you'de be most welcome to, and we would be open to merging such a PR.

**Comment by dancek** [comment]
@lorenzhs ok! I'm looking at it right now, but I don't understand this unit test:

```js
it('should not mess up IRC channels surrounded by HTML entities', inject(function(irclinkyFilter) {
    expect(irclinkyFilter('<"#foo">')).toEqual('<"<a href="#" onclick="openBuffer(\'#foo">\');">#foo"></a>');
}));
```

I would have thought that markup such as `<"#foo">` should rather be left untouched. Or is this another thing that can and should be fixed?

**Comment by lorenzhs** [comment]
no that's intended behaviour and a test case for a weird angular bug a while back

**Comment by dancek** [comment]
Well, I'm starting to see the problem. I wrote this unit test to see what goes wrong when `DOMfilter` is used (because just combining `linky` and `irclinky` doesn't cause issues).

```js
        it('should not touch links created by `linky`', inject(function(linkyFilter, DOMfilterFilter) {
            var url = 'http://foo.bar/#baz',
                link = linkyFilter(url, '_blank'),
                result = DOMfilterFilter(link, 'irclinky').$$unwrapTrustedValue();
            expect(result).toEqual(link);
        }));
```

The resulting markup is

```html
a target="_blank" href="http://foo.bar/#baz"><span>http://foo.bar/<a href="#" onclick="openBuffer('#baz');">#baz</a></span></a>
```

I'll see if I can think of something to fix this, but you might need to hack `DOMfilter` quite a bit to avoid the issue.
