### ISSUE TITLE
Lines with a hashtag and link crash GB

### ISSUE THREAD

**Issue by rscullin** [glowing-bear/glowing-bear#688]
Certain lines, like the following:

`JVST SAY YES - Switch Ft. Ephwurd by EPHWURD #np https://soundcloud.com/ephwurd/jvst-say-yes-switch-ft-ephwurd`
or
`#crash http://google.com`

cause the latest GB (e63877a) to lock up and become unresponsive when attempted to be displayed. CPU usage goes to 100% and never seems to recover.

**Comment by torhve** [comment]
Probably introduced here: https://github.com/glowing-bear/glowing-bear/pull/681

Can you have a look @dancek ?

**Comment by dancek** [comment]
Oh gee. I'll take a look.
