### ISSUE TITLE
Links and Channel Handles on same line Cause Tab Lockup (HEAD)

### ISSUE THREAD

**Issue by narthollis** [glowing-bear/glowing-bear#690]
When mucking around the repo HEAD, I encountered an issue where the Chrome tab would lock up.

Much frustration and testing has lead me to believe this occurs when there is a channel handle (#channel) and a link (http://example.com/) on the same line.

I was unable to properly debug this issue to the way that my Chrome tab would lock up every time I changed to a channel that had at least one line with both a link and a channel handle on it.

**Comment by cormier** [comment]
Hi @narthollis 

#689 has been deployed on latest.glowing-bear.org, does it fix your issue?

**Comment by narthollis** [comment]
It would appear it does. Thanks and sorry for not checking to see if there had been any new commits since last night :)

**Comment by cormier** [comment]
No problem! And feel free to join us on the IRC channel if you wish to have the latest news about the project.
