### ISSUE TITLE
Sync up unread messages count with weechat every now and then

### ISSUE THREAD

**Issue by pmelanson** [glowing-bear/glowing-bear#692]
Right now, we ask weechat for the unread count when connecting, but then only keep track of unread count on our end. If we make a mistake, or if another device connected to the relay reads messages, our unread count will be off.

@torhve on IRC suggested a timer every now and then to sync up unread counts.

how does something like a `setTimeout(aFunction, 60*60*1000)` sound? If so, what general area would that go in?

**Comment by torhve** [comment]
maybe just in connection.js itself?
we do this on connect now:
```

_requestHotlist().then(function(hotlist) {
    handlers.handleHotlistInfo(hotlist);

    if (successCallback) {
        successCallback();

```

And then we add the counts with += in handler, so that would either have to reset counts first or have to be changed to be assign instead of add.

Maybe just a new handler is easier.
