### ISSUE TITLE
Links are being parsed incorrectly under certain circumstances

### ISSUE THREAD

**Issue by KimBrodowski** [glowing-bear/glowing-bear#698]
Links are incorrectly linked (HTML wise) when the URL does not contain query parameters, but contains an anchor.

Paste the following in any buffer:
Works as expected:
http://example.com/path/file.html?param=value&param2=value2#HeyThisIsTheImportantPart
Creates two links (both incorrect) instead of one:
http://example.com/path/file#HeyThisIsTheImportantPart
http://example.com/file.html#HeyThisIsTheImportantPart
http://example.com/#HeyThisIsTheImportantPart

This leads to applications such as 0bin.net and Google Play Music being broken when accessed through Glowing Bear. 

Real world example links:
https://play.google.com/music/listen#/album//Chris+Huelsbeck/Giana+Sisters%3A+Twisted+Dreams+-+Original+Soundtrack

http://0bin.net/paste/IhWfCkhC7sCmXUuB#g0pU7YIOzvnXCUSDC8eAf1li9MS3q4ZcHhsJo08L2eb

**Comment by lorenzhs** [comment]
I think we fixed this recently in the development version, can you try https://latest.glowing-bear.org and report if the issue is present there as well?

**Comment by SimJoSt** [comment]
As I was experiencing the same problem and just wanted to open an issue, I tested it and my problems with links have been resolved.
Great job.

**Comment by KimBrodowski** [comment]
Yep it's fixed in the dev build. I'll make sure to check that one as well next time. Thank you!
