### ISSUE TITLE
iOS: date change marker doesn't seem to do locale stuff properly

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#700]
pj2melan on iirc said: I got the supported() function from the MDN page on toLocaleDateString

Safari on my iPad (iOS 9.1.1, iPad Air 1) is not supported according to that function.

**Comment by pmelanson** [comment]
Yeah, so the deal with this is that lorenzhs' browser doesn't properly fully support [Date.toLocaleDateString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) arguments. Specifically, the [locales argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#Checking_for_support_for_locales_and_options_arguments). This was determined by using [this one small webpage](https://csclub.uwaterloo.ca/~pj2melan/locale). That webpage used the function defined in the last MDN link, which returned false for lorenzhs but true for my firefox, chrome, and android chrome devices I tested on. So I went out on a limb and determined that this was what was causing the above.

Oh yeah, the problem that lorenzhs had: http://i.imgur.com/WCq6LIM.png the date change message wasn't properly formatted.

My fix will be to check if the browser supports that argument, then if it doesn't fall back to a little hacky thing that isn't ISO standards-compliant but works. PR incoming maybe today who knows.
