### ISSUE TITLE
Read marker is out of sync due to date change messages

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#705]
This is a regression introduced by our fancy new date markers, we should fix it.

Filing this issue so we don't forget.

**Comment by pmelanson** [comment]
So is this happening to the number shown next to each buffer in the buffer list? Like, does a date marker increase the number unread count?

Or is it like what was mentioned in IRC a bit ago, where the unread count was correct but the line showing up to where the last read message is gets shifted somehow?

**Comment by lorenzhs** [comment]
No, the counter is alright - it's that horizontal separator bar that indicates how far you've already read that's in the wrong position.

**Comment by lorenzhs** [comment]
Are you sure that this suffices? What if the date change message is below the readmarker (i.e. in the unread part of the buffer)? I don't think it should increment `lastSeen` in that case.

**Comment by pmelanson** [comment]
correct. I'll fix this.

**Comment by pmelanson** [comment]
PR made, #730 
told you I'd fix it, it just took me a month :stuck_out_tongue:

**Comment by lorenzhs** [comment]
I'm reopening this until the fix is merged

**Comment by lorenzhs** [comment]
This should now finally be fixed :)
