### ISSUE TITLE
GB reconnects 2-3 times a minute with Firefox v43

### ISSUE THREAD

**Issue by aedocw** [glowing-bear/glowing-bear#711]
Using stable glowing-bear (www.glowing-bear.org) and latest.glowing-bear.org, Firefox v43 reconnects to weechat relay 2-3 times per minute.  This happens over both encrypted and unencrypted channel.  Firebug console shows this each time:
Relay error
e/<()angular.min.js (line 102)
s/_()min.js (line 2)
[error ]

Weechat buffer shows:
 19:17 	<=!=>	relay: reading data on socket for client 2/ssl.weechat/1.1.1.1: error 0 (connection closed by peer)
19:17 	<>	relay: disconnected from client 2/ssl.weechat/1.1.1.1
19:17 	<>	relay: new client on port 9002: 2/ssl.weechat/1.1.1.1

This seems to have started happening to me in the last day.  Possibly related is that within the last two days I upgraded weechat from v.04 to v1.3, and then 1.4dev.  Previously I had been using FF with glowing-bear for 6 months with no issues.

Switching to Chrome has resolved the issue but I look forward to going back to firefox for this.

I'm on freenode IRC as "docaedo" and am available to provide additional information as needed.

**Comment by lorenzhs** [comment]
Thanks for the report. Can you paste the traceback from https://latest.glowing-bear.org/master/ as well, please? www. and latest. are minified and "min.js (line 2)" doesn't contain any useful information. If we knew which line threw the error, maybe this could start to make sense.

**Comment by aedocw** [comment]
Sure - here's what I got from the console at latest.glowing-bear.org/master/ - let me know if this is not what you're looking for (I haven't  spent much time debugging JS issues before)

Relay error
e/<()angular.min.js (line 102)
connect/onerror()connection.js (line 156)
[error ]
	

angular.min.js (line 102)
Disconnected from relay
angular.min.js (line 102)
The connection to wss://<server>:9002/weechat was interrupted while the page was loading.
websockets.js (line 121, col 13)
ws = new WebSocket(url);

**Comment by lorenzhs** [comment]
Right, that definitely looks like an issue with Firefox or some other software on your machine. The connection is being interrupted, which is out of our control. I fear that I have no idea how to approach this, but wish you the best of luck resolving this and please let us know what you find out! I'm going to leave this issue open for a while in case someone else has similar issues.

**Comment by aedocw** [comment]
Completely agree, I don't think this is actually a glowing-bear bug. I don't have too many addons, but behavior is the same with ghostery and ublock disabled.  Connection is also interrupted when portforwarding connection to weechat over SSH (and then connecting to localhost from glowing-bear).

Odd situation for sure - I'll close this, if someone else hits the same issue they'll at least see this in the list as invalid, but can open/comment if it can be reproduced :)

**Comment by Suver1** [comment]
Just confirming the issue: I also have this issue in Firefox without any extensions enabled, running encrypted https://latest.glowing-bear.org/
19:39 <=!=> relay: reading data on socket for client 4/ssl.weechat/::ffff:1.1.1.1: error 0 (connection closed by peer)
19:39 <>	relay: disconnected from client 4/ssl.weechat/::ffff:1.1.1.1
19:39 <>	relay: new client on port 9001: 5/ssl.weechat/::ffff:1.1.1.1
19:39 <=!=> relay: reading data on socket for client 5/ssl.weechat/::ffff:1.1.1.1: error 0 (connection closed by peer)
19:39 <>	relay: disconnected from client 5/ssl.weechat/::ffff:1.1.1.1
19:39 <>	relay: new client on port 9001: 6/ssl.weechat/::ffff:1.1.1.1

**Comment by torhve** [comment]
Do you have logs from javascript too? Those messages literally means what they say, closed by peer.

**Comment by Suver1** [comment]
Not yet. I switched to https://latest.glowing-bear.org/master/ just now. I'll get back to you if/when I get some valuable traceback.

**Comment by aedocw** [comment]
With firefox 44.0.2 running under Ubuntu 14.04 (kernel  3.19.0-49-generic) the issue is resolved for me.
