### ISSUE TITLE
Update README to include section about letsencrypt and nginx proxy

### ISSUE THREAD

**Issue by torhve** [glowing-bear/glowing-bear#713]
Our preferred way is to always use HTTPS and behind nginx proxy wit updated cipher settings with rate limiting to prevent brute force.

We should have a section in readme to help people with how to configure nginx and weechat for this, and then we can also change our default port to 443.

**Comment by r4v5** [comment]
Would you say the nginx proxy is necessary, or just recommended? I can see from just doing a 443 redirect with iptables that, by default, weechat supports some terrible ciphers (a bunch of 3DES/RC4 stuff). `/set relay.network.ssl_priorities` seems to be a knob to frob to change this, and https://wiki.mozilla.org/Security/Server_Side_TLS#GnuTLS_ciphersuite has a value for it that seems to work, with the exception of only 1024-bit DH parameters.

I'd take a stab at documenting an nginx config if you feel it necessary. I was already documenting the process of getting a LE key with standalone validation and putting that into weechat as a standard SSL relay, so it's not *too* far out of my way.

**Comment by lorenzhs** [comment]
nginx proxy is not required, but recommended. Part of the reasoning is that you're more likely to keep nginx cipher stuff up to date than weechat (or even know that it's configurable in weechat!), you have one endpoint that's very good at terminating connections etc etc.

We've got sample nginx config snippets flying around somewhere, mine is:
```
	location /weechat {
		proxy_pass https://weechat;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		proxy_read_timeout 604800;
		proxy_set_header X-Real-IP $remote_addr;
	}

server {
        <other stuff>
	location /weechat {
		proxy_pass http://weechat;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		proxy_read_timeout 604800;
		proxy_set_header X-Real-IP $remote_addr;
	}
}
```

**Comment by MarcusLlewellyn** [comment]
Please do add documentation about this. I managed to figure out that running weechat behind a nginx proxy was the way to go only after about 90 minutes of banging my head against a gnuTLS 110 error. After putting weechat behind a proxy, it just worked. Reduce the bruised heads!

Also, I agree with the point that anyone using LetEncrypt is going to find this a lot easier to maintain.

**Comment by lorenzhs** [comment]
There's already *some* documentation on the whole proxy stuff: https://github.com/glowing-bear/glowing-bear#faq - but it's not very well presented. We should improve that in the README.
