### ISSUE TITLE
Mysterious disconnects

### ISSUE THREAD

**Issue by komaflash** [glowing-bear/glowing-bear#719]
I'm using WeeChat 1.3 [compiled on Aug 16 2015 10:05:36] runnig on ubuntu server 14.04. No matter if i use latest or www glowing bear always connects and disconnects in a loop.

Every hint is appreciated!

```
2:08:15 weechat     | relay: disconnected from client 14/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 15/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
22:08:15 weechat     | relay: disconnected from client 15/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 16/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
22:08:15 weechat     | relay: disconnected from client 16/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 17/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
22:08:15 weechat     | relay: disconnected from client 17/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 18/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
22:08:15 weechat     | relay: disconnected from client 18/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 19/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
22:08:15 weechat     | relay: disconnected from client 19/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 20/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
22:08:15 weechat     | relay: disconnected from client 20/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 21/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
22:08:15 weechat     | relay: disconnected from client 21/ssl.weechat/IPV6:Address
22:08:15 weechat =!= | relay: reading data on socket for client 23/ssl.weechat/IPV6:Address: error 0 (connection closed by peer)
```

JS Console tells us
```
22:13:39.029 Relay error 
error { 
	target: WebSocket, 
	isTrusted: true, 
	currentTarget: WebSocket, 
	eventPhase: 2, 
	bubbles: false, 
	cancelable: false, 
	defaultPrevented: false, 
	timeStamp: 1450818819026571, 
	originalTarget: WebSocket, 
	explicitOriginalTarget: WebSocket, 
	NONE: 0 }
1 angular.min.js:102:264
e/<() angular.min.js:102
s/w() min.js:2
```

**Comment by lorenzhs** [comment]
To me this looks like your browser or maybe your ISP is closing your connection. Are you on a mobile network? Some ISPs are known to disconnect long-running connections after as little time as 20 seconds.

**Comment by komaflash** [comment]
@lorenzhs Thanks for your reply. I'm using a usual VDSL connection. No LTE or else is involved.

**Comment by lorenzhs** [comment]
So you have no problems with other long-running connections? Any firewall software or browser addons that might be doing that? Because to me it looks like this: Glowing Bear is getting an error from the browser that the connection was somehow interrupted, and weechat sees the connection as being closed. Something is closing that connection and it's not glowing bear (otherwise we wouldn't see that error).

**Comment by komaflash** [comment]
I tried chromium and firefox without any addons - same problem. 
My android weechat-client works like charm, but it uses IPv4.

**Comment by lorenzhs** [comment]
So maybe it's your IPv6 connection that's causing problems? Can you try disabling IPv6 (or use the IPv4 address of your weechat server) and see if that helps?

**Comment by komaflash** [comment]
It also happens if i connect via IPv4 to the weechat instance.
I'm absolutly clueless and i think it's rather not related to glowing bear, but to an config problem somewhere in the middle.
Thanks for your support. Merry christmas ;)

**Comment by lorenzhs** [comment]
Alright, I wish you the best of luck resolving it, and a merry christmas to you, too!

**Comment by komaflash** [comment]
I tried to connect with 
* Android-Client in my private WLAN: OK
* Android-Client in mobile network: OK
* Laptop in another Network: OK (Firefox 42.0)
* Laptop in my private WLAN: OK (Firefox 42.0)
* Workstation: NOT OK

Conclusion: Something is from with the workstation. ;)
