### ISSUE TITLE
buffer closing issue

### ISSUE THREAD

**Issue by mexus** [glowing-bear/glowing-bear#724]
When I close "relay.relay.list" buffer with a `Q<Enter>` the buffer disappears from the list of buffers (on the left), but the window doesn't switch so another buffer.
It happens only from time to time, and only in `chromium` browser (47.0.2526.106), I wasn't able to reproduce it in firefox (43.0.1).

I'm running GB from [http://www.glowing-bear.org/](http://www.glowing-bear.org/)

Steps to reproduce:
1. Open GB
2. Go to "relay.relay.list" buffer
3. Type in `Q` and hit the `Enter`
4. Normally the active window will be switched to the `weechat` buffer, if that's the case:
5. Press `F5` and go to step `2`

As for me, it takes 5-10 refreshes to achive the described state.

Here is how it looks like (no errors in the console):
![Active windows is a closed buffer](https://transfer.sh/f0ZhR/2016-01-02-212415-1618x1000-escrotum.png)

So I wonder if I am the only lucky man with the issue, and if so I'll ask the developers how can I debug the case.

**Comment by mexus** [comment]
Ha, actually the same happens not only for `relay.relay.list`, but also for channels.
Steps to reproduce:
1. Join channel
2. `/close`
3. go to `1`

**Comment by lorenzhs** [comment]
@mexus can you still reproduce this on https://latest.glowing-bear.org/?

**Comment by mexus** [comment]
@lorenzhs no, I can't reproduce this anymore, so I guess the case closed.

**Comment by lorenzhs** [comment]
Awesome, thanks for your help! If you ever notice it again, let us know.
