### ISSUE TITLE
Can an option be added to always open links in a new tab?

### ISSUE THREAD

**Issue by blha303** [glowing-bear/glowing-bear#744]
As it is, if someone links a Youtube video and you click on it, it opens in the same tab, when the preferred behavior for me would be opening it in a new tab, for example by adding target="_blank" to external links. Is this possible?

**Comment by blha303** [comment]
In the meantime I made a bookmarklet that makes any link to an external domain open in a new window. It uses findParent from this stackoverflow answer http://stackoverflow.com/a/12552017

```
javascript:function findParent(e,o){if((o.nodeName||o.tagName).toLowerCase()===e.toLowerCase())return o;for(;o=o.parentNode;)if((o.nodeName||o.tagName).toLowerCase()===e.toLowerCase())return o;return null};window.onclick = function(e) { if (findParent('a',e.target || e.srcElement) && (e.target.host != window.location.host)) { e.target.target = "_blank" } }
```

**Comment by lorenzhs** [comment]
We already pass the '_blank' parameter to linky, so all links have the target set accordingly. We have no control over included content, so if the youtube iframe doesn't do that, then we can't force it to. Rewriting links in an iframe from a different domain is prevented by CSRF protection iirc. In any case, it's bad practice and we shouldn't be doing it.

What we should be doing is something like http://jsbin.com/uhajun/2/edit?html,css,js,output

**Comment by blha303** [comment]
I recorded a video testing this. https://s.b303.me/SOcY.mp4

After a refresh (clearing the effects of the above bookmarklet), the link opens in the same tab. After going back and clicking on the bookmarklet to add target="_blank", the link opens in a new tab as expected. Lastly I show that, in a freshly reloaded page, links processed by linky have no target="_blank".

**Comment by torhve** [comment]
This doesn't happen in any of my browsers. As lorenz said, we already add _blank to links. Maybe you have some addon or something else with your browser that is interfering. I am closing this issue.

**Comment by lorenzhs** [comment]
Agreed. The last frame of your video even shows the `linky:'_blank'` part. You also have two errors in the JS console, there shouldn't be any there.

**Comment by blha303** [comment]
The two errors are both

    Failed to load resource: https://developer.android.com/images/brand/en_app_rgb_wo_45.png the server responded with a status of 404 (OK)

But you are correct, loading Glowing Bear in an incognito window shows <a target="_blank">. Apologies.
