### ISSUE TITLE
Add support for clearing notifications without refreshing glowing-bear

### ISSUE THREAD

**Issue by furhouse** [glowing-bear/glowing-bear#748]
WeeChat has a function to clear the hotlist (activity notification on other buffers), `/input hotlist_clear`.

Running the same command in glowing-bear clears the buffers only after reconnecting to glowing-bear. It would be nice to be able to clear the hotlist without having to reconnect.

**Comment by lorenzhs** [comment]
This should probably be implemented similar to https://github.com/glowing-bear/glowing-bear/blob/73123fd0dd46ffc9637c206b064939b5b0f21f03/js/inputbar.js#L141 (unless we can get some sort of event to do it properly)

**Comment by torhve** [comment]
Fixed with automatical sync every 60 s in latest gb.
