### ISSUE TITLE
Cannot connect to session via Safari iOS

### ISSUE THREAD

**Issue by ghostfreeman** [glowing-bear/glowing-bear#756]
I've been attempting to connect to my Weechat relay from Safari iOS with an "Error: Wrong Password" warning despite using the correct password on other devices, and confirming it via Relay settings. The isssue seems to be isolated to my iPad 2 running iOS 9.3 and Safari.

When I have some time this week I will post some Debug output to help with issue resolution.

**Comment by lorenzhs** [comment]
This kind of issue is usually easier to debug on IRC, feel free to join us in #glowing-bear on freenode. Personally I have no issue connecting with iOS, but I recall someone describing the same issue recently. I forgot how they resolved it though, but maybe they'll notice your issue on IRC? ;)

**Comment by lorenzhs** [comment]
Oh and please note that self-signed certificates cause lots of issues on iOS, I'd recommend a trusted certificate from Let's Encrypt. iOS and OS X also don't support TLS keys with >4096 bits.

**Comment by lorenzhs** [comment]
As @torhve said on IRC, 99% of the time that people are having issues with TLS, the certificate chain is incomplete. Try adding all intermediates to the `relay.pem` and reload the certificate in weechat (`/relay sslcertkey`).

**Comment by lorenzhs** [comment]
Closing for lack of feedback
