### ISSUE TITLE
'&sect'  breaks hyperlinks

### ISSUE THREAD

**Issue by trisk** [glowing-bear/glowing-bear#763]
For the following URL appearing in a message:
`http://www.mgaleg.maryland.gov/webmga/frmStatutesText.aspx?article=grp&section=8-402&ext=html&session=2015RS&tab=subject5`

The actual href in the link appears as (in Chrome):
`http://www.mgaleg.maryland.gov/webmga/frmStatutesText.aspx?article=grp§ion=8-402&amp;ext=html&amp;session=2015RS&amp;tab=subject5`

The `&sect` seems to be converted to `§` which is HTML entity `&sect;`.

**Comment by lorenzhs** [comment]
This is a bug in ngSanitize (angular.js): https://github.com/angular/angular.js/issues/10565 - sanitizing is hard, but angular is making a fool of themselves. This is not the first issue we've had with crap like that. We should switch to something better for sanitizing / linkifying.
