### ISSUE TITLE
Improve linky

### ISSUE THREAD

**Issue by torhve** [glowing-bear/glowing-bear#774]
We should add these to our linky like this:

<div ng-bind-html="snippetWithSingleURL | linky:'_self':{rel: 'noopener noreferrer'}"></div>

Because: https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c#.hugalsd7c

**Comment by lorenzhs** [comment]
Yeah, grep.py tells me already talked about this in March
