### ISSUE TITLE
Error: wrong password on browser like surf or midori

### ISSUE THREAD

**Issue by blaskovic** [glowing-bear/glowing-bear#776]
Hi,

I am getting 

> Error: wrong password

In browsers like [surf](http://surf.suckless.org/) or [midori](http://midori-browser.org/)

It works just fine with the same credentials in Chrome or Firefox.

Tell me how to obtain additional information which would help you with debugging. Thank you

**Comment by lorenzhs** [comment]
Well you're going to have to be a bit more specific: Are you using encryption? Is the certificate self-signed or trusted by the system/browser? What happens when you go to `https://<weechathost>:<relayport>/weechat`, do you get a certificate error (bad) or a blank page that never finishes loading (good)?

Also, can you please post the console output of the developer tools? Free free to remove your hostname.

**Comment by blaskovic** [comment]
> Are you using encryption? Is the certificate self-signed or trusted by the system/browser?
Yes, self signed cert

> What happens when you go to https://<weechathost>:<relayport>/weechat, do you get a certificate error (bad) or a blank page that never finishes loading (good)?
Just blank white page.

> can you please post the console output of the developer tools?
```
[Debug] Connecting to URL:  wss://domain.tld:9001/weechat (angular.min.js, line 107)
[Error] WebSocket network error: Unacceptable TLS certificate (www.glowing-bear.org, line 0)
[Log] Disconnected from relay (angular.min.js, line 107)
```

So, it looks like, surf cannot accept the cert. This is weird, because I use it for other web pages on which I have self signed cert too. It works without warning so I think surf just ignore it at all.

I am not familiar with websockets, but maybe it uses different mechanism than loading the page, so maybe surf does not have it implemented properly (to ignore it).

**Comment by lorenzhs** [comment]
Yeah, surf is rejecting it - it might be intended on their part (for security reasons), but they should at least allow it if you've manually accepted the certificate.

I'm closing this issue because there's nothing that we can do it, browser behaviour is outside of our reach :(

**Comment by blaskovic** [comment]
Yes, I understand.

So it's the best time to get it working with letsencrypt :) Thank you

**Comment by lorenzhs** [comment]
Yup, definitely! :)

**Comment by blaskovic** [comment]
It works like charm with letsencrypt cert.

Thanks.

**Comment by lorenzhs** [comment]
Awesome, great to hear that!
