### ISSUE TITLE
Ability to pin buffers

### ISSUE THREAD

**Issue by torhve** [glowing-bear/glowing-bear#778]
Would be extremely helfpul to have a drag&drop of buffers to "pin" them to the top. This would help a lot when you display only unread buffers but still have a few favorite buffers that you switch to often.

**Comment by lorenzhs** [comment]
See #604

**Comment by torhve** [comment]
I couldn't find that issue when I looked. I'm terrible :(

I wonder if we could start with a "pin" button before going full drag&drop.

**Comment by rickybrent** [comment]
I like this idea, too -- I actually wrote code to do this solely for my own use (as a a comma-separated list in settings), but that definitely wouldn't cut it as a real way to handle the ux for pinning/unpinning.

**Comment by lorenzhs** [comment]
Duplicate of #608 and #440
