### ISSUE TITLE
I don't see underscores in buffers content

### ISSUE THREAD

**Issue by JulienPalard** [glowing-bear/glowing-bear#779]
I tried to play a bit with the CSS to find the origin of the problem but that's not easy for me:

 - It's zoom-level dependent (if I zoom-in, underscores appear).
 - It's font-dependent, by default the `DejaVu Sans Mono—80 glyphs` is used and the bug is here
   but with `Liberation Sans—80 glyphs`, I see underscores
 - It's bound to `line-height: 100%` (meaning `14px` in my case, if I disable the `line-height: 100%` I get a `line-height` of `20px` and underscores appear)
 - I'm using Chromium 47.0.2526.80 from the Debian package 47.0.2526.80-1~deb8u1
 - I upgraded to Chromium 50.0.2661.94 from the Debian package 50.0.2661.94-1, still missing underscores

How can I help on this ?

**Comment by lorenzhs** [comment]
Quickfix would probably be to put `tr.bufferline { line-height: 1.1; }` in the custom CSS box. I'm not sure how we can fix this in the general case, given that we can't know which font the system will eventually use. It probably depends on fonts installed, fonts chosen, rendering engine, screen resolution and a bunch of other parameters we don't really control.

**Comment by gene1wood** [comment]
@lorenzhs For what it's worth I also get this same problem in my different browser and different OS, just as @JulienPalard describes.

Ubuntu 14.04
Firefox 52.0

I can confirm the custom CSS workaround does workaround the problem.

**Comment by lorenzhs** [comment]
I don't think there's much we can do in general, it really depends on which fonts you have installed. Choosing a different font (in settings) or increasing line height a bit are the easiest ways to fix it.
