### ISSUE TITLE
Display buffer timestamps in a matter consistent with detected locale

### ISSUE THREAD

**Issue by Techman-** [glowing-bear/glowing-bear#782]
(This is a feature request)
I live in the United States, so following strftime my optimal timestamp in this case would be formatted as `%I:%M:%S %p`. [This site](http://foragoodstrftime.com/) is a really neat cheat-sheet. It ends up looking like `08:49:47 PM`. Even though I used strftime for this, it can be converted to what AngularJS uses by [their docs](https://docs.angularjs.org/api/ng/filter/date).

Slightly off track here, but I wonder why [a strftime library](https://www.google.com/search?q=strftime+javascript) for glowing-bear wasn't used.

**Comment by torhve** [comment]
Angular provides functions for formatting time, that's what we use: https://docs.angularjs.org/api/ng/filter/date

**Comment by torhve** [comment]
For those looking to implement this, take a look at the function `injectDateChangeMessageIfNeeded` in file `js/handlers.js` that already does some locale stuff.

**Comment by pmelanson** [comment]
@Techman- made a PR, from my testing it now puts 12h time format if the system locale is 12h time. Do you want to test to make sure? https://latest.glowing-bear.org/pull/783/

**Comment by torhve** [comment]
GB will now use weechat configuration, so this should work now.

**Comment by Techman-** [comment]
Is this working on the main website now?

**Comment by lorenzhs** [comment]
https://latest.glowing-bear.org/ for now
