### ISSUE TITLE
Readme and documentation are a bit outdated

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#788]
- [x] remove link Firefox OS app - it's outdated and Firefox OS isn't being developed any more
- [x] remove "install as Firefox app" thingy, it's removed from Firefox
- [ ] mention electron more prominently (maybe we should set up travis builds on releases)

**Comment by cormier** [comment]
I think #853 fixes this.. unless we want to mention electron even more prominently? :)

**Comment by lorenzhs** [comment]
Fair point, let's close it
