### ISSUE TITLE
Fetch time format from weechat

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#789]
using https://github.com/glowing-bear/glowing-bear/pull/710 it should be fairly straight-forward to fetch the `weechat.look.buffer_time_format` option. We can't use it directly (it has more syntax, including colours, than JS can handle) but we can definitely use it to distinguish between 24h (%H/%HH) and 12h (%h/%hh) time formats

**Comment by lorenzhs** [comment]
documentation for date format used by angular: https://docs.angularjs.org/api/ng/filter/date

**Comment by pmelanson** [comment]
(relates to #783 #782)

From IRC:

<+lorenzh>	basically we should probably look for %H / %h (translate them to %HH/%hh) and maybe AM/PM markers and add those if present in weechat
<+lorenzh>	if you feel like porting the colour support, knock yourself out, that would be cool - but I think detecting 24h/12h and whether AM/PM markers are used (in 12h) is good enough ™️

I'll get to this at some point, but it won't be immediately.

**Comment by lorenzhs** [comment]
This would also allow us to get rid of the two timestamp options \o/ (see if the weechat time string has seconds shown, and ditch them if not)
