### ISSUE TITLE
After upgrading to firefox 48: Can't login anymore (Secure connection error)

### ISSUE THREAD

**Issue by dreamcat4** [glowing-bear/glowing-bear#801]
Hi there,
Firefox upgraded itself recently (automatially) to version 48. Straight after it did that, firefox could not load except in safe mode. Finally after clearing cache etc, firefox would work again. So after reconnecting have again recently re-added the self-signed cert (for weechat relay) back into to SSL exceptions list. Normally that would be it. However for some not-known reason this time its still refusing to log in. Nothing on the server side has changed.

![](http://i.imgur.com/QurBMHY.png)

It would be nice to know if anybody else is using glowing-bear successfully on the latest Firefox v48. Or if there was any other issue for them. Many thanks.

**Comment by lorenzhs** [comment]
I have no issues with Fx48 (from the Debian unstable repos). Firefox not starting except in safe mode sounds like an issue with your profile (extensions maybe?). I'm pretty sure that this isn't a Glowing Bear issue (thus closing it). But maybe we can help you resolve it if you paste the JavaScript console output?

**Comment by dreamcat4** [comment]
BTW sorry I forgot to mention earlier that this was on Win10.

Ahh interesting.

```javascript
Service Worker is supportedangular.min.js:107:210
Connecting to URL:  "wss://localhost:9001/weechat"angular.min.js:107:210
...
Firefox can't establish a connection to the server at wss://localhost:9001/weechat.min.js:2:18765
Relay error error { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1470386977595000, originalTarget: WebSocket, explicitOriginalTarget: WebSocket, NONE: 0 }angular.min.js:107:210

Disconnected from relayangular.min.js:107:210
```

It says its trying to conect to `localhost`. But that is not right and the hostname auto-filled into the connection box is `irc.lan`...

So to cut a long story short, I just had to change the target hostname to something fake, then change it back and everything was fine. Perhaps it was some weird autofill issue. Especially if the default value is supposed to be `localhost`.

**Comment by lorenzhs** [comment]
That's weird. Sounds like a localstorage issue (which would be in line with cache etc being weird). Glad you got it working again!
