### ISSUE TITLE
Configuring weechat buffer_time_format to include dates doesn't affect GB

### ISSUE THREAD

**Issue by darrenkenny** [glowing-bear/glowing-bear#803]
It would be nice if our parser for WeeChat's time format also handled dates, which is useful when catching up with the logs after vacation. That way you can simply add the date to the time format and not get confused about chronological ordering.

-- edited by @lorenzhs

---
Original comment:

While for every-day use, the HH:MM time format is fine, it would be useful when browsing
back in time, especially after returning from vacation, to be able to opt for a time format that
includes the date or something else.

A simple field that takes strftime formatting strings would be perfect.

**Comment by torhve** [comment]
We parse the time format defined in WeeChat configuration in latest version of glowing bear.

**Comment by darrenkenny** [comment]
Can you tell me which option? I would expect it to be:

   /set weechat.look.buffer_time_format %F %H:%M:%S

but that doesn't work in the Glowing Bear interface nor does other formats that include
the date - .e.g. %d/%m/%y %H:%M:%S, etc.

A quick look in the connection.js file seems to suggest that it is converting several time
formats to angular, but it is totally skipping any date formatting.

**Comment by torhve** [comment]
Date formatting is supposed to be solved by date marker once per day.

**Comment by torhve** [comment]
Each day change you get a localized line saying which date it changed to

**Comment by darrenkenny** [comment]
Sure, but it's definitely a matter of preference if someone wants to have the date in every item - it works in Weechat itself - so why strip it out in the web app?

Also, some of the IRC channels that I would be on are very active, so having to look back possibly several
pages to locate what day something was said on is not always practical - as mentioned this is especially
an issue when browsing back history of several days post vacation, or similar.

**Comment by torhve** [comment]
I don't think anyone is opposed to that funcionality existing, it's just that the author who wrote that parsing code didn't add support for dates.

For very active channels I just assume that the last line is today, and then as I read scrollback I see the date markers once the day wraps.

Anyway, feel free to add an issue (or possibly rename this for the discussion?) to support parsing date configuration from WeeChat.

**Comment by darrenkenny** [comment]
Will update the synopsis - since I believe this is more of a bug now than a new feature.

**Comment by darrenkenny** [comment]
Anyway to re-open this?

**Comment by lorenzhs** [comment]
I wouldn't say bug, it's more of an improvement to broaden an existing feature's scope. I'll edit the synopsis at the top accordingly.

**Comment by darrenkenny** [comment]
Fair enough, thanks for re-opening.

**Comment by pmelanson** [comment]
Hey @darrenkenny I'm the one who has been doing work on timestamps recently so this is kinda me. I've tried to make time for this improvement/bugfix, but I don't think I'm going to get to this before I'm out of internet for a couple weeks this weekend. If it's super annoying or you're code fingers are feeling itchy, anyone who uses glowing-bear like you do would probably appreciate a new contributor on this issue :P 

Alternatively just wait for a while more and I'll get to it eventually.

**Comment by lorenzhs** [comment]
Fixed in #816
