### ISSUE TITLE
Cannot connect to SSL.weechat relay

### ISSUE THREAD

**Issue by dragonshardz** [glowing-bear/glowing-bear#808]
Pretty much as it says on the tin. I go through the steps to set up SSL connections - though I used LetsEncrypt instead of StartCom, because they won't issue SSL certificates to .tk domains - but when I add the ssl.weechat relay, it just fails to connect. When I reconnect using non-SSL, I can see the following error message:

```
23:16	<>	relay: new client on port 9002: 657/ssl.weechat/::ffff:69.62.180.135
23:16	<=!=>	relay: TLS handshake failed for client 657/ssl.weechat/::ffff:69.62.180.135: error -15 An unexpected TLS packet was received.
23:16	<>	relay: disconnected from client 657/ssl.weechat/::ffff:69.62.180.135
```

What am I missing that is preventing this from working?

**Comment by lorenzhs** [comment]
Please don't file an issue for setup problems, it's much easier to help with these on our IRC channel (#glowing-bear on freenode). Your issue can have many possible causes, and it's near impossible to diagnose over GitHub issues. Here are some things you could try:
- navigate to `https://<host>:<port>/weechat` (e.g. `https://foo.bar:9002/weechat`) in your browser. Do you get a certificate error? Correct behaviour would be a blank page.
- did you run `/relay sslcertkey` after setting your certificate? Try re-running it.
- is there any output in the JS console?
- let our bot diagnose your TLS setup, query `lorelai` on freenode and type `>tls <host>:<port>` (substituting host and port as above)

If those steps don't help, please join us in #glowing-bear on freenode and ask there, I'm sure we can figure this out!

Oh and Let's Encrypt is the preferred method now :) It just wasn't ready when I wrote the guide. StartCom is a bit shady and not nice to use. We just haven't updated the docs yet.
