### ISSUE TITLE
Feature request: Remember last viewed channel, and go to it

### ISSUE THREAD

**Issue by dreamcat4** [glowing-bear/glowing-bear#809]
The idea is that once you get logged into Glowing Bear, it doesn't just always dump you onto the 1st buffer at the top of the list (weechat). But actually remembers the last channel buffer you were viewing from the previous web session. And automatically opens that channel instead.

For a nicer / more enhanced user experience.

**Comment by lorenzhs** [comment]
See #807 ...

**Comment by lorenzhs** [comment]
Fixed in #807
