### ISSUE TITLE
incorrect password when using a password manager

### ISSUE THREAD

**Issue by mmlb** [glowing-bear/glowing-bear#811]
I'm using [passwordmaker](https://chrome.google.com/webstore/detail/passwordmaker-pro/lnhofcfhehhcbccpmdmdpjncdoihmkkh) on chrome and every time it auto fills the password I have to type a character at the end, then delete it. Otherwise gb will return an error `Error: wrong password`.

**Comment by lorenzhs** [comment]
I think that's a bug with passwordmaker or Angular, not Glowing Bear. We have an input field with `ng-model="password"` - if your password manager sets the password in a way that doesn't trigger angular's change listener, the model is never updated, and Glowing Bear only sees an empty password. See https://github.com/angular/angular.js/issues/3133

**Comment by lorenzhs** [comment]
@mmlb can you see if https://latest.glowing-bear.org/paste-quickfix/ fixes the issue for you? It triggers an input event on all inputs before connecting, which triggers angular's change handlers

**Comment by mmlb** [comment]
@lorenzhs nope same error

**Comment by lorenzhs** [comment]
Hm. Then I'm not sure what's causing it, sorry. If you want to investigate this yourself, the issue is that angular's watchers (for `ng-model`) aren't triggered by whatever mechanism your password manager uses to fill in the password. Explicitly triggering an input event on the input doesn't seem to help (or I'm doing it wrong).

**Comment by mmlb** [comment]
aww :(, let me ping @heavensrevenge on this then. Any thoughts?

**Comment by mmlb** [comment]
@lorenzhs thanks for looking into it. I've pinged the dev of passwordmaker, hopefully he has some thoughts.

**Comment by heavensrevenge** [comment]
Hello @mmlb & @lorenzhs , oh @lorenzhs would you mind changing https://github.com/glowing-bear/glowing-bear/blob/ae1295c3f2dcd8e24e3a528e467a253ff912ae5f/js/glowingbear.js#L598-L599 to be `"var event = new Event('change', {'bubbles': true, 'cancelable': true}));"` to see if it works for him? if it does I'll just add the fix to my extension too.

**Comment by lorenzhs** [comment]
I just pushed to the branch, https://latest.glowing-bear.org/paste-quickfix/ should be up to date in <15 minutes.

**Comment by mmlb** [comment]
Sadly does not work, same error.

**Comment by heavensrevenge** [comment]
There must be a way to do this that is angular friendly... I'm looking into this since this may be related to one of my past issues.

**Comment by mmlb** [comment]
thanks a lot @heavensrevenge

**Comment by heavensrevenge** [comment]
OK I've pushed out 0.8.5 of my extension to try and work around angular needing to do a $apply or $dispatch in their own angular apps to update their state.  

After it updates to 0.8.5 for you and you give it a shot, let me know if it works for you too since it worked for me on my end.

**Comment by mmlb** [comment]
Yup works for me
