### ISSUE TITLE
Close-parenthesis ends a hyperlink prematurely

### ISSUE THREAD

**Issue by lycurgus** [glowing-bear/glowing-bear#820]
If a hyperlink ends with a close-parenthesis (as many Wikipedia links in particular do), it's not included in the hyperlink. For instance, `https://en.wikipedia.org/wiki/BNC_(software)` is rendered as a link to `https://en.wikipedia.org/wiki/BNC_(software` with a trailing `)`; clicking the link goes to Wikipedia's "did you mean..." page.

![broken-link](https://cloud.githubusercontent.com/assets/8443742/18812068/faa91dbe-830a-11e6-83e2-26e8e9a4ec3d.png)

**Comment by lorenzhs** [comment]
This is a problem with angular.js -- we use its linky filter for that. It's a known issue :\

**Comment by lycurgus** [comment]
Ah, okay - that's unfortunate but understandable. Thanks for the quick response :)
