### ISSUE TITLE
Nicks with background color break in nicklist

### ISSUE THREAD

**Issue by Vaesper** [glowing-bear/glowing-bear#823]
left side is weechat in terminal, right side is glowing-bear:

![](https://i.imgur.com/uhh3Vi7.png)

Inspecting the elements shows that they do not get the appropriate classes applied. The coloring of these same nicks does work in the chat buffers, background color included.

**Comment by lorenzhs** [comment]
Seems to be a problem with `models.nickGetColorClasses`: https://github.com/glowing-bear/glowing-bear/blob/f98dc977371306b12c5492b357ac88db3484b558/js/models.js#L389

Not sure what there is that we're not handling. Any ideas, @torhve @eirikb?

**Comment by Vaesper** [comment]
Just for completeness' sake; the incorrectly classed nicks get "cwf-default" applied to them whereas the correctly classed nicks (ie. the ones without background colour) get a "cef-X" class applied. In the chat area, the nicks with background colour get both "cef-X" and "ceb-Y" classes applied.

**Comment by lorenzhs** [comment]
Hm. Maybe this could be merged with the `parseRichText` function? I don't know enough about formatting in WeeChat, though

**Comment by oakkitten** [comment]
possibly #513 is related

**Comment by lorenzhs** [comment]
I don't think so - there we just use our own because we didn't have a way to get the correct style previously (but now we do, so this could be done). Here, we fail to parse the style correctly.

**Comment by Vaesper** [comment]
I think I see the problem. Colors in weechat can be of the form FG:BG - in the if/else block there is no catch for colors containing the : symbol.

**Comment by Vaesper** [comment]
Unfortunately I don't have a working test setup; I'd be much obliged if someone else could verify that this works (and doesn't break anything).

`function nickGetColorClasses(nickMsg, propName) {
    var colorClasses = [
        'cwf-default'
    ];
    if (propName in nickMsg && nickMsg[propName] && nickMsg[propName].length > 0) {
        var color = nickMsg[propName];

        if (color.match(/^weechat/)) {
            // color option
            var colorName = color.match(/[a-zA-Z0-9_]+$/)[0];
            colorClasses = [
                'cof-' + colorName,
                'cob-' + colorName,
                'coa-' + colorName
            ];
        } else {
            if (color.match(/^[a-zA-Z]+[:$]/)) {
                // WeeChat color name (foreground)
		var fgcolor = color.match(/^[a-zA-Z]+[:$]/)[0];
                colorClasses = [
                    'cwf-' + fgcolor
                ];
            } else if (color.match(/^[0-9]+[:$]/)) {
                // extended color (foreground)
		var fgcolor = color.match(/^[0-9]+[:$]/)[0];
                colorClasses = [
                    'cef-' + fgcolor
                ];
            }
            if (color.match(/:[a-zA-Z]+$/)) {
                // WeeChat color name (background)
                var bgcolor = color.match(/:[a-zA-Z]+$/)[0];
                colorClasses.push('cwb-' + bgcolor);
            } else if (color.match(/:[0-9]+$/)) {
                // extended color (background)
                var bgcolor = color.match(/:[0-9]+$/)[0];
                colorClasses.push('ceb-' + bgcolor);
            }
        }
    }
    return colorClasses;
}`
