### ISSUE TITLE
Mark all messages as read?

### ISSUE THREAD

**Issue by Phyks** [glowing-bear/glowing-bear#832]
Hi,

There is a shortcut in Weechat, "Alt+h" on my setup, to mark all buffers as read. I did not find anything equivalent in Glowing Bear and I think it could be really useful.

Typically, I suggest that upon clicking the total number of unread items, a confirm box pops and asks whether we really want to mark all the unread items as read.

What do you think?

**Comment by Vaesper** [comment]
I agree with this one, only thing to consider is if it should also mark unread highlights as read.

**Comment by Phyks** [comment]
In weechat, it marks everything as read, including hilights.
