### ISSUE TITLE
Feature: toggle nicklist on mobile without going through settings menu.

### ISSUE THREAD

**Issue by Vaesper** [glowing-bear/glowing-bear#838]
Ideally implemented to work with swipe and a button, like how channel list works. Sometimes you just want to quickly check who is in a channel.

**Comment by lorenzhs** [comment]
We had a swipe thingy before. It didn't work properly (opened the nicklist when you wanted to close the buffer list, and stuff like that) so we removed it. We're certainly not opposed to opening and closing the nicklist with a swipe at the right end of the screen. If someone has experience with swipe gestures in Angular apps, this shouldn't be too hard to implement and we'd welcome a PR—it's just that we didn't manage to get it to work properly ;)

**Comment by Vaesper** [comment]
I have no idea about Angular so perhaps I'm way off here but a simple idea to circumvent that: have a "swipestate" variable that you decrement by swiping left (minimum value 0) and increment by swiping right (maximum value 2). Then if swipestate = 0, show the buffer list, if swipestate = 2, show the nicklist, else show neither.
