### ISSUE TITLE
Youtube video IDs with an underscore are cropped in embed URL

### ISSUE THREAD

**Issue by MoonZ** [glowing-bear/glowing-bear#848]
Example:

`https://www.youtube.com/watch?v=E-OvK_sgoOE`

Is translated in the HTML page to :

```html
<iframe src="https://www.youtube.com/embed/E-OvK?html5=1&amp;iv_load_policy=3&amp;modestbranding=1&amp;rel=0&amp;showinfo=0" width="560" height="315" frameborder="0" allowfullscreen="true"></iframe>
```

Not sure why though, the YT plugin regexp looks OK in that regard.

Context infos: 

WeeChat 1.6 Windows 7 x86
Glowing Bear front end : http://www.glowing-bear.org/

Browsers displaying this behavior: 
- Chrome Version 54.0.2840.71 m
- Firefox: 48.0.2, 49.0.2

**Comment by lorenzhs** [comment]
Works fine in mobile safari. Interesting...

**Comment by lorenzhs** [comment]
Oh could you try https://latest.glowing-bear.org? I believe we fixed this a while back. Should make a release.

Also, you should really use an encrypted relay and Glowing Bear over https if you're connecting over the internet!

**Comment by MoonZ** [comment]
I can confirm it does work with the latest version.
I'm using a local only connection for the moment, Thanks for your advice, will do.

**Comment by lorenzhs** [comment]
Awesome, I'll close it then :)
