### ISSUE TITLE
Filter command do nothing until force refresh of the buffer

### ISSUE THREAD

**Issue by Phyks** [glowing-bear/glowing-bear#851]
Hi,

If typing `/filter toggle` in a Glowing bear buffer, the content of the buffer is cached and the `filter` command then has no effect at first. Changing buffer do not force reload either.

It seems that scrolling the buffer, up to the "fetch more lines" limit does reload the buffer content and apply the `filter` command though.

It would be really nice if Glowing-bear was able to intercept the `filter toggle` command and force a reload of opened buffers.

Thanks

**Comment by Vaesper** [comment]
I think this is more generally a thing that GB doesn't count on bufferlines changing/being removed, only being added. For example iset also doesn't work well in GB.

**Comment by lorenzhs** [comment]
As @torhve said on IRC, there isn't an event in the relay protocol for this, so we can't do it :(
```
20:14	<+xt>	the relay protocol doesn't support it
20:15	<+xt>	i think
20:15	<+xt>	it's not something we can choose
20:15	<+xt>	to support
20:15	<+xt>	same with iset
20:15	<+xt>	those are "free bufferse", not line based
20:15	<+xt>	relay protocol *could* support it, but it doesn't
20:18	<+xt>	https://weechat.org/files/doc/devel/weechat_relay_protocol.en.html
20:18	<+xt>	no _buffer_line_changed
```
- Sorry :disappointed:

**Comment by Vaesper** [comment]
Could have a button for force refresh?

**Comment by lorenzhs** [comment]
But how would you communicate the button's purpose? Most of the time it just looks weird and you have no use for it. I don't think it would be particularly nice. We should probably ask FlashCode nicely to add it to WeeChat, that would be a much better solution.

**Comment by Vaesper** [comment]
Good point.
