### ISSUE TITLE
Sync buffer read status

### ISSUE THREAD

**Issue by Mikaela** [glowing-bear/glowing-bear#870]
I use:

* WeeChat directly
* WeeChat Android
* Glowing Bear

When I read something with WeeChat or WeeChat Android, I see that reflected in the other "client". When I read something with WeeChat, the chance doesn't come to Glowing Bear and I must refresh the page for seeing that I read everything at WeeChat.

I think this is feature of the WeeChat Relay protocol as WeeChat Android help text for option *Sync buffer read status* says *Mark buffers as read in WeeChat when you read them in this app. Requires WeeChat 1.0 or newer.*

**Comment by lorenzhs** [comment]
This should work in https://latest.glowing-bear.org - it's just not in a release yet. Simply updating Glowing Bear read status should work even before weechat 1.0

**Comment by lorenzhs** [comment]
Fixed in #796, duplicate of #692
