### ISSUE TITLE
Unable to type @-character in safari 10.0.1

### ISSUE THREAD

**Issue by aptituz** [glowing-bear/glowing-bear#875]
In Safari, when using the mac-typical keyboard layout, where the at-character is typed by hitting alt-l, I'm unable to type an at-character into the glowing bear text field. 

This affects the field used in chatting and can be workarounded by configuring a different keymap (e.g. a typical pc-keyboard-layout with at-character on alt-q). The input fields on the startpage, e.g. for server address are not affected.

**Comment by Nicd** [comment]
This happens on any Mac browser I think, at least on Chromium based ones too. It's because GB's alt-keycodes take priority. This prevents the typing of at least `©@£$∞§|[]` on a Finnish layout.

**Comment by lorenzhs** [comment]
Yeah, we really need to rework our keyboard shortcuts and use a different modifier key on Mac OS. See #572 (of which this is a duplicate)
