### ISSUE TITLE
Add option to use DCC when drag-and-dropping files

### ISSUE THREAD

**Issue by LoganBarnett** [glowing-bear/glowing-bear#876]
I think the auto imgur thing is great, but sometimes you straight up want to DCC a file. Sometimes that's the case with images too, where you don't want your image publicly discoverable for whatever reason. Could this be a configurable option? Or did I just miss how to do it via Glowing Bear?

Thanks!

**Comment by lorenzhs** [comment]
You certainly didn't miss it, I can reassure you there ;)

I'm not sure whether this is possible via the relay protocol. But I'm also not sure how many people even use DCC any more? Depending on how much work it would be to add to GB (and maintain!), I'm not sure whether we want to support it. @torhve do you know more?

**Comment by torhve** [comment]
I don't think the relay protocol has any way to transfer abitrary data from the client to weechat, so that seems unlikely we could add such a feature. If WeeChat grew this capability we can revisit this issue.
