### ISSUE TITLE
window.location.hash linking to channel

### ISSUE THREAD

**Issue by blha303** [glowing-bear/glowing-bear#877]
It would be handy to have the URL hash link to the current window using the channel ID (e.g /#irc.network.#channel) so 1. bookmarks for glowing bear can link to a particular channel or buffer, 2. refreshing the page returns the user to the same channel they were on. Example code that would achieve this effect:

```
window.onload = function() {
    if (window.location.hash) {
        setActiveBuffer(window.location.hash.substr(1))
    }
}
```

But I have no clue how Angular works so I'm unable to PR it.

**Comment by lorenzhs** [comment]
Well, we support passing connection settings in the hash, too (see https://github.com/glowing-bear/glowing-bear/blob/17d14364edaa59beb229cf4bffd904bf74b86854/js/glowingbear.js#L840), so it isn't quite that easy, but it would indeed be nice.
