### ISSUE TITLE
Getting rid of third-party such as cloudflare

### ISSUE THREAD

**Issue by Phyks** [glowing-bear/glowing-bear#879]
Hi,

I am hosting my own instance of glowing-bear. Then, I'd like to make requests only on my server and not any third-party such as cloudflare.

I've found [this command line](https://github.com/glowing-bear/glowing-bear/blob/master/electron.makefile#L15-L17) which seems to do it, but it is undocumented in the wiki, and seems to be directly related to "native" apps generation.

What about adding some documentation about the correct way to use bundled third-party rather than cloudflare's? Thanks!

**Comment by lorenzhs** [comment]
Sure, we could add an npm target for this to `package.json`. Would you like to add a section about this to README.md? It would probably make a nice bullet point under the FAQ.
