### ISSUE TITLE
font size option has no effect

### ISSUE THREAD

**Issue by occivink** [glowing-bear/glowing-bear#882]
Hi,

Changing the font size in the options doesn't seem to influence the text in the chat in any way. Changing the font works properly though.

I'm using firefox 50.1.0

**Comment by lorenzhs** [comment]
Can you refresh the page and see if the issue persists? I can't reproduce this on www or latest. In line with 33c3's motto, I guess all I can say is

![](https://4z2.de/worksforme.png)

**Comment by occivink** [comment]
Refreshing doesn't do anything. I suppose that my bug report doesn't have much informantion to help debug, but that's mostly because I'm using vanilla settings (i.e. no firefox extensions, no outstanding weechat settings, current www glowing bear instance). Let me know if there's anything else you need.

**Comment by lorenzhs** [comment]
Oh did you specify a font size unit (like `px`)? You have to add a unit—the default is 14px.

**Comment by occivink** [comment]
Oh right, that works. Thanks.

**Comment by lorenzhs** [comment]
Glad you got it working! Maybe the current solution isn't the most intuitive one. We could just append 'px' if the input is just a number?

**Comment by occivink** [comment]
If that's the only possible unit that'd probably be the best yes,

**Comment by lorenzhs** [comment]
Well it's not the only unit but the most common one. You can still specify other units.
