### ISSUE TITLE
Stuck at Fetching more lines

### ISSUE THREAD

**Issue by Allu2** [glowing-bear/glowing-bear#886]
What is happening:

Glowing bear loads and connects properly.
I see list of servers and channels, I even see icon indicating amount of messages I have unread.
I click on any channel and it opens up showing only few channel messages (joins, left and such)
After this no messages appear, the "Fetching more lines" line is shown and keeps spinning eternally.
Messages written to Glowing Bear reach the channels and show up there, but not on the Glowing bear itself.
No errors are shown.

WeeChat version 0.4.2, HTTPS is enabled but bug occures without it as well.
This happens in https://www.glowing-bear.org/#
as well as https://latest.glowing-bear.org/#

**Comment by Allu2** [comment]
Turns out I had some funky language preference set in the Firefox settings
"intl.accept_languages=fi"
JS console had error:
Error: invalid language tag: intl.accept_languages=fi

After removing it Glowing bear started to work properly

**Comment by lorenzhs** [comment]
Glad you got it working! Just a note, WeeChat 0.4.2 is really old, and we strongly encourage you to update to a more recent version. There are many fixed bugs and improved behaviour with Glowing Bear. Version 1.1 or later would be best.
