### ISSUE TITLE
Put glowing-bear on f-droid

### ISSUE THREAD

**Issue by matthiasbeyer** [glowing-bear/glowing-bear#889]
Would be awesome.

**Comment by lorenzhs** [comment]
Meh. I maintain the Android app but I don't even use Android any more, it's a pain to develop as it is. I honestly don't want to keep it up to date on another platform. If you really don't want to use Google Play or build it yourself, I upload the apk to https://4z2.de/glowingbear-release.apk (signature: https://4z2.de/glowingbear-release.apk.asc) whenever I rebuild (includes beta builds). It's signed with the exact same keys as the Play Store version. Update announcements are in our channel, #glowing-bear on freenode. Sorry if this is cumbersome.

**Comment by matthiasbeyer** [comment]
Thanks for your fast reply, I guess this will suffice for me!

**Comment by AeliusSaionji** [comment]
> I honestly don't want to keep it up to date on another platform.

fwiw, I don't think it works that way. F-Droid make their own builds by pulling directly from git. Once you connect the automated build system, your involvement is minimal.
