### ISSUE TITLE
Website down! CNAME Cross-User Banned

### ISSUE THREAD

**Issue by Zopieux** [glowing-bear/glowing-bear#900]
https://www.glowing-bear.org/
>Error 1014
>Ray ID: 335d94651a41691a • 2017-02-23 20:55:36 UTC
>
>What happened?
>You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.

**Comment by BKPepe** [comment]
Same here.

> Error 1014 
> Ray ID: 335dd2619c8f3e26 • 2017-02-23 21:37:55 UTC
> CNAME Cross-User Banned

**Comment by lorenzhs** [comment]
I'm on it, if anyone has encountered that error before I'd love any pointers. I didn't change anything in the cloudflare account, no idea what they're trying to tell me.

**Comment by lorenzhs** [comment]
Apparently it's a Cloudflare issue: https://twitter.com/Yank/status/834874220223995904

In the meantime, you can use https://latest.glowing-bear.org/ which should be stable (and doesn't use Cloudflare).

Sorry about the inconvenience

**Comment by Zopieux** [comment]
Yep, I'm using latest in the meantime. Thanks for the quick reply.

**Comment by lorenzhs** [comment]
Alright, it's working again so I'm closing this. Sorry again, hopefully cloudflare will release some info on what went wrong

**Comment by Zopieux** [comment]
Well… I think we can agree that they did, given the [shitstorm](https://bugs.chromium.org/p/project-zero/issues/detail?id=1139) they are now facing. :smile:

**Comment by lorenzhs** [comment]
Nope that's completely unrelated, jgrahamc confirmed on HN

**Comment by kleedrac** [comment]
Do we know if our weechat passwords were compromised?  I changed mine and finally got 'round to setting up glowing-bear on a VPS yesterday.

**Comment by Zopieux** [comment]
@lorenzhs okay thanks for the info.
@kleedrac I don't think so, it stays in your browser. The only thing that could leak it is frontend code (JavaScript).

**Comment by lorenzhs** [comment]
@kleedrac no traffic goes through our site (it's not "cloud", it's a direct connection from your browser to your weechat). Unless you proxy your relay through Cloudflare (and I have no idea why anybody would want to do that) then your credentials are safe.
