### ISSUE TITLE
Bad home page user experience when javascript is disabled

### ISSUE THREAD

**Issue by itsrachelfish** [glowing-bear/glowing-bear#902]
When searching for Glowing Bear, the first result is your website [glowing-bear.org](http://www.glowing-bear.org) which I'd expect to contain information about what Glowing Bear is. Unfortunately the site relies on client-side rendering so it's impossible to learn what the site is about without enabling javascript first. Also there's a ton of error messages everywhere.

I understand that Glowing Bear is a webapp and relies on javascript, but don't you think there should at least be some information visible to users that don't have javascript enabled?

![screenshot from 2017-02-24 06 45 19](https://cloud.githubusercontent.com/assets/1670549/23305703/55865b88-fa5d-11e6-8a63-de223d41e164.png)

**Comment by lorenzhs** [comment]
Fair point. Maybe we can just add a `<noscript>` tag that tells non-JS users to check out the github page and excuse the rendering mess? :> It wouldn't be pretty but at least a little bit helpful

**Comment by Vaesper** [comment]
I know for one that uMatrix doesn't trigger `<noscript>` tags.

**Comment by lorenzhs** [comment]
Ugh. But uMatrix users with restrictive defaults should be used to breakage, right? :)

The other option, of course, would be to use something `ng-if="::(!!angular)"` to hide it for js-enabled users. We would just need to prevent flickering.

**Comment by rscullin** [comment]
I've opened a PR ( #945 ) that should fix this issue. Tested and works well for me with uMatrix blocking both 1st and 3rd party scripts.
