### ISSUE TITLE
Disable automatic emoji in input

### ISSUE THREAD

**Issue by SimonSapin** [glowing-bear/glowing-bear#903]
When I talk about Rust’s `std::io::Write` trait, Glowing Bear automatically replaces `:io:` with `🇮🇴` (U+1F1EE REGIONAL INDICATOR SYMBOL LETTER I, U+1F1F4 REGIONAL INDICATOR SYMBOL LETTER O). If I hit backspace after the moment the replacement happens, the whole sequence is removed. There seems to be no way to input `:io:` literally. This is frustrating.

I disabled the "Enable non-native Emoji support" setting, but that one seems to be about rendering, not input.

I finally manage to disable this "feature" by messing with the source code:

```diff
diff --git a/js/inputbar.js b/js/inputbar.js
index 4777988..80ece0a 100644
--- a/js/inputbar.js
+++ b/js/inputbar.js
@@ -25,9 +25,9 @@ weechat.directive('inputBar', function() {
                              settings) {
 
             // E.g. Turn :smile: into the unicode equivalent
-            $scope.inputChanged = function() {
-                $scope.command = emojione.shortnameToUnicode($scope.command);
-            };
+//            $scope.inputChanged = function() {
+//                $scope.command = emojione.shortnameToUnicode($scope.command);
+//            };
 
             /*
              * Returns the input element
```

These should probably be a setting for this.

**Comment by lorenzhs** [comment]
I think it's never a good idea to replace matches that aren't surrounded by whitespace, but I don't think emojione has an option to do so. I filed https://github.com/Ranks/emojione/issues/409 a while ago with no response so far.

**Comment by SimonSapin** [comment]
The whitespace thing would be a good start, but regardless I think it’s wrong to make it impossible to input some strings of characters.

Compare with auto-correct on mobile (at least on my phone, Android with Google’s keyboard): when auto-correct changes anything, hitting "backspace" undoes the change and restores what was actually typed. And auto-correction can be disabled completely.

**Comment by lorenzhs** [comment]
Yes, I agree that that would be preferable. I'm not aware of an easy solution, though—EmojiOne isn't very suitable for this usecase :(

**Comment by SimonSapin** [comment]
Proposal:
* Rename the *Enable non-native Emoji support* setting to *Enable non-native Emoji rendering*
* Add another setting called *Enable automatic replacement of EmojiOne short names like `:smile:` in input* or something, that controls whether `emojione.shortnameToUnicode` is used.

Personally I would keep this new setting disabled. Someone who likes that feature could keep it enabled, but disable it temporarily when the really need to work around it. This would make inputting a literal `:de:` (for example) merely very inconvenient, instead of impossible without messing with the source code.

**Comment by lorenzhs** [comment]
Eh, I don't like adding settings, it makes setup confusing for new users. I'd rather we fix the current behaviour so that it only replaces freestanding matches and allows undoing replacements with backspace.

But given that the replacement isn't very publicly known and causes more trouble than it's worth, maybe we should just disable autoreplacement for now and instead aim for an emoji picker completion thingy like GitHub's?

**Comment by SimonSapin** [comment]
Disabling works for me to, the setting proposal was an attempt at making the proposal less disruptive.

**Comment by lorenzhs** [comment]
Here's an idea: tokenize the string into sections that are separated by whitespace. Push each token through the emojifier. **If** the result contains *only* emoji, use the emojified version, otherwise discard it and use the original. Join the result back together with the whitespace that was used for splitting. That way we can have emojification without having to fix emojione :)

**Comment by txanatan** [comment]
I definitely use the emojification a lot, and I know of a few people who do - but we might be in the minority. I think a config option is the way to go here, even if it's disabled by default. The whitespace tokenization seems like a good idea, as well.

**Comment by lorenzhs** [comment]
OK so removing it might be a bit too lazy ;) I'll try implementing the tokenization approach.
