### ISSUE TITLE
nick list cannot display on iPad

### ISSUE THREAD

**Issue by Bekcpear** [glowing-bear/glowing-bear#924]
I found this bug and try a way to fix it.

The `#nicklist-div` is in the `#bufferlines-div` by default. When nick list displaying under my iPad Safari, its content is covered by `margin-right` of `#bufferlines-div`.  I also try to modify the z-index property but have no effect.

If move the `#nicklist-div` to outside of `#bufferlines-div`, everything looks fine. Check the index.html in this commit: https://github.com/Bekcpear/glowing-bear/commit/74992279a0db4781cb226a9068b2299e5b9527f8

*I have no idea whether this modification can affect other features, and I also have only iPad(with version 10.2.1) so I don't know if it works on iPhone or other iOS device.*

**Comment by lorenzhs** [comment]
Yeah it's kind of a known bug that the nicklist doesn't show on iOS. Thanks for working on fixing it! I'll test when I get home, but I'd like to avoid the CSS hackery in JS if possible. I'll play around with it a bit and see if I can make it work.

**Comment by alexbarton** [comment]
I'm seeing this as well (or better: I'm not seeing the nick list), latest iOS on iPad and iPhone.

Is there anything I can help with to get this fixed?

Thanks for sour great work,
Alex

**Comment by alexbarton** [comment]
BTW: Pull request #926 "[WIP/TEST] Fix nicklist display on iOS" is related, but outdated ...

**Comment by lorenzhs** [comment]
Yeah that PR doesn't work with the new swiping implementation, and anyway, it's a workaround. I'm not sure how best to fix it, CSS is not my specialty. It also doesn't help that I don't have a Mac to debug it (there's sort of a read-only web inspector proxy tool for Chrome, https://github.com/google/ios-webkit-debug-proxy, but it doesn't allow playing around with values). If you have experience in that area, a fix would be greatly appreciated :)
