### ISSUE TITLE
Can't remove channels from channel list

### ISSUE THREAD

**Issue by JulienPalard** [glowing-bear/glowing-bear#929]
Hi, thanks for Glowinw-Bear, loving it.

Until now, I was able to leave a channel using "/leave" and to make the channel dissapear in the channel list by typing "/leave" again (don't know if it was the expected behavior).

But now (latest.glowing-bear.org with 1.5-1~bpo8+1), the second "/leave" does not remove the channel from the channel list. Did I missed an obvious feature to do it or it is a bug?

**Comment by lorenzhs** [comment]
Hi Julien, I'm not terribly familiar with weechat commands but a single /close should be enough, have you tried that? If a buffer is closed in weechat but doesn't disappear in Glowing Bear then that's a bug of course.

**Comment by JulienPalard** [comment]
Yes, it works, thank you, not familiar with weechat commands either, I was stuck to the good old `/leave` as it worked on glowing-bear.

Thanks!

**Comment by lorenzhs** [comment]
Awesome! I think I've had an issue once or twice in the past where buffers really didn't close in Glowing Bear (but did in WeeChat), I've never been able to reproduce but if you observe that, please do reopen this issue!
