### ISSUE TITLE
`README.md`: update the instruction on setting up TLS as Chrome 58 mandates `subjectAlternativeName`

### ISSUE THREAD

**Issue by MaskRay** [glowing-bear/glowing-bear#934]
<https://4z2.de/2014/07/06/weechat-trusted-relay> referred by `README.md` no longer works because Chrome 58 has removed support for `commonName` matching in certificates and mandated `subjectAlternativeName`. https://developers.google.com/web/updates/2017/03/chrome-58-deprecations#remove_support_for_commonname_matching_in_certificates

The commands below can be used to generate self-signed certificates and `ca.cert.pem` can be imported to  chrome://settings/certificates，Authorities tab Edit->Trust this certificate for identifying websites.
```zsh
openssl req -x509 -newkey rsa:2048 -nodes -keyout ca.key.pem -out ca.cert.pem -days 9999 -subj '/CN=127.0.0.1'
openssl req -new -newkey rsa:2048 -nodes -keyout key.pem -subj '/CN=127.0.0.1' |
  openssl x509 -req -out cert.pem -CAkey ca.key.pem -CA ca.cert.pem -set_serial 2 -days 9999 -extfile <(
    printf "subjectAltName = IP:127.0.0.1, DNS:localhost")
```

**Comment by lorenzhs** [comment]
Hey @MaskRay, thanks for the info! 4z2.de is my website, and I marked the article as deprecated, but maybe not clearly enough. We should remove the link from the readme. We now recommend using let's encrypt, and the instructions have moved to the landing page. It's not merged back into the stable instance yet, but you can see them at https://latest.glowing-bear.org/ ("Getting Started").
