### ISSUE TITLE
Incorrect time zone used on Android

### ISSUE THREAD

**Issue by SimonSapin** [glowing-bear/glowing-bear#936]
The Android Play Store says this is version 0.6.0. I changed my phone’s time zone several times over the past few weeks. Glowing Bear kept using the time zone of two changes ago for showing the time of messages and date change lines. Force-closing the app and restarting it did not help, but rebooting the phone did.

**Comment by lorenzhs** [comment]
Sadly there's not much we can do about that, angular's `date` filter uses the browser-provided time zone by default [(documentation)](https://docs.angularjs.org/api/ng/filter/date). It seems that Android's WebView component somehow doesn't get the memo about the time zone change until you reboot. It's not quite the same issue but https://bugs.chromium.org/p/chromium/issues/detail?id=520783 might be related.

**Comment by SimonSapin** [comment]
Is there a way to use Glowing Bear on Android with a more modern browser engine the WebView, and also make sure that Glowing Bear’s own files stay in cache and don’t need to be fetched from the network at random times?

**Comment by lorenzhs** [comment]
Android updates the web view via the play store now. What is your Android version?

The files are packaged in the app. It doesn't download anything.

**Comment by SimonSapin** [comment]
Android 7.1.2.

I meant using something other than the Play Store app, in order to use something other than WebView.

**Comment by lorenzhs** [comment]
Well you can just use the web page :) https://www.glowing-bear.org, or https://latest.glowing-bear.org if you want to try the development version (it's pretty stable, I use it exclusively)
