### ISSUE TITLE
Use modal topic overlay on desktop, too

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#943]
Otherwise it's impossible to open links that are near the end of the topic, or even comfortably read long topics. The alt text isn't really enough.

**Comment by Techman-** [comment]
> \<Techman\>	Re: that post talking about making the topic popup show up on desktop
> \<Techman\>	I just did .mobile {display:inline;} and span.desktop{display:none;} to hide the desktop topic and only show the channel name in the topic bar. It also shows the nick complete button (which I'm okay with)
> \<Techman\>	I dunno if display:inline; was the proper choice or not but it didn't look weird so I stuck with it. It's been a good 3+ years since I was seriously into doing CSS modifications on websites so I'm a little rusty on that.
> \<Techman\>	I think there's a few ways you could go about doing a solution where the truncated topic is still shown, like adding a button only visible when in "desktop" view
> \<Techman\>	Or you could go the route of making any text-only (so, non-hyperlinked) areas of the topic link to showModal('topicModal')
> \<Techman\>	While you're at it, you might as well go full IRCCloud and add an edit button for when you're a halfop and up in a channel so you can inline edit it and save

**Comment by lorenzhs** [comment]
I'd like to continue showing as much of the topic as possible on desktop, but add the modal popup behaviour from mobile to desktop. #946 does this. Just showing all the things that are shown on mobile and hiding the desktop things is a very large hammer :)

Edit button would be nice, this goes in the direction of other proposals to wrap IRC commands with UI elements.
