### ISSUE TITLE
image URL at end of /topic has extraneous quote

### ISSUE THREAD

**Issue by nivex** [glowing-bear/glowing-bear#954]
On joining the channel I see:
`Topic for #example is "IPv6 all the things! | https://eclipse2017.nasa.gov/ | Do not taunt happy fun lemur! http://www.nivex.net/images/attacklemur.jpg"`
Which results in an attempt to display and link to `http://www.nivex.net/images/attacklemur.jpg%22`

**Comment by lorenzhs** [comment]
We let angular handle the linkification, so it's their bug, not ours. Angular's linky isn't very good though and we're a bit unhappy with it. Maybe one day we'll substitute a better one, but until then, fixing this means fixing angular. Sorry.
