### ISSUE TITLE
CORS issue with Firefox Nightly

### ISSUE THREAD

**Issue by tcitworld** [glowing-bear/glowing-bear#956]
Angular is broken with Firefox Nightly because the CORS header "Access-Control-Allow-Origin" is missing, and it seems the « Same Origin » policy blocks this.

**Comment by lorenzhs** [comment]
Sorry, not a specialist on CORS etc. Can you break this down into what's needed to fix it? Don't have time to read up on it in-depth atm.

**Comment by TheBlusky** [comment]
This Header is needed on the relay, not on glowing beard. If you use a reverse-proxy for weechat relay, you can probably add the Header in your apache/nginx server.

If you can manage to do it, it would be nice to add the answer on the readme :-)

**Comment by lorenzhs** [comment]
OK I just downloaded Firefox 56.0a1 nightly and both latest and www work just fine for me. I have no "Access-Control-Allow-Origin" headers configured in my nginx (which proxies the relay). I do have the following:
```nginx
        add_header Strict-Transport-Security "max-age=31536000;";
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header Content-Security-Policy "default-src https:; style-src https: 'unsafe-inline'";
        add_header X-Xss-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
```

**Comment by Nicd** [comment]
AFAIK CORS does not apply to WebSocket connections, so there is probably something else wrong with your setup.

**Comment by lorenzhs** [comment]
@tcitworld @pmelanson can you provide an update on this?

**Comment by pmelanson** [comment]
Wow, g-b had actually been broken for a while for me for exactly this reason, but I tried it just now and it worked! That's some wizard magic right there.

**Comment by lorenzhs** [comment]
So was this a Firebox bug and we can close the issue? Glad it's working for you again :)

**Comment by pmelanson** [comment]
I'm 75% sure it was a Firefox bug, but I never did a full investigation. I'd say close the issue, then if someone is still having this issue after updating Firefox/glowing-bear etc then they can post here.

And thank you!
