### ISSUE TITLE
Matrix support

### ISSUE THREAD

**Issue by aditya3098** [glowing-bear/glowing-bear#958]
Hi, 
Kinda unfamiliar with the codebase, Ill try to get something for this, but for now I want to just post the idea. I use matrix as a weechat backend, and matrix has its own way of doing image uploads. I was wondering if it is possible to detect matrix rooms and use their upload system rather than imgur.
[https://matrix.org/docs/api/client-server/#!/Media/post_matrix_media_r0_upload](https://matrix.org/docs/api/client-server/#!/Media/post_matrix_media_r0_upload) contains information on how to do the upload itself. I think we can slightly modify the imgur code we can make it work. My question is mainly how I can detect what I am in.

Glowing bear seems to be the best matrix client apart from that one thing, so I would love to see this feature.

**Comment by lorenzhs** [comment]
Gonna have to ask @torhve on that one, he's the one who developed matrix.lua :)

**Comment by aditya3098** [comment]
Um, sorry, had a brainfart. Of course this doesn't touch the matrix network handling. Sorry...

**Comment by lorenzhs** [comment]
Not sure, maybe Glowing Bear could handle that off to matrix.lua? The relay protocol might not have provisions for that kind of thing, though.

**Comment by aditya3098** [comment]
I don't think matrix.lua supports image upload anyway, because in order to upload the images you'll need a way to load the images into weechat. I guess I should look into other things. I should probably set myself up a custom imgur-compatible api within my VPN so things get viewed real nice.

**Comment by aditya3098** [comment]
Ill probably add something to matrix.lua to post a base64 encoded image up, and then simply patch up gb to send the data: value over.

**Comment by lorenzhs** [comment]
From IRC:
```
13:16	<+xt>	matrix.lua supports image upload
13:17	<+xt>	but you'd have to get the images over to weechat
13:17	<+xt>	seems backwards
13:17	<+xt>	can just post directly
13:17	<+xt>	glowing bear could read the matrix-settings from the conf and just use that
```

**Comment by aditya3098** [comment]
Huh. I'm going to clone some gits and read some code.
