### ISSUE TITLE
Parentheses left out in URLs linkification

### ISSUE THREAD

**Issue by TimelessBeing** [glowing-bear/glowing-bear#961]
Many URLs have parentheses in them, especially those from wikipedia as for example https://en.wikipedia.org/wiki/Parenthesis_(disambiguation)

Right now, when this url is linkified in glowing-bear, the right parenthesis is left out (and therefore the link points to the wrong url)

**Comment by lorenzhs** [comment]
Yup, there's a bunch of issues about linkification that all boil down to Angular's linky Filter being terrible. We want to replace it at some point but until then there's nothing we can do :( Sorry

**Comment by AStove** [comment]
Fixed in #1148, please close
