### ISSUE TITLE
weechat.completion.nick_completer is not working in glowing-beat

### ISSUE THREAD

**Issue by apidrone** [glowing-bear/glowing-bear#963]
Set weechat.completion.nick_completer to "" or any other delimiter. The console client works well, but glowing-bear does not respect the property set

**Comment by lorenzhs** [comment]
Yeah, we don't parse and implement those right now. This would be a nice addition, though. Settings can be retrieved via `connection.fetchConfValue('weechat.completion.nick_completer', function() { /* callback */});`, the result will be stored in the `models.wconfig` dictionary. I'll play around with it.
