### ISSUE TITLE
Electron build fails on Windows

### ISSUE THREAD

**Issue by xobs** [glowing-bear/glowing-bear#980]
According to the documentation, a Windows build of Electron can be generated with `npm install; npm install electron-packager; npm run build-electron-windows`.  However, this last command fails:

````
[12:40:10 PM] ~/Documents/Code/glowing-bear> npm run build-electron-windows

> glowing-bear@0.7.0 build-electron-windows C:\Users\smcro\Documents\Code\glowing-bear
> make -f electron.makefile build-electron-windows

find bower_components \( -name "*min.js" -o -name "*min.css" \) -exec cp {} 3rdparty \;
File not found - "*min.css"
make: *** [copylocal] Error 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! glowing-bear@0.7.0 build-electron-windows: `make -f electron.makefile build-electron-windows`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the glowing-bear@0.7.0 build-electron-windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\smcro\AppData\Roaming\npm-cache\_logs\2018-02-22T04_40_21_259Z-debug.log
[12:40:21 PM] ~/Documents/Code/glowing-bear>
````

It looks like this is because it uses commands such as `find`, `sed`, and `cp` that are not present on Windows, so `make` is failing.

**Comment by lorenzhs** [comment]
The problem isn't that it cant find `find`, the problem is that `find` can't find the files it's looking for :smile: It looks like `bower install` failed to download bootstrap, can you manually run `bower install` and see if that works? 

I just tried (on my debian machine) and can build the electron app for Windows without problems from a fresh clone, so it looks like something went wrong on your machine.

**Comment by xobs** [comment]
`find.exe` is in `C:\Windows\system32`, and is akin to "grep" in terms of what it can do.

I've managed to manually copy files and run a build that mostly works (with the occasional assert error), so I suspect the issue is that the build system is relying on Unix commands that are not present on Windows.

**Comment by lorenzhs** [comment]
Ah right, you need a GNU userland, either through the Linux subsystem on Windows 10 or mingw.  Maybe we should add a note about that in the README.
