### ISSUE TITLE
electron build fails here

### ISSUE THREAD

**Issue by Hakker** [glowing-bear/glowing-bear#982]
C:\glowing-bear>npm run build-electron-windows

> glowing-bear@0.7.0 build-electron-windows C:\glowing-bear
> make -f electron.makefile build-electron-windows

find bower_components \( -name "*min.js" -o -name "*min.css" \) -exec cp {} 3rdparty \;
File not found - "*min.css"
make: *** [copylocal] Error 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! glowing-bear@0.7.0 build-electron-windows: `make -f electron.makefile build-electron-windows`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the glowing-bear@0.7.0 build-electron-windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2018-02-25T22_46_49_690Z-debug.log

**Comment by lorenzhs** [comment]
This is the same issue as #981. You need a GNU userland, either via the Linux Subsystem for Windows (Win10) or mingw.
