### ISSUE TITLE
Website and gh-pages out of date

### ISSUE THREAD

**Issue by evaryont** [glowing-bear/glowing-bear#984]
Seems like there have been a huge number of commits but gh-pages hasn't been kept up to date with them. The latest tagged release is from Feb 2016! I think there's been something worth a version bump committed since then. 😄

**Comment by lorenzhs** [comment]
Yes, very true. There some iOS 11 bugs (and laziness) that have kept me from making a release but given that the bugs aren't regressions (it's just as bad on gh-pages) maybe we should just go ahead and make a release. I'm on vacation next week, if there are no blockers or vetoes I'll try to release when I get back :)

**Comment by andrewchambers** [comment]
Also the tag v0.6.0 is not listed as the latest release by github for whatever reason, if you go to releases it shows 0.5.0 (note the missing v)

**Comment by lorenzhs** [comment]
It lists it if you click on "show 9 newer tags". Github seems to distinguish between the two types of tags git knows, and shows only tags with a description etc by default

**Comment by evaryont** [comment]
As 0.7.0 and 0.7.1 have been tagged and released, this issue is no longer relevant. Thanks for picking back up on that!
