### ISSUE TITLE
Embedded content pushes hide button too far to the right

### ISSUE THREAD

**Issue by azizLIGHT** [glowing-bear/glowing-bear#995]
If you expand embedded content like a gist inside a buffer, and if that gist has very long lines that extend beyond the browser window horizontally, then the 'Hide Gist' button is pushed as far as the longest line all the way to the right.

For instance, [this gist](https://gist.github.com/norrs/34f25e6dd02cf5f7805d925f2663ab46) pushes the 'Hide Gist' button as far as the width of line 6 (the longest/widest line), when expanded. Since this issue affects mobile Firefox, desktop Firefox, and desktop Chrome (and probably others), those with small resolutions have horizontal scrollbars appear and causes a usability nightmare, especially on mobile.

The embedded content should not influence the positioning of the hide button. Instead, the hide button should behave like the 'show gist' button in terms of positioning on the screen and be visible at all times

**Comment by lorenzhs** [comment]
Yes, we need to enforce a max-width on the embeds.

**Comment by azizLIGHT** [comment]
I think this is a duplicate of #957
