### ISSUE TITLE
Horizontal scrollbar has no indicator on Chrome

### ISSUE THREAD

**Issue by azizLIGHT** [glowing-bear/glowing-bear#996]
When embedded content like a gist is expanded, and has lines that extends very far to the right horizontally, then a horizontal scrollbar appears. On Firefox, the scrollbar has a indicator on it to show where we are currently scrolled to, and it can be manipulated with the mouse to move left/right. However, on Chrome, while there is a scrollbar that appears for the same situation, there is no indicator. The horizontal scrollbar on Chrome is just a black bar on the dark theme without a light gray indicator (like there is for vertical scrollbars). The horizontal scrollbar is functional, but is just missing a important visual cue as to where the scroll position is, horizontally.

**Comment by lorenzhs** [comment]
There isn't supposed to be a horizontal scrollbar under any circumstances, so fixing #995 would also fix this. And fixing #995 is what we should do, so I'll close this issue :)
