### ISSUE TITLE
Embedded content prevents browser title from being changed

### ISSUE THREAD

**Issue by azizLIGHT** [glowing-bear/glowing-bear#997]
When embedded content like a gist is expanded in a buffer, the browser title gets stuck on buffer where the embedded content was opened.  You could switch to another buffer, but the browser title will be talking about the buffer where the gist was opened. Hiding the gist where the gist was opened does not fix the title bar updating when buffers are switched. There is no way to fix this that I see besides refreshing the page and not opening the gist. This issue affects Firefox as well as Chrome.

**Comment by lorenzhs** [comment]
WTF. I can reproduce this, but it's rather confusing how expanding embeds could possibly have an influence on the page title changing. Seriously, wtf. Thanks for the report :)
